### ISSUE TITLE
如果启用增强硬解模式，播放画面简直不忍直视

### ISSUE THREAD

**Issue by Exvoke** [typcn/bilibili-mac-client#101]
如题，可以启用试试，颜色好像完全错误了...

**Comment by typcn** [comment]
硬件解码通常会自动使用 macbook 的  Intel 核显进行解码，如果没有核显，请禁用

**Comment by Exvoke** [comment]
用的是14年中的rmbp x72，iris5100的核显，之前的版本都是可以的...不知道发生了什么。不启用的话感觉发热量有点大...纠结

**Comment by typcn** [comment]
旧的 VDA 硬解已经在新的 OSX 中被移除了，现在只有 VideoToolBox 了，如果留着 VDA ，10.11 就不能用。。明天我给
apple 提个 bugreport

**Comment by Exvoke** [comment]
好的...麻烦了...

**Comment by typcn** [comment]
我今天使用 VideoToolBox 手动构建了播放器，貌似没法重现，也许是一个 ffmpeg 的 bug ，我再测试测试

**Comment by typcn** [comment]
检查了代码，问题出在 MPV 的 OpenGL Shader 上，已经发 issue

**Comment by typcn** [comment]
![image](https://cloud.githubusercontent.com/assets/8022103/9756728/f1575812-570e-11e5-9ee1-b3c17459401f.png)
使用新的黑科技播 720P 视频，能耗比 QQ 都低

**Comment by Congee** [comment]
看了mpv上的issue，然后测试` mpv --hwdec=videotoolbox --vo=opengl ~/Movies/foobar.mp4`，能正常硬解，但是bilibili-mac-client就不行

**Comment by typcn** [comment]
不知道为什么，链接的时候不能去掉旧的 VDA framework ，必须同时链接 VT 和 VDA 两个 framework 才能 work

**Comment by typcn** [comment]
请问有 10.11 的用户吗？ 帮忙看下  /System/Library/Frameworks/VideoDecodeAcceleration.framework/Versions/A/VideoDecodeAcceleration 
这个文件是否存在

**Comment by Exvoke** [comment]
已升级到2.07，此问题已消失，另外感觉发热小了很多，感谢！
