### ISSUE TITLE
播放某些分p的视频的特定p时2会在获取视频信息时意外退出

### ISSUE THREAD

**Issue by Exvoke** [typcn/bilibili-mac-client#109]
如题，比如 http://www.bilibili.com/video/av1409159/index_1.html 这个链接的第2p和第10p播放时会出现这样的问题。附上截图：2p
<img width="1000" alt="2015-09-21 12 53 35" src="https://cloud.githubusercontent.com/assets/12795904/9981840/453fe742-5ffb-11e5-99c4-f994e4c5214b.png">
10p 
<img width="989" alt="2015-09-21 12 54 27" src="https://cloud.githubusercontent.com/assets/12795904/9981842/58b5ac58-5ffb-11e5-886f-17173a763529.png">
已测试过用safari网页flash播放，播放正常。麻烦您了...

**Comment by typcn** [comment]
![image](https://cloud.githubusercontent.com/assets/8022103/9981858/d8322ff6-5ffb-11e5-86b3-8d89a4b0c29c.png)

我这里完全正常，看样子像 B 站的部分 API 服务器的问题

**Comment by Exvoke** [comment]
好的，明天我再试试...是b站的问题就好啦~

**Comment by Exvoke** [comment]
问题解决，换了个网就ok了~
