### ISSUE TITLE
自己发的弹幕有时候看不到

### ISSUE THREAD

**Issue by qinyuhang** [typcn/bilibili-mac-client#113]
iOS 版本的 bilibili 发完弹幕之后自己的弹幕又一个白色的方框把弹幕框起来，但是用 bilibili-Mac 的时候没有这种方框，而且从弹幕里面仔细找好像也找不到自己发的弹幕，给人一种弹幕发送失败的感觉。

**Comment by typcn** [comment]
B 站的弹幕池有缓存，等上几分钟再去看就有了
