### ISSUE TITLE
支持 mpv 配置文件

### ISSUE THREAD

**Issue by livelazily** [typcn/bilibili-mac-client#114]
是否能支持这个呢？
我现有的在 ~/.config/mpv/ 下的配置都不生效，想自定义各种快捷键都失败

**Comment by typcn** [comment]
可以支持，过几天加

**Comment by zanderzhng** [comment]
能不能支持 mpv 的 border=no，ontop=yes 之类的？
最好还能支持~/.config/mpv/下的脚本之类的。
换句话说，对有安装mpv的用户，让他们用自己的mpv。

**Comment by typcn** [comment]
加个“自定义 MPV 属性”吧 ，我做界面也渣，直接弄个文本框，里面填配置，在载入播放器的时候循环读取并设置。

**Comment by zanderzhng** [comment]
也行，用户可以用 [--config-dir](http://mpv.io/manual/master/#options-config-dir) 来重置 $MPV_HOME ，也可以直接在里边填几条短命令。

**Comment by typcn** [comment]
Added in 

https://github.com/typcn/bilibili-mac-client/commit/d61439ca28d077c015ec9ce5f4416985d112c140
https://github.com/typcn/bilibili-mac-client/commit/e6abe776a55a66a6a7cd861c3337d528c940483f
