### ISSUE TITLE
“本视频无法正常播放，你所访问的页面是盗播链接”

### ISSUE THREAD

**Issue by laike9m** [typcn/bilibili-mac-client#118]
![image](https://cloud.githubusercontent.com/assets/2592205/10391305/c01cce6c-6eb0-11e5-8352-8ef07d019541.png)

软件版本 2.11

**Comment by typcn** [comment]
页面地址？

**Comment by laike9m** [comment]
我测试所有视频都这样

**Comment by 15cm** [comment]
同样遇到此问题，版本2.1.1。比如[这个](http://www.bilibili.com/video/av1032829/)

**Comment by typcn** [comment]
我现在没法测试，请问看到此issue的其他用户有遇到吗？

**Comment by maemual** [comment]
上面15cm提到的例子我这里也是盗链的页面。

但是其他视频我点了好多都是正常播放的。

**Comment by geeeeeeeeek** [comment]
2.1.1，没有遇到

**Comment by typcn** [comment]
真是想不通，防盗链不是增加解析难度而是改网页

**Comment by typcn** [comment]
遇到盗链提示的用户，可以找找是user agent，还是其他header，或者是javascript触发的？分析下网页，谢谢了，现在没用mac

**Comment by typcn** [comment]
已重现，稍等修复

**Comment by typcn** [comment]
累死了，费了20分钟逆向拿到了一对新的appkey，增加了解析中的ts参数，稍等发布更新。

**Comment by laike9m** [comment]
d(`･∀･)b

**Comment by typcn** [comment]
国内更新已经发布，国外 Akamai 节点正在同步中

**Comment by typcn** [comment]
国外节点已更新，更新之后应该可以正常使用了

我经过测试 B 站封了我以前用的那对 APPKEY ，如果他们继续这样封的话，这样更新可能跟不上节奏。

可能需要考虑云端解析模块了，每次启动从服务器上动态读取代码并执行

**Comment by typcn** [comment]
![image](https://cloud.githubusercontent.com/assets/8022103/10392746/964ed8bc-6ebc-11e5-915c-74b29c99cf1c.png)
![image](https://cloud.githubusercontent.com/assets/8022103/10392749/a5fb9c28-6ebc-11e5-9f6c-bfc93f5b08b4.png)

appkey 输入一堆 123 都能解析出低画质视频，但是使用客户端原来使用的 appkey，会得到 copyright.mp4 ，很明显，这次的 API 更新就是针对这个来的。

真是想不通，那些解析 B 站直接在自己的播放器里面盗链的网站都 P 事没有，去封这种完全公益性的软件，而且我连界面上的广告都没有屏蔽，不知道这群人是怎么想的。

**Comment by kiddik** [comment]
更新后已经可以正常播放了，感谢typcn～

**Comment by typcn** [comment]
明天加一个功能，每隔 5 分钟从服务器上下载一次 .dylib ，把解析函数放到 dylib 里面，客户端动态载入代码到内存中执行（当然会有数字签名校验+证书校验），这样有算法更新就不需要更新本体了，用户无感知就可以完成。

明天把 安卓 + iOS 最新版的客户端都逆一遍，再上 IDA 把 alchemy 里面动态提取出来，上三套备用方案。

**Comment by laike9m** [comment]
:clap: :clap:  大大效率就是高 :+1:
