### ISSUE TITLE
更新后还是有防盗链。。

### ISSUE THREAD

**Issue by Ikaroshu** [typcn/bilibili-mac-client#119]
动画或者其它视频都不行。

开启或者关闭伪造IP也都不行。。

**Comment by htc550605125** [comment]
昨天晚上还是可以的，今天早上就不行了。

**Comment by typcn** [comment]
我日，神经病吧，稍等修复

**Comment by typcn** [comment]
这次反编译他们安卓客户端拿到的APPKEY，然后UserAgent和各种header，甚至参数的顺序都一样。

如果他们再封杀这个版本，他们官方的最新版客户端也会失效

**Comment by typcn** [comment]
已经发布 2.13 ，请大家点击检查更新

**Comment by typcn** [comment]
软件更新服务器遭到大量 DDoS 攻击，且所在域名 eqoe.cn 的备案号被注销。

现在放上了 Fastly CDN

**Comment by typcn** [comment]
没想到这些人是这幅嘴脸

**Comment by Ikaroshu** [comment]
这太疯狂了。。

**Comment by dont10** [comment]
2.13下载会直接闪退，就我一个这样吗？

**Comment by typcn** [comment]
额。。。是个BUG，获取当前URL的时候，等下和动态解析模块一起更新吧

**Comment by dont10** [comment]
好勤快，点赞。bishi商业化后真是越来越讨厌了。

**Comment by typcn** [comment]
跟 B 站的人联系了一下，说可以我们分配一个独立的 appkey ，稍等等吧

**Comment by laike9m** [comment]
坐等

**Comment by matthew-z** [comment]
希望能握手言和  毕竟没有直接利益冲突    怪 B 站不支持 HTML5

**Comment by typcn** [comment]
有人反馈又出问题了，请问大家有遇到么

**Comment by laike9m** [comment]
没在用 Mac。b 站的人说一套做一套啊(╯‵□′)╯︵┻━┻

**Comment by typcn** [comment]
我现在还没换，他们还没提供给我新的key，现在是他们安卓客户端

**Comment by Ikaroshu** [comment]
更新2.13，刚测试了两个视频，一切正常。
