### ISSUE TITLE
增量更新不起作用

### ISSUE THREAD

**Issue by JokerQyou** [typcn/bilibili-mac-client#121]
提示是增量更新，但是抽出 21MB+ 本体，并且抽出时网络流量也一直在走，似乎并不是增量更新。
版本 `v 2.12`。

**Comment by typcn** [comment]
这种情况是增量patch apply失败或者 sign mismatch 造成的

**Comment by typcn** [comment]
我看了一下 CDN 的 Log，大部分用户还是成功的，部分情况下可能会失败，但是目前找不到原因

**Comment by typcn** [comment]
找到原因了，是打包时候的路径问题，在 2.15 中已经修复
