### ISSUE TITLE
就希望有个能关闭弹幕的功能...就想静静看

### ISSUE THREAD

**Issue by MinweiShen** [typcn/bilibili-mac-client#124]

**Comment by geeeeeeeeek** [comment]
这个还真有，在播放器中把字幕关了就行了。

![wechat_1444798055](https://cloud.githubusercontent.com/assets/7262715/10475076/c880fd52-7271-11e5-9cb6-e898e7799d98.jpeg)

**Comment by MinweiShen** [comment]
好吧...有点隐蔽没发现啊...
