### ISSUE TITLE
缓冲每次都停在10s+73M

### ISSUE THREAD

**Issue by matthew-z** [typcn/bilibili-mac-client#128]
请问是设置了缓存上线嘛  以前也是这样 

打开视频暂停的话只能缓冲10s+73M

另外  在线播放缓冲跟下载视频的机制是一样嘛   因为想在办公室下载缓存视频  又怕被网关抓....

![qq20151018-0](https://cloud.githubusercontent.com/assets/5741303/10562539/3413ccd0-759b-11e5-912f-890067776bc1.png)

**Comment by typcn** [comment]
没设置上限啊，应该是 mpv 默认的？ 是不是内存填满了？

**Comment by matthew-z** [comment]
系统总的内存应该是没问题  8G 的 MBA, 看了下还有2G 没用.

**Comment by typcn** [comment]
奇怪，我这里打开就缓冲完全片，我看看有没有相关设置

**Comment by typcn** [comment]
服了，升级 10.11 输入法第一次聚焦之后 100% 掉字，切换一下才能输入

mpv 有个 buffer 位置和大小的设置，我一会整合到设置面板里吧

**Comment by matthew-z** [comment]
Thank you!

**Comment by sequencer** [comment]
同只能缓存到73MB
MacBook Air 2013 顶配

**Comment by typcn** [comment]
需要注意的是，播放时的视频缓存全部在内存中，尽量不要大于总内存的 1/2
