### ISSUE TITLE
或许可以增加一个本地视频加载在线弹幕的功能？

### ISSUE THREAD

**Issue by clockcloud** [typcn/bilibili-mac-client#131]
windows下有款 蛋蛋play 的播放器。。功能不错，但mac下没找到类似的工具。。

**Comment by qinyuhang** [comment]
请去 Mac app store 搜索 射手影音。绝对物超所值。几乎所有美剧都可以匹配在线zm

**Comment by JokerQyou** [comment]
+1.

好像下载视频不会同时下载弹幕了，下载好了视频却只能加载本地弹幕，但本地又没有弹幕……真是孤独啊

**Comment by htc550605125** [comment]
@JokerQyou 下载视频时会下载弹幕的，是那个 xml 文件，播放本地文件的时候选上就有弹幕。

**Comment by JokerQyou** [comment]
然而我昨天下载了一部电影，并没有下载弹幕。之前我记得下载视频是会同时下载弹幕的。
建议增加单独下载弹幕的功能。
