### ISSUE TITLE
mpv播放时字幕字体大小不一

### ISSUE THREAD

**Issue by kimgogo** [typcn/bilibili-mac-client#133]
<img width="1292" alt="1014731012" src="https://cloud.githubusercontent.com/assets/14231747/10660059/f5dd01d6-78ef-11e5-81ea-2387599103f5.png">
弹幕字体改用成langtinghei之后出现字体大小不一的状况。默认丽黑就没问题。删除/users/shared/.fc重建缓存问题依旧。

**Comment by typcn** [comment]
如果某个字体字库不全，不存在某些字的时候，会 fallback 到其他字体，导致这种情况，可以下载一些全的字体（这类字体通常大于30MB）扔进去。

**Comment by kimgogo** [comment]
谢谢了，我似乎找到问题了。原来好像是字体的名字没输入对。不过我想问下不同字重可以设置吗？之前的mpv也是不会设置字重。

**Comment by typcn** [comment]
暂时没有做，参数是这个： sub-scale

**Comment by typcn** [comment]
Added in 

https://github.com/typcn/bilibili-mac-client/commit/d61439ca28d077c015ec9ce5f4416985d112c140
https://github.com/typcn/bilibili-mac-client/commit/e6abe776a55a66a6a7cd861c3337d528c940483f
