### ISSUE TITLE
[Chrome 插件] [Feature request] 允许用户选择使用flash播放器

### ISSUE THREAD

**Issue by SsnL** [typcn/bilibili-mac-client#136]
希望能够加一个button，能让用户使用flash播放器。我个人不是很想为了看一眼一个视频再去开一下app。

**Comment by typcn** [comment]
可以暂时在“插件”菜单中禁用，按钮明天加

**Comment by typcn** [comment]
目前已经完成与 Bilibili 助手的整合，你可以同时安装 Bilibili 助手，实现 HTML5 播放器，Flash 播放器，Mac 客户端播放器的一键切换

**Comment by typcn** [comment]
助手地址 https://chrome.google.com/webstore/detail/%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E5%8A%A9%E6%89%8B%EF%BC%9Abilibilicom-%E7%BB%BC%E5%90%88%E8%BE%85%E5%8A%A9%E6%89%A9%E5%B1%95/kpbnombpnpcffllnianjibmpadjolanh

（Helper https://chrome.google.com/webstore/detail/bilibili-mac-client-helpe/njfkchgcdllehlpohbhmfjbcojolkafa）

**Comment by SsnL** [comment]
谢谢
