### ISSUE TITLE
打开特定视频时崩溃

### ISSUE THREAD

**Issue by htc550605125** [typcn/bilibili-mac-client#139]
http://www.bilibili.com/video/av198810/

https://gist.github.com/htc550605125/2c29ba7723c2ba1d0984

**Comment by typcn** [comment]
弹幕解析失败，一般是临时+特定地区的情况，你现在试试可能就好了。

最近发现 B 站部分老视频，在一些情况下，弹幕文件最后会缺少一个字符。

比如 <i> 内容 </i  ，这样没有闭合，可能是这个问题造成的，一会回来修一下
