### ISSUE TITLE
客户端最小化时，点击dock中的图标不能唤出窗口

### ISSUE THREAD

**Issue by fortissimoX** [typcn/bilibili-mac-client#142]
RT，测试环境 RMBP15‘ OS X 10.11.1

**Comment by typcn** [comment]
如果是 Chrome 扩展自动开启的，是无 GUI 方式启动的，不会显示窗口，退出再打开即可。

如果是点击左上角的最小化按钮，显示窗口是点击垃圾桶左边的窗口缩略图

**Comment by fortissimoX** [comment]
我的意思是正常的应用可以通过点击dock中的图标唤出窗口，Bili客户端不行。
我还以为是bug＝ ＝

**Comment by typcn** [comment]
OSX 默认是不会呼出的。。。。那些应用应该是做了特殊处理。。我也处理一下吧

**Comment by fortissimoX** [comment]
蟹蟹大大> <
