### ISSUE TITLE
mpv配置文件无效

### ISSUE THREAD

**Issue by join98** [typcn/bilibili-mac-client#145]
# No window border
no-border
随便加了一句无边框的没效果，最好还能提供一下input.conf的修改好改一下键位输入，或者能否告知一下客户端里mpv播放器的配置文件在哪个目录，如果要自己建立应该建在哪个目录下，我自己去改。百度云插件播放视频那里为什么有3个按钮，强迫症有点不舒服哈哈。客户端非常好，谢谢

**Comment by typcn** [comment]
no-border=yes
这样设定选项

不过 mpv 窗口相关的配置可能不会生效，因为 mpv 是作为 view 嵌入进来的

也可以用 conf-dir=xxx 来重定向配置文件夹到你自己的配置
