### ISSUE TITLE
播放界面mpv的OSC字体大小不一

### ISSUE THREAD

**Issue by oscar-c** [typcn/bilibili-mac-client#147]
![mpv截图](http://d.pr/i/1b3W8+)
（注意“年轻气盛”那几个字）
mpv里面OSC的中文字体大小不一，弹幕的字体倒是没有这个问题。

*Edit1:  OSD -> OSC

**Comment by typcn** [comment]
这是什么奇葩问题。。。 感觉这应该是某个繁体或者是日文字体？
不过这个不怎么影响，暂时先放一下

**Comment by oscar-c** [comment]
希望能支持调用自己装好的mpv，这样配置文件什么的都好搞。

**Comment by typcn** [comment]
点击设置，有个MPV选项，可以自定义配置

**Comment by oscar-c** [comment]
以及这些文字都是简体中文

**Comment by typcn** [comment]
日文和繁体的字体集里面也包括一部分简体的，有些字有有些没有，就会有这种情况

**Comment by oscar-c** [comment]
我在设置里面用的字体是STHeiti，我还不知道怎么改OSD的字体

**Comment by oscar-c** [comment]
OSC的配置文件要单独创建在 lua-settings/osc.conf 里面，用bilibili客户端的mov配置选项管不着。

https://mpv.io/manual/stable/#configuration

**Comment by typcn** [comment]
conf-dir

**Comment by oscar-c** [comment]
意思是加一行`conf-dir=~/.config/mpv`吗？
我的`~/.config/mpv`里面是保存了有效的配置的，但是加上`conf-dir=~/.config/mpv`这句之后bilibili那边没有体现出变化

**Comment by typcn** [comment]
我现在没法测试，一会回去看一下

**Comment by typcn** [comment]
```
1.15   - mpv_initialize() will now load config files. This requires setting
         the "config" and "config-dir" options. In particular, it will load
         mpv.conf.
       - minor backwards-compatible change to the "seek" and "screenshot"
         commands (new flag syntax, old additional args deprecated)
```

Try This: 
config=mpv.conf 
config-dir=mpvconfdir

https://github.com/mpv-player/mpv/blob/master/DOCS/client-api-changes.rst

**Comment by oscar-c** [comment]
加了一行`config-dir=/Users/[我用户名]/.config/mpv`，没啥效果
我把mpv的配置文件移到别处，然后在`~/.config/mpv/mpv.conf`里用`config-dir`来指出另外一个存放了配置文件的目录，本机的mpv也不承认config-dir的效果。

**Comment by typcn** [comment]
我上次编译的 MPV 版本是 392ae68e5f802e940b7b7f5a139af7e2698b5e0e

这个时候 client api changes 已经加入了这几行说明啊。。
