### ISSUE TITLE
进入视频页面后会自动启用独显

### ISSUE THREAD

**Issue by zhuangluda** [typcn/bilibili-mac-client#150]
印象中2.15版本没有此问题（不知道有没有记错），更新到2.17后就有了。
很明显使用集显就够用，而且省电

**Comment by zhuangluda** [comment]
仅供参考：https://developer.apple.com/library/mac/qa/qa1734/_index.html

**Comment by typcn** [comment]
程序是没有办法控制这个的。。很可能加了之后一样会启用独显。
而且这个属性也没有办法动态添加修改。。

**Comment by zhuangluda** [comment]
我这里加了以后效果还挺好的，至少他能自动切回核显

**Comment by typcn** [comment]
主要是这玩意有缓存，用程序改了之后很可能不会立即生效

**Comment by zhuangluda** [comment]
你可能理解错了，这个属性并不需要用代码修改，只要加到项目的Info.plist里就可以了。
NSSupportsAutomaticGraphicsSwitching为false的话，一旦切到独显后就不会再切回来了，设置为true以后可以自动切回核显。
 the MacBook Pro automatically switches to the higher-end discrete GPU for performance concerns and won't switch back until the application quits.

**Comment by typcn** [comment]
em.. 好吧，我以为是用核显来渲染 OpenGL 画布，怕会出问题而加选项

**Comment by zhuangluda** [comment]
核显应该不会出问题的吧。。。不然13寸的不是全跪了。。

**Comment by typcn** [comment]
也许有人喜欢用独显之类的吧。。 

Added in https://github.com/typcn/bilibili-mac-client/commit/20540b58b7251cb3bdd53e4eabecf0a996b2921c

**Comment by zhuangluda** [comment]
。。。。
那你看着办吧。。不行的话每次更新后我手动加也可以。。

**Comment by typcn** [comment]
Added in 20540b5

**Comment by zhuangluda** [comment]
之前看到的，谢谢~

**Comment by anamewing** [comment]
拜谢！之前被这个问题困扰挺久了，但一直觉得未必是bug而无法提。

**Comment by typcn** [comment]
没事，只要不是“不能用”，“崩溃” 这种几个字 ＋ 没说明／错误报告／Log 的信息我都会去找问题的。。。
