### ISSUE TITLE
海外党伪装 IP 失效

### ISSUE THREAD

**Issue by matthew-z** [typcn/bilibili-mac-client#165]
现在打开任意新番的专题一律404
直接点新番视频提示"由于版权相关问题 我们不对您所在的地区提供服务"

 chrome+unblock youku 也是一样的结果

坐标日本..

**Comment by typcn** [comment]
我买一台国内服务器反代，明天更新

**Comment by matthew-z** [comment]
呃 谢谢 辛苦了....

昨天问了几个朋友都相同的情况还以为是 B 站改了设置   然而不知道今天为什么莫名其妙又恢复了=.=

不好意思啊

**Comment by typcn** [comment]
那是他设置问题了吧，那暂时不用动了
