### ISSUE TITLE
优酷插件失效

### ISSUE THREAD

**Issue by lisonma** [typcn/bilibili-mac-client#170]

**Comment by lisonma** [comment]
优酷不能看了..

**Comment by typcn** [comment]
修复了，稍等发布插件更新，无需更新软件本体

（感谢 https://github.com/zythum/mama2 的算法）

**Comment by typcn** [comment]
已经更新，进入插件中心点击更新按钮即可使用。

以及新增百度云下载功能，免会员无视限速。

（算法一样是别人的 233 来自 https://github.com/acgotaku/BaiduExporter ）

**Comment by lisonma** [comment]
感谢, 新增的百度云下载功能不能下载未保存到网盘的资源, 之前的 BaiduExporter 插件可以导出..
