### ISSUE TITLE
弹幕字体设置无效

### ISSUE THREAD

**Issue by sensssz** [typcn/bilibili-mac-client#171]
![image](https://cloud.githubusercontent.com/assets/1689179/11433219/2c805914-9488-11e5-95db-41a7f92ba662.png)
![image](https://cloud.githubusercontent.com/assets/1689179/11433232/70ff9564-9488-11e5-96e1-1f5fe6af3c98.png)
我已经设置了弹幕字体为 Hiragino Sans GB，但是从图上看来设置明显是无效的，删除缓存 (/Users/Shared/.fc) 重建也没有用。我的系统语言为英文，也有怀疑过是不是系统语言设置导致字体 fallback 有问题，但是改为中文重建缓存之后还是一样，系统能够改进一下这个问题，现在弹幕字体看着真的太不舒服了。

**Comment by typcn** [comment]
/Linrary/Fonts 另外字体要填简写：例如 STHeiti Heiti SC

**Comment by sensssz** [comment]
你是说，虽然设置里面写字体必须在 /System/Library/Fonts 里面，但是实际上是在 /Library/Fonts 里面找的字体？还有这个简写是什么意思？不是直接拿字体的文件名吗？

**Comment by sensssz** [comment]
好吧，反正我把 Hiragino Sans GB 的字体文件复制到 /Library/Fonts 下面就可以了，为什么只在 /Library/Fonts 下面找字体文件啊？

**Comment by typcn** [comment]
编译的时候一个小失误，之后我会专门在一个地方放字体

**Comment by sensssz** [comment]
好吧。建议默认使用 Hiragino，虽然苹方只能在新系统上使用，但是 Hiragino 旧版本的系统上都还是有的。STHeiti 这套字体实在是太难看了。
