### ISSUE TITLE
几点改进建议

### ISSUE THREAD

**Issue by MittWillson** [typcn/bilibili-mac-client#172]
今天刚下载使用 感觉确实很厉害 作为同样未成年 我很落后哇 (U •́ .̫ •̀ U)

虽然个人感觉不习惯浏览器式风格, 但还是觉得这样也不错 嘿嘿。
1. 建议播放器和浏览器分开 有个问题就是如果我切到其他地方 想调出正在播放的视频就比较麻烦
2. 希望能实时调整画质
3. 捐助页面的支付宝链接已挂。

**Comment by typcn** [comment]
1. 右键点击图标，就有名为视频名称的窗口
2. 实时切换因为目前播放器的问题很难做到，而且换了分辨率还得重新 load 弹幕
3. 支付宝关掉了接口，现在换成二维码了

另外：今天由于服务器硬件故障，挂了一段时间，恢复之后又由于网络的配置问题一直没有 Online，所以 部分 CDN 缓存过期的地区会卡在连接服务器，现在已经恢复，非常抱歉。
