### ISSUE TITLE
safari扩展？

### ISSUE THREAD

**Issue by Ikaroshu** [typcn/bilibili-mac-client#173]
rt，不知道有没有可能将已有的chrome扩展移植到Safari上？

**Comment by typcn** [comment]
客户端本身就是 Safari 壳吧..

**Comment by Ikaroshu** [comment]
啊，抱歉没表达清楚，我是指能否提供一个Safari的插件，这样就可以在Safari上直接启动播放器而不必再单开客户端了。就像chrome扩展做到的那样。

**Comment by typcn** [comment]
刚看了下相关文档和 Chrome 没太大差别，如果大家有时间可以贡献一个，
我可能需要迟一段时间

**Comment by Ikaroshu** [comment]
喔喔，感谢！
