### ISSUE TITLE
地址栏输入文字内容直接B站搜索，以及地址栏输入av123456编号直接跳转

### ISSUE THREAD

**Issue by VersusClyne** [typcn/bilibili-mac-client#175]
如题－，－这个似乎不难，感谢菊苣orz

**Comment by typcn** [comment]
我决定加一个类似 Chrome 的智能提醒，显示选项，搜索 B站 / 搜索 XXX 之类的233（好像更像浏览器了

**Comment by typcn** [comment]
![image](https://cloud.githubusercontent.com/assets/8022103/11842975/e9e30d1c-a441-11e5-89a0-a3c70d0fe464.png)
目前效果是这样，不过还是有一些 BUG ，明天更新

**Comment by fortissimoX** [comment]
求顺便加个cmd+L到地址栏

**Comment by typcn** [comment]
全部加了，现在支持了在线 suggest ，也支持本地热点 URL 持久化 suggest
