### ISSUE TITLE
百度盘的链接失效啦

### ISSUE THREAD

**Issue by petter1102** [typcn/bilibili-mac-client#176]
RT
紧紧是提醒0v0

**Comment by typcn** [comment]
我给百度提交了一个反馈，不过短时间内估计不会得到回复，我先加个cdn地址吧

**Comment by petter1102** [comment]
Roger~

**Comment by typcn** [comment]
![image](https://cloud.githubusercontent.com/assets/8022103/11693914/7c6a7900-9ee2-11e5-8efd-ac6c607612a7.png)
重新分享了一个貌似可以？

**Comment by petter1102** [comment]
OK！可用！

**Comment by typcn** [comment]
![image](https://cloud.githubusercontent.com/assets/8022103/11712634/4fbcd574-9f69-11e5-9bae-e4e7c1c549ca.png)
![image](https://cloud.githubusercontent.com/assets/8022103/11712644/5ead5ed2-9f69-11e5-878d-e1a7786448af.png)

响应还挺快，恢复了
