### ISSUE TITLE
下载的视频有多个分段该如何播放？

### ISSUE THREAD

**Issue by HatCloud** [typcn/bilibili-mac-client#177]
本地播放选中第一个视频只会播放该视频。
比如我下载的这个“狼的孩子雨和雪”，有20个分段之多。有办法能像播放在线视频一样的播放它们吗？
<img width="824" alt="2015-12-13 4 17 13" src="https://cloud.githubusercontent.com/assets/7430550/11766167/ff14f4e6-a1b4-11e5-9870-e5f95a3eab4e.png">

**Comment by typcn** [comment]
这是分P还是分段。。。 尝试下载MP4格式的视频？

如果需要的话我会在之后加入自动合并多个视频的功能，目前需要用 ffmpeg 合并多个视频

**Comment by HatCloud** [comment]
是分段，这个视频只有1P，我试试下载MP4

**Comment by HatCloud** [comment]
倒不一定要合并视频，能够一个接一个地播放也行，我记得以前用AcDown的时候，是可以直接播放一个文件夹里的所有视频分段的，就是切换不同分段的时候会卡一下

**Comment by HatCloud** [comment]
果然MP4画质损失好严重，还是在线看吧

**Comment by typcn** [comment]
Fixed in https://github.com/typcn/bilibili-mac-client/commit/4a29885ceace490ecba7585c06e1c07c522229cd

“选择文件”现在可以选择多个文件了，如果选择了多个文件，则会自动把它们连接成一个视频进行播放
