### ISSUE TITLE
播放时显示视频信息

### ISSUE THREAD

**Issue by htc550605125** [typcn/bilibili-mac-client#178]
希望能在播放时查看 视频/音频 码率/格式 以及源url 下载速度 的信息

**Comment by typcn** [comment]
下载速度是在 ffmpeg 那边的，加这些东西得改 mpv 的源码，暂时先输出到 log 里吧，打开 console 就能查看

**Comment by typcn** [comment]
Fixed in https://github.com/typcn/bilibili-mac-client/commit/20b94c2f5bfac919aa89515750c1ae2bbe8fef13
