### ISSUE TITLE
百度云盘的播放功能疑似失效

### ISSUE THREAD

**Issue by chliul** [typcn/bilibili-mac-client#181]
勾选文件后上方并未出现播放按钮
客户端版本：2.23
百度云插件版本：2
症状如截图：
![default](https://cloud.githubusercontent.com/assets/7077748/11913489/4413933c-a6a0-11e5-8374-9b5e6ef786ee.jpg)

**Comment by typcn** [comment]
百度改版造成的，wait

**Comment by typcn** [comment]
诶，我看你图中的界面依然是旧版的界面，难道是百度在做 A-B Test ？这种情况略蛋疼啊

**Comment by chliul** [comment]
难道我被针对了。。。＝w＝

**Comment by typcn** [comment]
Should Fixed in 2.24
