### ISSUE TITLE
2.2.3新版本无法观看直播

### ISSUE THREAD

**Issue by sunnysk** [typcn/bilibili-mac-client#182]
2.2.3 无法直播

**Comment by typcn** [comment]
沃日，我明明只请求了 1000 个字节的数据，他却源源不断的返回了无限长的数据

**Comment by sunnysk** [comment]
好修复么。我用2.1.4版本可以看直播

**Comment by typcn** [comment]
回收站里会自动保存上一个版本，可以先用着，晚上更新

**Comment by sunnysk** [comment]
好的。修复了话close一下这个issue，我就马上更新了，摸摸大

**Comment by typcn** [comment]
Should Fixed in 2.24
