### ISSUE TITLE
求有空的时候添加几个比较简单的可以通过html5实现的功能

### ISSUE THREAD

**Issue by laserroger** [typcn/bilibili-mac-client#184]
1. 循环播放
1. 声音大小修正

可能不好做的东西

1. 弹幕透明度

阿里嘎多

**Comment by typcn** [comment]
循环播放按 X 键即可
声音大小按 ⬆️  和 ⬇️

透明度设置里面有。。。

**Comment by typcn** [comment]
![image](https://cloud.githubusercontent.com/assets/8022103/11947534/354e9ae0-a8a3-11e5-8972-e3f3bd23a142.png)
