### ISSUE TITLE
媒體鍵的自定義問題

### ISSUE THREAD

**Issue by sequencer** [typcn/bilibili-mac-client#186]
有時候開了軟件之後想要暫停iTunes，卻發現媒體鍵被佔用了，希望可以有選項關閉媒體鍵功能

**Comment by izhaomin** [comment]
+1, 迫切希望。

**Comment by typcn** [comment]
![image](https://cloud.githubusercontent.com/assets/8022103/12077469/6d793cf0-b220-11e5-849c-5b2d0a2ea1d4.png)
晚上改吧，一会要出去

**Comment by typcn** [comment]
选项已增加，一会更新

**Comment by typcn** [comment]
Added in 2.25

**Comment by sequencer** [comment]
英文適配 233 強迫症 還要麻煩一下

**Comment by typcn** [comment]
英文适配下次再加。。。最近比较忙
