### ISSUE TITLE
You-get 插件无法使用

### ISSUE THREAD

**Issue by chliul** [typcn/bilibili-mac-client#190]
最新版本客户端：2.25
You-get版本：1
在各视频网站下测试，点击右上角播放按钮后，均出现视频解析失败，返回错误信息为空
![default](https://cloud.githubusercontent.com/assets/7077748/12223687/c110e2f2-b818-11e5-8e47-9a2ddf747c14.jpg)

**Comment by typcn** [comment]
2.26 已修复，尝试更新软件版本＋插件版本
