### ISSUE TITLE
打开Bilibili出现unblock youku失效画面？

### ISSUE THREAD

**Issue by naijim** [typcn/bilibili-mac-client#195]
打开bilibili客户端后出现一个画面提醒unblock youku失效了，提示需要继续使用服务必须要下载unblockcn客户端，请问这个和bilibili客户端有没有关系？

**Comment by typcn** [comment]
没听说过这个，发个截图？

**Comment by naijim** [comment]
http://imgur.com/GwuF9qk

**Comment by Hs-Yeah** [comment]
难道是 DNS 劫持的玩意？ Unblocker/Unblock-Youku#468

**Comment by typcn** [comment]
这个与软件无关，应该是网络流量被劫持的而出现的，这个看起来并不是 unblock youku
的官方版本，而是通过设置代理劫持流量等方式而实现的（当然也可能是路由器上）第三方版本，如果你不需要 unblock youku
的劫持，可以暂时关掉或者将B站排除，软件的设置中已经自带了伪造IP地址的功能，如果你需要这个劫持软件，可以尝试照他的步骤操作。

**Comment by naijim** [comment]
好的，我自己看看怎么解决

**Comment by typcn** [comment]
看了下那个 issue，那完全就是个流氓软件，执行以下步骤：
1. 卸载关于 UnBlockCN 的所有组件
2. 关掉代理设置
3. （如果dns被改的话）dns 服务器设置为默认或者 8.8.8.8

**Comment by naijim** [comment]
把DNS改成8.8.8.8了，又把系统自动代理清空了，好像还是不行呢，我也没有装那个Unblockyoukucn

**Comment by typcn** [comment]
这么坑爹？
执行： nslookup www.bilibili.com 和 curl -vv http://www.bilibili.com ，然后贴一下返回结果

**Comment by naijim** [comment]
jack@Walnut  →  nslookup www.bilibili.com
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
www.bilibili.com	canonical name = bilibili.hdslb.net.
Name:	bilibili.hdslb.net
Address: 69.147.251.42

jack@Walnut  →  curl -vv http://www.bilibili.com
* Rebuilt URL to: http://www.bilibili.com/
*   Trying 69.147.251.42...
* Connected to www.bilibili.com (69.147.251.42) port 80 (#0)
> GET / HTTP/1.1
> Host: www.bilibili.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 14 Jan 2016 21:02:47 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Server: Tengine
< Expires: Thu, 14 Jan 2016 21:03:17 GMT
< Cache-Control: max-age=30
< X-Cache: HIT from us-newyork-ubi.hdslb.com

**Comment by naijim** [comment]
根据这个 https://support.apple.com/en-us/HT202516
重置了本地DNS Cache，貌似没用的样子，我试试重启好了

**Comment by StoneMoe** [comment]
检查hosts，系统偏好设定中网络部分的代理选项，DNS选项

**Comment by naijim** [comment]
重启了电脑，并没有什么用。。。
这是DNS的截图 http://imgur.com/ChQtPEq
这是代理的截图 http://imgur.com/U1XTBSI

**Comment by typcn** [comment]
并不像是这些问题，因为他刚刚 curl 已经落到 B 站的 cdn 上并且正确返回结果了...... 很诡异，也许是网页缓存？

加个参数试试 http://www.bilibili.com/?v=2

还是不行就得怀疑 dylib注入，路由，网络环境了

**Comment by naijim** [comment]
好了 http://www.bilibili.com/?v=2 这个可以，非常感谢，是什么原理，v=2是什么

**Comment by typcn** [comment]
em... 可能是你刚刚的请求落在了劫持页面上，劫持页面的 header 里面指定了这个页面缓存 X
秒，加了参数之后等于就是请求了不同的页面，不会理会之前的页面缓存。

**Comment by naijim** [comment]
那就是网页缓存的问题了，感谢各位，那这个issue就关闭了

**Comment by naijim** [comment]
本来用unblockyoukucn是为了能用网易云音乐听歌的，现在解决了Bilibili的问题，听音乐的问题又回来了，我不打算继续用unblockyoukucn了，看来要找其他办法了

**Comment by typcn** [comment]
网易云的话，用 Proxifier 之类的软件把 music.163.com 走国内代理，然后通过 17ce.com 查看 m1 到
m10.music.126.net 在国内的解析结果，把较快的 ip 放到 hosts 里面应该就可以了

**Comment by zhuzhuor** [comment]
@naijim 我是 Unblock Youku 的开发者，想问你之前安装过 UnblockCN 的软件吗？即便是安装后立马卸载了

想知道 UnblockCN 显示这页面的原理是什么

**Comment by tommyzhaozbh** [comment]
网易云音乐的问题请看看这里能不能解决 Unblocker/Unblock-Youku/issues/488

**Comment by typcn** [comment]
@tommyzhaozbh 网易云音乐是对国外 IP 的 DNS 解析到了 1.1.1.1 ，解决方法也很简单

通过 17ce 检测 m* 的域名 ，获得 IP 地址
http://www.17ce.com/site/dns/201601_36672a4d5f2fe5047580598b05cd0f6a.html

比如我们要使用这个 IP 14.215.9.79，就拼接 URL 为

http://14.215.9.79/m2.music.126.net/原来的路径?wsiphost=local

这个参数很关键，为了避免再次 302 ，需要加上 wsiphost 的 参数。

这是网宿 CDN 的一些特性

@zhuzhuor 显示这个页面的原理无非就是 PAC 了吧，因为他可以记录用户的 IP 地址，以及他是代理服务器，可以任意修改 http header 里的 Cookie 等信息，一旦用户使用达到多长时间，就自动把这个页面代理到他之前做好的服务器上

**Comment by naijim** [comment]
@zhuzhuor 以前没有装过那个插件
