### ISSUE TITLE
播放本地视频时的问题

### ISSUE THREAD

**Issue by JokerQyou** [typcn/bilibili-mac-client#197]
两个问题：

- 播放本地视频的话，浏览器窗口会被关掉，而不是像在线播放那样隐藏。这会导致之前打开的 tab 全部丢失。
- 类似地，升级过程中重启了应用，启动后上次打开的 tab 就全部没有了。

两个 feature request：

- 可否在播放本地视频时只将浏览器窗口隐藏而不是关闭？
- 进一步地，可否提供设置选项（类似 Chrome）来让每次关闭窗口或退出应用后，下次打开浏览器窗口，仍然打开那些 tab？

**Comment by typcn** [comment]
这些浏览器的功能已经在计划中，但是最近有很多事还没有实现。。得到大概20号左右吧

**Comment by typcn** [comment]
2.26 注册了播放器，可以直接通过打开方式进行播放

**Comment by typcn** [comment]
Added in https://github.com/typcn/bilibili-mac-client/commit/2a8e1d7623e422afcc190e620dc7c4dff207ce21
