### ISSUE TITLE
OS X 10.9 无法载入窗口

### ISSUE THREAD

**Issue by typcn** [typcn/bilibili-mac-client#2]
如果哪位朋友知道怎么解决的话，麻烦告诉我一下，貌似 10.9 的窗口需要手动载入？我明天装一个虚拟机试试

**Comment by RexPi** [comment]
似乎是不支持storyboard

**Comment by typcn** [comment]
storyboard 应该是支持的吧？ 我在怀疑哪里设置错了，一会虚拟机装个 XCode 5 看看

**Comment by RexPi** [comment]
http://stackoverflow.com/questions/28318900/swift-storyboards-mac-osx-10-9-deployment
http://stackoverflow.com/questions/24203113/storyboards-for-osx-app-in-xcode-6
http://stackoverflow.com/questions/26614827/xcode-6-1-osx-apps-using-storyboard-does-not-render-window-or-menubar

**Comment by typcn** [comment]
擦。。。还得换成 XIB 啊

**Comment by RexPi** [comment]
或者放弃支持10.9【

**Comment by typcn** [comment]
有点不想支持了，但是 10.10 的比例并不大。
也许是旧版大部分是黑苹果？
![image](https://cloud.githubusercontent.com/assets/8022103/6957414/2743cf60-d92d-11e4-9ced-a2a0a0754bd6.png)

**Comment by RexPi** [comment]
黑苹果不少吧，但是应该也还有没升级的。
其实没什么特殊原因的话为何不升级【

**Comment by typcn** [comment]
暂时放弃支持，以后可能针对 10.9 发布补丁，但不保证全部功能可用。
