### ISSUE TITLE
视频分段顺序加载与mpv编译相关

### ISSUE THREAD

**Issue by htc550605125** [typcn/bilibili-mac-client#200]
播放视频时默认的似乎是视频分段一起下载的，我家网络带宽不大所以同时加载分段会导致第一分段的视频卡顿严重。

然后我尝试去看了一下源码，下载控制是在mpv里面的是吗？然后又fork了 https://github.com/typcn/mpv ，尝试build了一下

```
./waf configure --enable-libmpv-shared
./waf build
cp build/libmpv*.dylib ../bilibili-mac-client/bilibili/libs
```

然后这样会运行报错...

```
cp build/libmpv*.dylib /usr/local/lib
```

这样就跑起来了。不过播放器界面的字体好像出问题了。所以求问mpv编译使用的正确姿势？

**Comment by typcn** [comment]
需要用 dylib_unhell.py ，把相关文件放过去，然后用 install_name_tool 将文件的链接信息改成 当前可执行文件目录的
libs 文件夹，然后将 libs 文件夹内容与 libmpv 一同复制过去

**Comment by htc550605125** [comment]
编译了最新的mpv之后问题解决，变成单线程下载的了。
所以默认多线程下载不知道是版本原因还是什么导致的。

如果可能的话当然是希望能做成一个选项。

**Comment by typcn** [comment]
印象中一直都是不是多线程下载的，只是开始播放的时候要 probe 一下所有的分片。。

**Comment by htc550605125** [comment]
然而目前至少，你的release在我本机上运行的时候是多线程下载的

**Comment by htc550605125** [comment]
现象为，网络跑满（4M)，第一个分段特别卡，第一个分段播放完毕之后都是缓冲好的。

**Comment by typcn** [comment]
em.. 目前的版本好像确实是这样的，网络跑到几百 Mbps 却显示只缓冲了几秒，过几天我重新编译一下，最近忙飞了。

**Comment by htc550605125** [comment]
所以现在repo的lib里的mpv是哪个版本的呢？

**Comment by typcn** [comment]
repo 里的 libs 是跟着 release 走的

**Comment by htc550605125** [comment]
https://github.com/mpv-player/mpv/releases
这个？

**Comment by typcn** [comment]
这个是我自己编译的，上次编译应该是 37544e53dc0725d813ed3e525309a95b09c2d7fe

**Comment by htc550605125** [comment]
好的，我试试找一下是哪里的问题

**Comment by typcn** [comment]
2.26 更新到了最新的 mpv 和 ffmpeg， 测试一下

**Comment by htc550605125** [comment]
确认问题解决，不过没找到是mpv哪里的问题，那就不管了。
