### ISSUE TITLE
git clone 失败!

### ISSUE THREAD

**Issue by shenguanjiejie** [typcn/bilibili-mac-client#202]
git clone https://github.com/typcn/bilibili-mac-client.git
Cloning into 'bilibili-mac-client'...
remote: Counting objects: 5063, done.
remote: Compressing objects: 100% (167/167), done.
remote: Total 5063 (delta 85), reused 0 (delta 0), pack-reused 4896
Receiving objects: 100% (5063/5063), 38.77 MiB | 25.00 KiB/s, done.
Resolving deltas: 100% (3201/3201), done.
Checking connectivity... done.
git-lfs smudge 'bilibili/libs/aria2c': git-lfs: command not found
error: external filter git-lfs smudge %f failed -1
error: external filter git-lfs smudge %f failed
fatal: bilibili/libs/aria2c: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by typcn** [comment]
安装 git-lfs

brew install git-lfs

**Comment by shenguanjiejie** [comment]
太给力了 秒回啊 谢谢

**Comment by shenguanjiejie** [comment]
...安装过git-ifs了 还是报错:
$ git clone https://github.com/typcn/bilibili-mac-client.git
Cloning into 'bilibili-mac-client'...
remote: Counting objects: 5063, done.
remote: Compressing objects: 100% (167/167), done.
remote: Total 5063 (delta 85), reused 0 (delta 0), pack-reused 4896
Receiving objects: 100% (5063/5063), 38.77 MiB | 37.00 KiB/s, done.
Resolving deltas: 100% (3201/3201), done.
Checking connectivity... done.
WARNING: These git config values clash:
  git config "include.path" = "~/.gitcinclude"
  git config "include.path" = ".githubconfig"
WARNING: These git config values clash:
  git config "include.path" = ".githubconfig"
  git config "include.path" = ".gitcredential"
Downloading bilibili/libs/aria2c (3.31 MB)
Error accessing media: bilibili/libs/aria2c (f3649fbe44d98c65dc8e5017bd321c5386e197ddf34c50d5afd6923d6ab6e4ed)

Errors logged to .git/lfs/objects/logs/20160129T171445.975104852.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge %f failed 2
error: external filter git-lfs smudge %f failed
fatal: bilibili/libs/aria2c: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by typcn** [comment]
挂代理试试。。

**Comment by shenguanjiejie** [comment]
好 稍等~

**Comment by shenguanjiejie** [comment]
跟刚才一样 奇怪 快下班了 我明天试试吧 说不定重启就好了

**Comment by shenguanjiejie** [comment]
今天还是老样子 不知道是不是我这边电脑或者环境的问题

**Comment by typcn** [comment]
我这里怎么测试都可以正常 clone 和 checkout 啊。。

你输入 git lfs logs last 看一下日志？

**Comment by shenguanjiejie** [comment]
我是看不懂:
 git lfs logs last  
git-lfs/1.1.0 (GitHub; darwin amd64; go 1.5.1)
git version 2.6.3

$ git-lfs smudge bilibili/libs/aria2c
Error accessing media: bilibili/libs/aria2c (f3649fbe44d98c65dc8e5017bd321c5386e197ddf34c50d5afd6923d6ab6e4ed)

Error buffering media file: cannot write data to tempfile ".git/lfs/tmp/objects/f3649fbe44d98c65dc8e5017bd321c5386e197ddf34c50d5afd6923d6ab6e4ed-553217301": read tcp 192.168.2.108:49714->54.231.11.88:443: read: connection reset by peer
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
	/private/tmp/git-lfs20151119-47227-st469y/git-lfs-1.1.0/src/github.com/github/git-lfs/lfs/errors.go:557 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0x8af1e8, 0xc82063c000, 0xdacee0, 0xc82048dd60)
	/private/tmp/git-lfs20151119-47227-st469y/git-lfs-1.1.0/src/github.com/github/git-lfs/commands/commands.go:184 +0xf7f
github.com/github/git-lfs/commands.logPanic(0xdacee0, 0xc82048dd60, 0x0, 0x0)
	/private/tmp/git-lfs20151119-47227-st469y/git-lfs-1.1.0/src/github.com/github/git-lfs/commands/commands.go:148 +0x421
github.com/github/git-lfs/commands.handlePanic(0xdacee0, 0xc82048dd60, 0x0, 0x0)
	/private/tmp/git-lfs20151119-47227-st469y/git-lfs-1.1.0/src/github.com/github/git-lfs/commands/commands.go:123 +0x4e
github.com/github/git-lfs/commands.LoggedError(0xdacee0, 0xc82048dd60, 0x55a620, 0x1e, 0xc82011dc98, 0x2, 0x2)
	/private/tmp/git-lfs20151119-47227-st469y/git-lfs-1.1.0/src/github.com/github/git-lfs/commands/commands.go:73 +0x82
github.com/github/git-lfs/commands.smudgeCommand(0x75e040, 0xc820011a90, 0x1, 0x1)
	/private/tmp/git-lfs20151119-47227-st469y/git-lfs-1.1.0/src/github.com/github/git-lfs/commands/command_smudge.go:77 +0xd89
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0x75e040, 0xc8200119e0, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/git-lfs20151119-47227-st469y/git-lfs-1.1.0/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x403
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0x75f080, 0x0, 0x0)
	/private/tmp/git-lfs20151119-47227-st469y/git-lfs-1.1.0/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x46a
github.com/github/git-lfs/commands.Run()
	/private/tmp/git-lfs20151119-47227-st469y/git-lfs-1.1.0/src/github.com/github/git-lfs/commands/commands.go:88 +0x23
main.main()
	/private/tmp/git-lfs20151119-47227-st469y/git-lfs-1.1.0/git-lfs.go:34 +0x12e

ENV:
LocalWorkingDir=.
LocalGitDir=.git
LocalGitStorageDir=.git
LocalMediaDir=.git/lfs/objects
TempDir=.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
GIT_DIR=.git
GIT_WORK_TREE=.
GIT_PREFIX=

如果没有其他人反馈这种问题的话 那就应该是我自己的问题 作者费心了 不用再替我忙活了...

**Comment by typcn** [comment]
Connection reset by peer... 明显是网络问题

用 Proxifier 或者 proxychains 让 git 和 git-lfs 走代理就好了，当然挂上全局代理也可以

**Comment by shenguanjiejie** [comment]
稍等啊 是我傻了 我用的Shadowsocks 我发现是选的'自动代理模式'  现在改成'全局模式' 应该能行 网速略慢 等会看到结果再回复你

**Comment by shenguanjiejie** [comment]
不好使 算了 麻烦你了~
