### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by eccentricyan** [typcn/bilibili-mac-client#203]
第一次用xcode装，<a href="https://github.com/typcn/bilibili-mac-client/blob/master/HOW_TO_BUILD.md#add-crashlytics-key">这里</a>不是很明白。总之apikey文件设置好后，打开xcode, 然后打开bilibili，然后按三角键后发生下记错误。

```
ld: warning: directory not found for option '-F/Users/shiyanhui/bilibili-mac-client/Build/Products/Debug'
ld: library not found for -lharfbuzz.0
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
<img class="image" id="js-image" src="https://i.gyazo.com/42d7eccc803ffa759c510f45cbea0c22.png" style="width:auto;height:auto;max-width:100%;max-height:100%;" data-reactid=".1.1:5.0.1.0">

**Comment by typcn** [comment]
https://github.com/typcn/bilibili-mac-client/tree/master/bilibili/libs

这些文件下载失败了，可以手动重新下载

**Comment by eccentricyan** [comment]
@typcn 但是我有这些文件啊 怎么手动下载呀
<img width="569" alt="2016-01-29 20 53 59" src="https://cloud.githubusercontent.com/assets/10955785/12675023/be8ba916-c6ca-11e5-8318-fb054e427a57.png">

**Comment by typcn** [comment]
例如缺少 harfbuzz，就下载 
https://github.com/typcn/bilibili-mac-client/raw/master/bilibili/libs/libharfbuzz.0.dylib ，覆盖到本地的 bilibili/libs 文件夹里面

想要简单一点可以安装 gif-lfs 然后给它挂代理重新 git clone
