### ISSUE TITLE
直播的时候，弹幕过滤无效

### ISSUE THREAD

**Issue by yuanhaoliang** [typcn/bilibili-mac-client#204]
可能是B站有BUG，经常看到“请输入弹幕DA ZE”的，我屏蔽“请输入”，重新打开直播 还是会出现这些字幕。

**Comment by typcn** [comment]
Fixed in https://github.com/typcn/bilibili-mac-client/commit/8c6925a2747e69bfeaa8d17f778941238f23a4d6
