### ISSUE TITLE
加入修改请求头的功能

### ISSUE THREAD

**Issue by zanderzhng** [typcn/bilibili-mac-client#21]
加入修改X-Forwarded-For与Client-IP请求头的功能（方便海外用户）。

**Comment by typcn** [comment]
可以，明天写

**Comment by typcn** [comment]
啊，昨天忘记了，稍等加上

**Comment by typcn** [comment]
是播放器请求视频的头，还是浏览器浏览网页的头？

**Comment by zanderzhng** [comment]
应该是有两次判断的，
第一次判断是浏览器请求网页的时候，会这样提示
![screen shot 2015-05-08 at 19 47 47](https://cloud.githubusercontent.com/assets/867749/7534993/3c3fa4de-f5bb-11e4-8de3-1816641c3a1f.png)
第二次是播放器请求视频的时候，会这样提示
![screen shot 2015-05-08 at 19 49 00](https://cloud.githubusercontent.com/assets/867749/7535002/4f4b9a24-f5bb-11e4-811e-2c110c1199c5.png)

**Comment by typcn** [comment]
直接修改请求头，不加代理可以欺骗吗？

**Comment by zanderzhng** [comment]
是的，Unblock-Youku（一个Chrome扩展）的Lite模式就是这样做的，对 www.bilibili.com/* 与 interface.bilibili.com/* 在onBeforeRequest阶段修改他们的请求头，加入XFF与Client-IP两条。
```javascript
function extra_header_modifier(details) {
    details.requestHeaders.push({
        name: 'X-Forwarded-For',
        value: unblock_youku.ip_addr
    }, {
        name: 'Client-IP',
        value: unblock_youku.ip_addr
    });

    return {requestHeaders: details.requestHeaders};
}
```

**Comment by typcn** [comment]
已经加上了，等我下午再加几个功能推送更新

**Comment by typcn** [comment]
已更新

**Comment by zanderzhng** [comment]
实测可用，感谢。
