### ISSUE TITLE
ASS 渲染出错

### ISSUE THREAD

**Issue by nuomi1** [typcn/bilibili-mac-client#212]
[归档.zip](https://github.com/typcn/bilibili-mac-client/files/117000/default.zip)
MPV 和 VLC 截图在压缩包里，出问题的字幕也在里面。

**Comment by typcn** [comment]
你字幕中 V4+ Styles 中 Encoding 为 1，但是 UTF-8 编码的 Encoding 应该是 0，请设置为 0 然后保存为 UTF-8 ( Without BOM )

**Comment by nuomi1** [comment]
@typcn 但是为什么 Default 可以正确渲染？

**Comment by typcn** [comment]
em.. 也许是字体问题吧

**Comment by nuomi1** [comment]
@typcn 已确认，的确是字体问题。
