### ISSUE TITLE
打开Bilibili出现unblock youku失效画面

### ISSUE THREAD

**Issue by Payuing** [typcn/bilibili-mac-client#214]
我查过github上的讨论串，其他人用别的浏览器也有同样的问题。
但本人的mac只有bilibili这一客户端出现了这个问题
我想尝试清理cache，但是没有相应的选项，请问有没有人也碰到了类似问题？

**Comment by typcn** [comment]
清空了相关 PAC 吗？否则可能是缓存，尝试添加 ?2
 我会考虑添加一个刷新缓存的按钮

**Comment by Payuing** [comment]
谢谢及时的回复。
我重置了下DNS就搞定了
