### ISSUE TITLE
百度盘无法播放 如图 看不到播放按钮

### ISSUE THREAD

**Issue by lifangzheng** [typcn/bilibili-mac-client#215]
![2016-02-11 12 03 29](https://cloud.githubusercontent.com/assets/12532311/12952871/0b93770c-d053-11e5-973f-bf369f43340f.png)

**Comment by lifangzheng** [comment]
![2016-02-11 12 05 56](https://cloud.githubusercontent.com/assets/12532311/12952911/428067e8-d053-11e5-8963-b6952277d3fd.png)

**Comment by typcn** [comment]
插件安装了么？尝试删下缓存？

**Comment by lifangzheng** [comment]
天啊你回复好快 刚想说重启OK了 正在找怎么删帖呢
