### ISSUE TITLE
无法自动播放视频

### ISSUE THREAD

**Issue by BigPa** [typcn/bilibili-mac-client#216]
进入播放器后，默认为暂停状态。（可以正常缓冲）
怎样可以自动播放？
（并没有修改mpv自定义配置）
`Version 2.28 (Build 1784)`

**Comment by typcn** [comment]
我这里测试没有问题啊，你是不是在 mpv 的自定义配置里面改了什么？

**Comment by BigPa** [comment]
以下是除默认外修改的设置（并没有修改mpv配置）
![screen shot 2016-02-11 at 04 15 04](https://cloud.githubusercontent.com/assets/9963287/12960551/c961ac0e-d076-11e5-89c5-0eab53dfe584.png)

**Comment by typcn** [comment]
是不是什么快捷键卡住了，尝试重启一下？

暂停只会在：1.按到快捷键 2.点击暂停键／iTunes 媒体键的暂停 3. 参数加了 pause 的情况下触发

**Comment by BigPa** [comment]
Very interesting.
重启后，第一次播放，问题消失，之后所有的播放，问题出现。

**Comment by typcn** [comment]
WTF........ 
自定义配置文件里面加一行 pause = no 试试

**Comment by BigPa** [comment]
mpv 自定义配置中添加 pause = no 无效

**Comment by typcn** [comment]
这应该是快捷键卡住了吧。。键盘什么的有异常么。。（当然也可能是软件卡住了，例如 QQ 截图经常会卡住 Cmd 键），想一想有没有什么软件快捷键与 P 和 空格 有关。

还有就是 Apple Remote 的问题，如果有 Apple Remote 设备也可能会被暂停

**Comment by typcn** [comment]
试试新版？

**Comment by BigPa** [comment]
@typcn 新版已解决该问题
