### ISSUE TITLE
播放器界面闪现

### ISSUE THREAD

**Issue by nuomi1** [typcn/bilibili-mac-client#218]
选择两个文件使用 `bilibili.app` 打开。
如果第一个是 `.ass`，第二个是 `.mp4`，播放器界面闪现。
如果第一个是 `.mp4`，第二个是 `.ass`，可以正常部分。

PS：希望增加变速功能。

**Comment by typcn** [comment]
em.. 确实本地文件检测方式有点问题，过几天修下

变速快捷键是 [ 和 ]

**Comment by nuomi1** [comment]
可以的话，在 FAQ 里列出 mpv 的快捷键吧😄

**Comment by typcn** [comment]
新版会自动匹配同一文件夹下的弹幕和字幕
