### ISSUE TITLE
开始播放后自动隐藏bilibili browser窗口

### ISSUE THREAD

**Issue by zanderzhng** [typcn/bilibili-mac-client#22]
关闭TYPCN Media Player之后自动再开启。
做成可选设置可能更好。

**Comment by typcn** [comment]
没太明白什么意思，点了播放不自动显示窗口，手动打开播放器窗口？

**Comment by zanderzhng** [comment]
点击播放后，会有一个浏览器窗口（Bilibili Browser），一个播放器窗口（TYPCN Media Player），希望能自动隐藏掉浏览器窗口。

**Comment by typcn** [comment]
我测试了一下，默认就是隐藏的啊，如果最小化或者关闭播放器窗口，浏览器才会再次出现

**Comment by zanderzhng** [comment]
试了下，我这里点击播放之后，浏览器窗口只会被放到最后边，不是隐藏。

**Comment by zanderzhng** [comment]
按错了。
