### ISSUE TITLE
ChromiumTabs无法编译

### ISSUE THREAD

**Issue by WindProphet** [typcn/bilibili-mac-client#221]
在ChromiumTabs工程的CTBrowser.m中

`CTBrowser *browser = [isa browser];`出现如下错误

Direct access to Objective-C's isa is deprecated in favor of object_getClass()

是否因为Xcode版本问题而造成无法编译，改如何解决

**Comment by typcn** [comment]
代码里并没有直接访问 isa ，请确认你是从 https://github.com/typcn/chromium-tabs 这里下载的。

原版的已经很多年没有更新了

**Comment by WindProphet** [comment]
我已经发现了，在从 https://github.com/typcn/chromium-tabs 下载后可以完成编译
