### ISSUE TITLE
支持自定义 mpv 快捷键

### ISSUE THREAD

**Issue by rainux** [typcn/bilibili-mac-client#224]
现在的情况是只能配置 mpv 核心选项，无法提供自定义 input.conf。

应该允许用户提供 input.conf 格式的快捷键定义，或者尝试直接从 `~/.config/mpv/input.conf` 读取现有的配置。

**Comment by typcn** [comment]
最近锅有点多，过几天加。。

**Comment by typcn** [comment]
新版可以了，所有配置都可以自定义，包括 lua 脚本
