### ISSUE TITLE
浏览器 session 支持

### ISSUE THREAD

**Issue by rainux** [typcn/bilibili-mac-client#225]
应该可以在退出时保存内置浏览器打开的所有 tabs 为 session，再次启动时直接从保存的 session 恢复打开所有的 tabs，方便追番。

**Comment by typcn** [comment]
Added in https://github.com/typcn/bilibili-mac-client/commit/2a8e1d7623e422afcc190e620dc7c4dff207ce21

**Comment by rainux** [comment]
👍👍👍
