### ISSUE TITLE
打开两个播放窗口时，关闭其中的一个另一个会失去响应。

### ISSUE THREAD

**Issue by Jackeriss** [typcn/bilibili-mac-client#229]
第一个是douyutv的直播，通过自带浏览器打开，第二个是bilibili的视频，通过chrome插件打开。

**Comment by typcn** [comment]
我当时写这个的时候还是初学 oc。。。 当时 mpv 开两个 view 会崩，所以为了省事，传视频信息用的是全局变量，我有时间改改吧，弄个多播放器管理的

**Comment by typcn** [comment]
准备重构这一块

PlayerManager(创建，查找，删除播放器） -> Player -> PlayerView

**Comment by typcn** [comment]
Fixed in 2.33
