### ISSUE TITLE
You-get 插件无法使用

### ISSUE THREAD

**Issue by chliul** [typcn/bilibili-mac-client#230]
在2.28版本下You-get版本为3，重装APP插件均无效，显示视频解析失败，错误信息为空白。
在插件youget 路径/Users/USER/Library/Application Support/com.typcn.bilibili/Plugins/youget.bundle/Contents/MacOS下执行./youget返回为-bash: ./youget: cannot execute binary file （我有该文件的执行权限）

**Comment by typcn** [comment]
尝试在设置中加 --debug 参数？

**Comment by chliul** [comment]
已经尝试添加了，依然错误信息为空白

**Comment by typcn** [comment]
youget.bundle 里面还有一个 you-get.bundle ，里面存的是 python 的封装，执行那个试试？

**Comment by chliul** [comment]
在you-get.bundle下找到的you-get执行./you-get --debug www.acfun.tv/v/ac2567330返回了Illegal instruction: 4

**Comment by typcn** [comment]
你自己装一个 you-get 然后设置 you-get 可执行路径到 /usr/local/bin/you-get 试试？

**Comment by cnbeining** [comment]
Please use the LATEST version of you-get. Also notice for not you-get can only provide quite limited support to Acfun.

**Comment by typcn** [comment]
You-Get updated to https://github.com/soimort/you-get/commit/73eb64431a73033f1cd348139e23452e6ba120b9
