### ISSUE TITLE
关于全屏后屏幕切换的问题的问题

### ISSUE THREAD

**Issue by houjunxiong** [typcn/bilibili-mac-client#232]
您好，请问一下2.33版本APP全屏后，在切换至另一虚拟屏幕再切换回去总是会出现跳回主屏的问题该怎么解决，谢谢！

**Comment by maemual** [comment]
+1 问题

**Comment by typcn** [comment]
这个。。。。

**Comment by typcn** [comment]
应该是 becomeKeyWindow 的时候，程序把 playerControlWindow 给 show 出来了，系统认为程序打开了一个新的窗口，所以切回去了。。

**Comment by typcn** [comment]
更新试试？

**Comment by houjunxiong** [comment]
更新解决了~~辛苦~~
