### ISSUE TITLE
播放器控件的位置会挡字幕

### ISSUE THREAD

**Issue by oscar-c** [typcn/bilibili-mac-client#233]
![](http://d.pr/i/6gjU+)

主要是挡字幕，而且点击画面不会消失，这样全屏的时候看进度的话就有点不方便，每次看新的视频都要手动把控件稍微往边上挪一点，每次都要调其实还是挺不方便的。

希望能把控件上移动一点，或者记住上次控件的位置。

**Comment by typcn** [comment]
现在默认位置上调了 60px
