### ISSUE TITLE
编译通过,运行就直接crash了...

### ISSUE THREAD

**Issue by w1ng** [typcn/bilibili-mac-client#235]
Log如下:
**dyld: Library not loaded: @executable_path/lib/libx264.146.dylib
  Referenced from: /Users/Wubing/Library/Developer/Xcode/DerivedData/VideoPolymer-cqretyhyzyvvapebhtyimnojqopo/Build/Products/Debug/Bilibili.app/Contents/MacOS/lib/libswscale.4.dylib
  Reason: image not found**

Build时有如下警告,跟crash时的lib一样:
`ld: warning: directory not found for option '-F/Users/wingzzZ/Documents/Github/bilibili-mac-client/Build/Products/Debug'
ld: warning: ignoring file /Users/wingzzZ/Documents/Github/bilibili-mac-client/bilibili/libs/libharfbuzz.0.dylib, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): /Users/wingzzZ/Documents/Github/bilibili-mac-client/bilibili/libs/libharfbuzz.0.dylib
ld: warning: ignoring file /Users/wingzzZ/Documents/Github/bilibili-mac-client/bilibili/libs/libglib-2.0.0.dylib, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): /Users/wingzzZ/Documents/Github/bilibili-mac-client/bilibili/libs/libglib-2.0.0.dylib
ld: warning: ignoring file /Users/wingzzZ/Documents/Github/bilibili-mac-client/bilibili/libs/libx264.148.dylib, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): /Users/wingzzZ/Documents/Github/bilibili-mac-client/bilibili/libs/libx264.148.dylib
ld: warning: ignoring file /Users/wingzzZ/Documents/Github/bilibili-mac-client/bilibili/libs/libintl.8.dylib, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): /Users/wingzzZ/Documents/Github/bilibili-mac-client/bilibili/libs/libintl.8.dylib
ld: warning: ignoring file /Users/wingzzZ/Documents/Github/bilibili-mac-client/bilibili/libs/libopus.0.dylib, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): /Users/wingzzZ/Documents/Github/bilibili-mac-client/bilibili/libs/libopus.0.dylib`

编译前根据HOW_TO_BUILD里面的lib地址,下载下来替换掉了bilibili/libs里面的文件,没替换的时候编译会报错, 不过我看libs下面本来有34个个文件,下载下来的1.tar.gz里面只有28个文件,是不是libs压缩包还是旧的?

**Comment by typcn** [comment]
是的 libs 还没更新你可以从 github 上下载新的，我明天更新下

**Comment by typcn** [comment]
已更新
