### ISSUE TITLE
弹幕发送的问题

### ISSUE THREAD

**Issue by derbalkon** [typcn/bilibili-mac-client#237]
刚打开应用的时候发送弹幕是可以成功的，过一段时间之后再尝试发送弹幕，虽然显示发送成功，但是弹幕池里并不会出现

**Comment by typcn** [comment]
b站弹幕有缓存，等半小时再来看

**Comment by derbalkon** [comment]
但是B站的直播也会出现这种情况，按理说直播弹幕应该是实时的不是吗……

**Comment by typcn** [comment]
直播弹幕目前不会处理粘包，在弹幕量太大的时候会自动丢掉一些

**Comment by typcn** [comment]
可以尝试在网页上观看发送成功与否

**Comment by derbalkon** [comment]
get，以及还要反馈一个问题，2.36 (2807)版本看直播关掉窗口之后经常意外退出，系统是10.11.3

**Comment by typcn** [comment]
Fixed in 2.27
