### ISSUE TITLE
希望能加入鼠标不动时自动隐藏的功能

### ISSUE THREAD

**Issue by lzfxxx** [typcn/bilibili-mac-client#24]
全屏后有个鼠标挡着画面蛮不舒服的，放到屏幕边缘也不能隐藏

**Comment by typcn** [comment]
播放开始之后是 libmpv 捕获了鼠标，我的程序收不到鼠标移动的信号，只能全屏之后全部隐藏或者快捷键隐藏显示

**Comment by lzfxxx** [comment]
我只知道 Safari 可以 esc 隐藏鼠标，你的程序中用什么快捷键可以隐藏呢

**Comment by typcn** [comment]
还没做，下午加进去，现在在外面

**Comment by lzfxxx** [comment]
好的，谢谢你的程序，刚加入的 ip 伪装对海外的也是很有用呢！
