### ISSUE TITLE
观看直播时焦点被强制切换

### ISSUE THREAD

**Issue by BigPa** [typcn/bilibili-mac-client#241]
在全屏状态启动视频播放（直播），会出现视频窗口和“实时弹幕”窗口。
当视频窗口全屏时，切换到视频窗口后一段时间，焦点就会切换到“实时弹幕”窗口。
切换回视频窗口后，又会切回“实时弹幕”...

还能不能愉快地看直播了（掀桌）

**Comment by typcn** [comment]
这个。。。。看直播我还没试过全屏。。没测出来
你把那个窗口最小化了试试？

**Comment by BigPa** [comment]
@typcn 
复现步骤：
1. 启动客户端，将浏览器全屏
2. 打开任意一个直播视频

当“实时弹幕”最小化后，焦点将切换到浏览器...

**Comment by typcn** [comment]
我这里测试全屏的时候实时弹幕窗口不会出现在播放器上，而是直接隐藏状态啊。。

**Comment by BigPa** [comment]
@typcn 

今天在看视频时焦点也会被强制切换（到浏览器）。
而在浏览器非全屏状态下，打开视频时，浏览器会自动隐藏（可能和这个有关）
发生强制切换时，浏览器处于全屏状态。
（此时应该是应用尝试隐藏浏览器窗口，而全屏状态时无法隐藏，就出现了播放时焦点强制切换的问题）

Version: 
```shell
Executable=/Applications/Bilibili.app/Contents/MacOS/Bilibili
Identifier=com.typcn.Bilibili
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=9074 flags=0x0(none) hashes=276+5 location=embedded
Signature size=8909
Timestamp=Apr 10, 2016, 21:35:20
Info.plist entries=32
TeamIdentifier=Y256486DRL
Sealed Resources version=2 rules=12 files=181
Internal requirements count=1 size=212
```

**Comment by typcn** [comment]
em... 浏览器全屏的情况确实是这样，感觉有点蛋疼

**Comment by typcn** [comment]
Fixed in https://github.com/typcn/bilibili-mac-client/commit/ce2e82cab16668c43c4a11dffb607070f1a35072
