### ISSUE TITLE
[Important] 请问是否有人在第三方网站/网盘下载了本软件

### ISSUE THREAD

**Issue by typcn** [typcn/bilibili-mac-client#242]
![image](https://cloud.githubusercontent.com/assets/8022103/13898520/fb84f1a4-ee0e-11e5-8878-391e9c7135c6.png)

崩溃报告收集的系统显示无符号的 Crash Report 远远高于我编译的官方版本崩溃数量。

造成这种情况只有两个可能：
1. 有人下载了源代码自己编译了一份（如果只是开发者自己编译应该不会造成这么多数量的 Crash Report）
2. 有人下载源代码自己编译，或者修改了二进制文件进行二次分发。

我之前做别的软件，经常被某些人拿来重新打包，改 logo 改名字或者插广告代码，或者拿来卖之类的。
所以我比较担心这个，要是广告代码/拿来卖还好说，插点恶意代码就不好了。

如果谁自己做了一个分支，请告诉我一下
如果谁发现了第三方下载地址（最终没有跳转到我的网盘或者 GitHub），请第一时间进行反馈

大家也可以通过以下命令验证一下数字签名：
```
codesign -dv /Applications/Bilibili.app
```

最新版（2.37）运行的返回结果应该是
```
Executable=/Applications/Bilibili.app/Contents/MacOS/Bilibili
Identifier=com.typcn.Bilibili
Format=bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=5682 flags=0x0(none) hashes=275+5 location=embedded
Signature size=8556
Timestamp=2016 3 16, 21:32:18
Info.plist entries=32
TeamIdentifier=Y256486DRL
Sealed Resources version=2 rules=12 files=181
Internal requirements count=1 size=212
```
如果任何人的输出不一样，也请告诉我。

**Comment by JokerQyou** [comment]
我觉得你应该把这个 issue 的链接挂到项目 readme 和网站首页上去……不然没多少人看得到

**Comment by xjbeta** [comment]
吓得我赶紧打个包挂上深水宝   手动滑稽🌚

**Comment by binai** [comment]
应该加入readme +1

**Comment by guoyida** [comment]
应该加个验证，验证不是你自己的版本无法脸上你的服务器更新模块啥的

**Comment by typcn** [comment]
下次加上签名验证吧，如果签名有问题给服务器发软件的 SHA1 值，如果存在大量相同的就得想办法了

**Comment by typcn** [comment]
下次加上签名验证吧，如果签名有问题给服务器发软件的 SHA1 值，如果存在大量相同的就得想办法了

**Comment by typcn** [comment]
找到了原因。。。。
如果第三方库发生 Crash ，它会尝试寻找额外的 dYSM 找不到就找我要。。。

暂时可以放心了
