### ISSUE TITLE
全屏暂停恢复时失去焦点

### ISSUE THREAD

**Issue by htc550605125** [typcn/bilibili-mac-client#243]
复现步骤：

1. 播放，全屏
2. 空格暂停
3. 切换到其它屏幕
4. 切换回播放屏幕，空格恢复
5. 焦点强制转换到了其它屏幕，貌似是 bilibili-mac-client 本体

**Comment by typcn** [comment]
orderFront 好像非得转移到目标屏幕...这点很蛋疼...

**Comment by typcn** [comment]
重现失败啊。。

**Comment by typcn** [comment]
Fixed in https://github.com/typcn/bilibili-mac-client/commit/ce2e82cab16668c43c4a11dffb607070f1a35072
