### ISSUE TITLE
窗口大小与位置

### ISSUE THREAD

**Issue by Ikaroshu** [typcn/bilibili-mac-client#245]
有个奇怪的小问题，播放器的窗口每次打开都会变高一点点，本来被调整成16：9的窗口随着播放次数的增多会越变越方。。
另外如果在全屏下关掉视频，下次窗口出现的位置就不会是原来的位置了，而是重新摆在左下。。

我试图在mpv的conf里添加如下的语句，但是似乎并没有变化：
--geometry = 50%:50%
--autofit = 60%
甚至试图想默认全屏打开：
--fullscreen
也并没有效果。。

**Comment by typcn** [comment]
mpv 的配置文件对于内嵌窗口不会影响的

这个位置是保存时候取值的一个小问题。。

**Comment by river1** [comment]
原来是这个限制的，可以增加一个不使用内嵌窗口的模式吗，现在的内嵌窗口下我主要遇到这两个问题：
1. 不能默认全屏，全屏要开新的空间
2. 全屏下显示播放控件会非常卡，而mpv自己的播放控件是不会卡的（用了5年的老mbp，请原谅）

**Comment by typcn** [comment]
独立启动 mpv 进程会有一些特性不能用，以及没办法把有的设置项传过去，倒也不是不能。。

暂时没这么多精力做这个。。 patch welcome
