### ISSUE TITLE
看 B 站某些视频时会自动跳过几秒钟

### ISSUE THREAD

**Issue by sensssz** [typcn/bilibili-mac-client#248]
在看某些视频的时候，有时候会忽然自动跳过几秒钟，而且好像是固定视频固定位置会出现。比如[这个视频](http://www.bilibili.com/video/av4180641/)，在播放到大概 05:58 左右的时候，会跳一下。在其他某些视频里也有同样的问题，不过我不太记得了。

**Comment by typcn** [comment]
Same with https://github.com/typcn/bilibili-mac-client/issues/234#issuecomment-195166893

**Comment by typcn** [comment]
Click "Check for update" to get new version
