### ISSUE TITLE
mpv的配置似乎不生效？进度条位置容易挡字幕- -

### ISSUE THREAD

**Issue by spicery-** [typcn/bilibili-mac-client#252]
还是喜欢mpv自己配样式 bottombar什么的就好了 
最近有间断性画面卡住只有音频 进度条往前滚得时候会到后面去（我用的鼠标滚轮控制）

**Comment by typcn** [comment]
mpv 窗口相关配置是无效的。

请问在画面卡住时执行了什么操作？是否开启了直播窗口？

关于滚动的方向，可以到设置中选择反转

**Comment by spicery-** [comment]
卡住的时候什么都没动    没看过直播。   比如这个视频av4355580   4分50多秒的时候就会卡住 只有声音 弹幕也不滚动

**Comment by spicery-** [comment]
卡住之后大概6-7秒又好了

**Comment by typcn** [comment]
这个属于正在缓冲.....比如视频遇到分段需要缓冲

可以在设置中调大缓存，一次缓冲完全片

**Comment by spicery-** [comment]
我调到了500000kb   还是卡住了  我明天再看看有没有卡住的情况 再来汇报下。

**Comment by spicery-** [comment]
还是有画面卡住的问题 好像是大约5分钟卡一下 会不会和上次的问题有关？

**Comment by typcn** [comment]
“卡一下”是卡一瞬间又继续开始播放，还是明显的播不动？

**Comment by spicery-** [comment]
一次是瞬间  两次是卡住四五秒左右

**Comment by typcn** [comment]
卡住之后恢复的时候网络流量是否增加了？

**Comment by spicery-** [comment]
额 没注意 我再看看

**Comment by spicery-** [comment]
问题是我再次打开同一个视频 卡住的时间点是不变的   当然第二次是快进的

**Comment by spicery-** [comment]
流量没有增加

**Comment by typcn** [comment]
有没有更详细的信息？比如播放时产生的 Log（Console.app），是否开启了硬解，下载到本地之后播放是否可以重现？

**Comment by spicery-** [comment]
没有开启硬解  下载到本地是4段flv。 卡住的地方正好是断点，     合并播放之后问题还是有。卡住的时候蹦出一大段 不知道是不是
![image](https://cloud.githubusercontent.com/assets/10226889/14601895/50973ca2-0597-11e6-94e1-313b74bc3854.png)
至于有时候会出现这个东西 关不掉 需要点一下dock栏的图标重新出现一个正常的首页
![image](https://cloud.githubusercontent.com/assets/10226889/14601918/821314b8-0597-11e6-82ec-9340d39b19c4.png)

**Comment by typcn** [comment]
这个 Log 明显是开启了硬解吧。。。。因为 VTB 同时只能创建一个，然后第一个 VTB 销毁之后，第二个才创建，然后又 probe 一遍，发现不能又 fallback 到软解，这个造成了很大的延迟

**Comment by typcn** [comment]
你检查你自定义的 MPV 配置文件里面是不是有 hwdec 

如果要开启硬解请通过软件的设置界面，而不是使用配置文件

**Comment by spicery-** [comment]
原来是这样- -  问题解决了 谢谢

**Comment by typcn** [comment]
现在默认位置上调了 60px
