### ISSUE TITLE
斗鱼无法解析

### ISSUE THREAD

**Issue by lzfxxx** [typcn/bilibili-mac-client#253]
显示 

Video Resolve Error
视频解析失败， 返回信息：

**Comment by typcn** [comment]
斗鱼换解析比较频繁。。可以自己通过 pip 装一个 you-get，在插件设置中，修改 you-get 路径为你安装的 you-get 来使用最新版本

**Comment by lzfxxx** [comment]
<img width="409" alt="screen shot 2016-04-13 at 16 05 08" src="https://cloud.githubusercontent.com/assets/12368329/14498252/9cfc1f54-0191-11e6-99c4-df2d8e7b15ce.png">
<img width="564" alt="screen shot 2016-04-13 at 16 05 35" src="https://cloud.githubusercontent.com/assets/12368329/14498256/a03a89d0-0191-11e6-95b2-b3a88ef92631.png">
我路径是不是写错了

**Comment by typcn** [comment]
要可执行文件，控制台输入 which you-get 来获得路径

**Comment by lzfxxx** [comment]
这样，现在路径看来是对了，就又回到一开始的样子了。。

<img width="247" alt="screen shot 2016-04-13 at 16 21 02" src="https://cloud.githubusercontent.com/assets/12368329/14498839/f171d392-0193-11e6-8c6a-f1acf3a9d7f0.png">

**Comment by typcn** [comment]
你在命令行下执行 you-get -u 播放地址，看一下是否有返回

**Comment by lzfxxx** [comment]
没有返回

**Comment by typcn** [comment]
尝试给 https://github.com/soimort/you-get 反馈

**Comment by lzfxxx** [comment]
好的，看来是 you-get 的问题，多谢

**Comment by j20120307** [comment]
我是命令行下有返回 但是界面里面连报错信息都没有 一片灰

**Comment by typcn** [comment]
尝试在 you-get  插件中，设置可执行文件路径到你安装的 you-get

**Comment by j20120307** [comment]
就是which 之后得到的路径

**Comment by typcn** [comment]
日志有输出么？

**Comment by j20120307** [comment]
![image](https://cloud.githubusercontent.com/assets/3880859/15272444/d1d1759e-1a46-11e6-8af4-3484bd11cb16.png)

**Comment by typcn** [comment]
我说软件是否在 you-get 里输出了日志

**Comment by j20120307** [comment]
好像可以了 点了右上角resolving video url就可以看了 （刚用这个不太熟练不好意思
