### ISSUE TITLE
Aria2c衝突問題

### ISSUE THREAD

**Issue by prenfic** [typcn/bilibili-mac-client#254]
首先，我電腦中已經配置了一個，而且加了token，

Aria2: 1.21.0

JSON-RPC Path如下：

> http://token:secret@127.0.0.1:6800/jsonrpc

然後，我最近開始用起了bilibili.app
才發現其中也內置了一個aria2c
不過不確定版本

不過我發現了一個問題是
在其他的瀏覽器
都可以順利地通過token連接aria2c

但是在bilibili.app中
我卻發現Json-rpc path
會自動更改為：

> http://localhost:23336/jsonrpc

而且無法調用系統內的配置文件
地址為

> $Home/.aria2

input-file跟save-session目測跟bilibili.app的應該一樣

> input-file=/Users/Shared/aria2.session
> save-session=/Users/Shared/aria2.session

---

我嘗試了手動更改Bilibili.app內的Json-rpc path
但依然顯示錯誤信息：

> Error: Unauthorized
> Error: Internal Server Error

我想請問有辦法調和嗎

---

目前的個人猜測是
bilibili.app內置的aria2c
版本較為低
不支持token

不過由於查不到內置aria2c的版本號
所以只停留在猜測階段

**Comment by typcn** [comment]
https://github.com/typcn/bilibili-mac-client/search?utf8=%E2%9C%93&q=23336

内置的是 Hardcode 的。。。

那个网页面板上的设置只是管理界面用的。。。

暂时不支持更改端口，可以考虑加入

**Comment by prenfic** [comment]
@typcn 所以這樣就是會開啟兩組daemon的意思嗎?
可是我只看到了我設定的--rpc-listen-all=true --rpc-listen-port=6800的daemon，
實際掃描結果，也只有6800的端口在用著

還是說，
我直接修改
bilibili/Downloader/DownloadWrapper.mm
跟
bilibili/startaria.sh

變成跟系統內的一致
會比較快???

**Comment by typcn** [comment]
如果软件内置的 deamon 没有正确启动的话，可能是文件有冲突（例如 input-session）

**Comment by hq3595** [comment]
你们是怎么获得APPKey 和 Secret 的 ？

**Comment by xjbeta** [comment]
建议改下Aria2c(exec文件) 的名字  (.sh 里对应的也改掉就行)    不然任务管理器里分不清。

**Comment by YangJianchong** [comment]
同样的问题..下了源文件然后按上面的方法试了试还是不行呢。

**Comment by typcn** [comment]
Fixed in https://github.com/typcn/bilibili-mac-client/commit/9efd7e32310876048f50c9de1101438388c0f95a
