### ISSUE TITLE
无法读取Cookie

### ISSUE THREAD

**Issue by shiniv** [typcn/bilibili-mac-client#256]
最近发现登录失效了，再次登录时出现 

> 验证码错误！ 无法读取Cookie 请检查您的浏览器设置 

删除了再下载一遍还是一样，有什么原因会造成这样呢？

**Comment by typcn** [comment]
设置 ---- 工具 --- 然后清空缓存和 Cookie 试一下

**Comment by shiniv** [comment]
都点了个遍都没有效果 还是出现无法读取 cookie

**Comment by shiniv** [comment]
额...多刷N次就好了...怪了

**Comment by typcn** [comment]
估计是 B 站服务器又炸了。。刚重启好了
