### ISSUE TITLE
后台播放腾讯的视频

### ISSUE THREAD

**Issue by SinCheung** [typcn/bilibili-mac-client#263]
http://117.135.168.15/vlive.qqvideo.tc.qq.com/y00201uigpo.mp4?vkey=E6C2B89DED5AE74239036BFF6E986A8AF1F0C4298BA2C1F9246621631C800AFB9349458B8E8FD03C7C2456D99661690C9A7720EB636943669C5E5F669AB5322770DB8A1DC5CF76AF5CD493135E49D51E81FCE23BB590F478&br=60&platform=2&fmt=auto&level=0&sdtfrom=v1010&locid=387157d7-c363-48c0-b202-44e795c155c3&size=427224842&ocid=224007596

![image](https://cloud.githubusercontent.com/assets/3352888/15265911/d5e0d48a-19c5-11e6-942e-e8ff94690961.png)

**Comment by SinCheung** [comment]
![image](https://cloud.githubusercontent.com/assets/3352888/15265960/3bfe0fde-19c7-11e6-8cc3-23a84dee95d8.png)

**Comment by typcn** [comment]
请提供日志

**Comment by SinCheung** [comment]
日志找不到相关的信息，很大几率在打开某个bilibili的页面，会自动后天播放腾讯视频，每次ip都会改变，重新加载就没有了，使用chrome也没有，使用客户端就会时常出现，客户端又不可以检查元素。目前使用的是移动的宽带。

**Comment by typcn** [comment]
wtf...... 可否将 Localhost 上的通讯也抓包一下？

因为在本地主机上的任何程序，都可以通过 localhost:2330 端口来播放视频

**Comment by SinCheung** [comment]
![image](https://cloud.githubusercontent.com/assets/3352888/15266007/c9ac6a3c-19c8-11e6-8ae2-ac70ccd2fa9c.png)
目前，我只开了网易云，chrome，bilibili客户端，这条request是从Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko)发出的

**Comment by typcn** [comment]
这就很奇葩了，客户端播放器的 UA 是写死的 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17

**Comment by typcn** [comment]
这个 UA 是客户端 Webview 的 UA，如果出现，表示 WebVIew 中有 html5 video 标签正在播放

**Comment by typcn** [comment]
可能是移动插的劫持代码，里面放了个腾讯视频？

**Comment by SinCheung** [comment]
表示怀疑了，昨天使用的上海联通宽带也出现了。

**Comment by typcn** [comment]
现在可以重现么？是否能抓到 HTML 和 JS 代码？

或者你可以将内容发我一份， typcncom@gmail.com ( key id: 0x39534AF6 )

客户端内置的 wkwebview 确实是没有办法 inspect 的，如果是缓存的 JS 导致，可以尝试在设置 - 工具 - 清空 WebKit 缓存

**Comment by SinCheung** [comment]
cdn:cdn2.eqoe.cn
$("head").append($('<link rel="stylesheet" type="text/css" />').attr("href", "http://cdn2.eqoe.cn/files/bilibili/all.css"));

var latest = false;

var request = new XMLHttpRequest();
request.open('GET', 'http://localhost:23330/ver', true);

request.onload = function() {
    var data = JSON.parse(request.responseText);
    if(data.version == 2.39 || data.version == 2.40 || data.version == 2.41){
        latest = true;
        if(!localStorage['hide_faq']){
          $("body").append('<div id="bm_tip">�����伴��棰�锛���瑰�昏�����(1021)</div>');
        }
    }else if(!window.bilimacVersion || window.bilimacVersion < 235){
        $("body").append('<div id="bm_tip" style="font-size:150%;">��变��B绔���茬����炬�存�帮��璇ョ�����宸插け���锛���瑰�昏�������存��<br>锛�涔����妫���ユ�存��404������棰�宸蹭慨澶�锛�</div>');
    }else{
        $("body").append('<div id="bm_tip" style="font-size:130%;">��ㄧ��杞�浠舵����扮�����锛���瑰�昏�������存��</div>');
    }
    fixUpdate();
    bindAction();
};

request.onerror = function() {
    if(!window.bilimacVersion || window.bilimacVersion < 235){
        $("body").append('<div id="bm_tip" style="font-size:130%;">��变��B绔���茬����炬�存�帮��璇ョ�����宸插け���锛���瑰�昏�������存��</div>');
    }else if(window.bilimacVersion < 235){
        $("body").append('<div id="bm_tip" style="font-size:130%;">��ㄧ��杞�浠舵����扮�����锛���瑰�昏�������存��</div>');
    }else{
        if(!localStorage['hide_faq']){
          $("body").append('<div id="bm_tip">�����伴��棰�锛���瑰�昏�����(1021)</div>');
        }
        latest = true;
    }
    bindAction();
};

request.send();

function bindAction(){
  if(latest){
      $("#bm_tip").on("click", function(i) {
          window.location.href = "http://vp-hub.eqoe.cn/faq.html";
      });
  }else{
      $("#bm_tip").on("click", function(i) {
          var data = {action: "checkforUpdate",data:"none"};
          try{
              window.webkit.messageHandlers.BLClient.postMessage(data);
          }catch(e){
            try{
                window.external.checkforUpdates();
            }catch(e){
                $.post("http://localhost:23330/rpc",data);
            }
          }
      });
  }
}

if(!localStorage.bilimac_player_type){
  function hidefaq(){
    localStorage['hide_faq'] = 'true';window.location.reload();
  }
  function showfaq(){
    delete localStorage['hide_faq'];window.location.reload();
  }

  if(!localStorage['hide_faq']){
    $('.z_top_nav ul').append('<li class="faq"><a class="i-link" href="javascript:hidefaq()">���������娴�</a></li>');
  }else{
    $('.z_top_nav ul').append('<li class="faq"><a class="i-link" href="javascript:showfaq()">��剧ず���娴�</a></li>');
  }
}

function fixUpdate(){
  if(!$('.z_top_nav ul .update')[0]){
      $('.z_top_nav ul').append('<li class="update"><a class="i-link" href="javascript:window.sendToView({action: \'checkforUpdate\',data:\'none\'});">妫���ユ�存��</a></li>');
      if(!$('.i_face').attr('src')){
          $('.login').css('width',200).children('span').html('��瑰�荤�诲��瀹㈡�风��浠ヤ究������寮瑰��');
      }
  }
}

if(window.location.href == 'http://www.bilibili.com/html/bnj2016.html'){
  $('.bnj-video-part-list').click(function(e){  window.TYPCN_PLAYER_CID = e.target.getAttribute('cid') + '|' + window.location.href + '|' + document.title });
}

$(".index-online").height('100');

$.ajax({ 
  url: 'https://storage.typcn.com/_api/bilibili', 
  dataType: 'json', 
  success: function(i){
    if(latest){
      $(".index-online").append('<br><span class="mac-online">Mac 瀹㈡�风����ㄧ嚎:' + i.online + '</span><i class="s-line"></i><span class="month-user">30澶╃�ㄦ�烽��:' + i.monthUser 
        + '</span><br><span class="mac-tip">��瑰�绘��涓���圭����板缓���绛炬��������浠ユ��瑙����浠朵腑蹇�</span></a>');
    }else{
      $(".index-online").append('<br><span class="web-online">Mac 瀹㈡�风����ㄧ嚎:' + i.online + '</span><i class="s-line"></i><span class="month-user">30澶╃�ㄦ�烽��:' + i.monthUser 
        + '</span><br><span class="mac-tip">��瑰�绘��涓���圭����板缓���绛炬��������浠ユ��瑙����浠朵腑蹇�</span></a>');
    }
    
  }, 
  timeout: 3000,
  error: function(jqXHR, status, errorThrown){
    $(".index-online").append('<br>璇诲����ㄧ嚎浜烘�颁俊���澶辫触锛����璇�浠ｇ��: '+status+'<br>');
  } 
}); 

![image](https://cloud.githubusercontent.com/assets/3352888/15268659/c23d93ac-1a18-11e6-9024-938bf1ada072.png)


http://120.76.101.72:40001:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko
------------------------------------------------------------------------------------------------------------------------
<a href="http://120.76.101.72:10000/track/api/v0/show/1.gif?pid=f0e0b534-8bdd-44ca-a27a-7df4c281ce65&amp;am=00000564&amp;loc=00000030&amp;u=http%3A%2F%2F114.215.114.158%2Ft_201604271905_1.HTML&amp;uid=448e09e7-4051-4605-8328-648197fa284c">Found</a>.

http://120.76.101.72:10000:
------------------------------------------------------------------------------------------------------------------------
<a href="http://114.215.114.158/t_201604271905_1.HTML">Found</a>.

/t_201604271905_1.HTML request:
------------------------------------------------------------------------------------------------------------------------
http://114.215.114.158
GET /t_201604271905_1.HTML HTTP/1.1
host：114.215.114.158
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko)
referer:http://www.bilibili.com/

reponse:
------------------------------------------------------------------------------------------------------------------------
HTTP/1.1 200 OK
Content-Length: 360
Content-Type: text/html
Last-Modified: Thu, 12 May 2016 11:23:15 GMT
Accept-Ranges: bytes
ETag: "5f7276ad40acd11:288"
Server: Microsoft-IIS/6.0
Date: Sat, 14 May 2016 12:32:54 GMT

<html>
<head>
<META HTTP-EQUIV="REFRESH" CONTENT="0; URL=http://v.qq.com/dtest/play/rpt_player.html?vid=e0020luwtuv&ptag=bl.rx.pn4.4&domain=s11&dmid=1259040629&dmwid=1259040629"> 
</head>
<body>
<div style="display:none">
<script src="http://s11.cnzz.com/stat.php?id=1258843267&web_id=1258843267" language="JavaScript"></script>
</div>
</body>
</html>

**Comment by typcn** [comment]
cdn2.eqoe.cn 是我的服务器，返回的脚本是用于显示首页上那个“在线人数”的，没有什么用处。

ip 120.76.101.72 跳转到了那个腾讯视频，这个 IP 属于北京市 长城宽带

**Comment by typcn** [comment]
oh no 我的 IP 库没有更新，现在这个 IP 属于 X 里云
![image](https://cloud.githubusercontent.com/assets/8022103/15271262/82fb775e-1a72-11e6-905d-2a103a075229.png)

Google 搜索这个 IP，可以看到跟你的抓包中差不多一样的 URL ，并且跳转目标都是那个页面

![image](https://cloud.githubusercontent.com/assets/8022103/15271264/8daca20e-1a72-11e6-9824-e571d8eb6e1c.png)

应该是属于页面上的广告被用于后台恶意播放视频，刷播放量（？）

**Comment by typcn** [comment]
通过 Google 搜索 114.215.114.158 ，可以获得：

https://www.douban.com/note/460954287/
http://zhidao.baidu.com/question/1604890086646633027.html
**https://www.v2ex.com/t/271595**

**Comment by typcn** [comment]
http://cdn.eqoe.cn/files/bilibili/widget-min.js

我在服务器注入了一些新的代码，会在网页打开的 10 内每秒检测一次 iframe 并移除，现在应该可以无视这个劫持了
