### ISSUE TITLE
你好，客户端有很突兀的广告声音，请问怎么解决

### ISSUE THREAD

**Issue by dearestu** [typcn/bilibili-mac-client#264]
比如说打开首页，过一会就会出现广告声音，都不知道哪儿来的。。。

**Comment by typcn** [comment]
搜索一下历史 issue ，已经分析过，这是运营商劫持导致的

**Comment by typcn** [comment]
https://github.com/typcn/bilibili-mac-client/issues/263

**Comment by typcn** [comment]
http://cdn.eqoe.cn/files/bilibili/widget-min.js

我在服务器注入了一些新的代码，会在网页打开的 10 内每秒检测一次 iframe 并移除，现在应该可以无视这个劫持了
