### ISSUE TITLE
如何直接下载 .ASS 文件弹幕？

### ISSUE THREAD

**Issue by ProtossProbe** [typcn/bilibili-mac-client#265]
现在下载出来的都是 .xml 文件

**Comment by typcn** [comment]
弹幕本身就是 xml 格式的
ASS 需要额外转换

如果同目录下存在 XML 文件，使用本软件播放的时候会自动加载它作为弹幕。

内置转换好的 ASS 文件可以通过日志“comment converted to xxx” 来找到。

手动转换可以使用 danmaku2ass / danmaku2ass_native 等工具实现

**Comment by ProtossProbe** [comment]
明白了，感谢回复！
