### ISSUE TITLE
The application "bilibili" can't be opened

### ISSUE THREAD

**Issue by matthew-z** [typcn/bilibili-mac-client#27]
Hi,

I just found this APP, and I think it is very useful. I downloaded the binary version from MEGA(1.6a, 9th May), but I can't open this APP on my RMBP (Early 2015, OS X 10.10.3, English Language).

I tried to download the source version, but the Xcode can't build it due to building errors.

Also, I have allowed "anywhere" apps in the security setting, but it did not help.

Any help would be appreciated.

**Comment by matthew-z** [comment]
![qq20150512-1 2x](https://cloud.githubusercontent.com/assets/5741303/7598352/9fc48194-f8f1-11e4-9bce-29d54ba6fda5.png)

**Comment by typcn** [comment]
I do not know why it is only show "can not be opened" without "because" .
You can try to compile from source code, [How to complie](https://github.com/typcn/bilibili-mac-client/blob/master/COMPLIE.md).
If you need APIKey and APISecret , I can send one via email.

**Comment by matthew-z** [comment]
Could you please send the API to my Email address: zhaohao.zeng93@gmail.com?

**Comment by typcn** [comment]
Sent

**Comment by matthew-z** [comment]
Thanks

**Comment by matthew-z** [comment]
Hi,

I still got a building error : "danmaku2ass_native/danmaku2ass.h",

any advice?

Thanks

**Comment by typcn** [comment]
git submodule update --init

**Comment by matthew-z** [comment]
Oh, my bad

Thanks

**Comment by matthew-z** [comment]
Hi,

I just built this Application in release schema, and I really like it. However, I found that my RMBP was very warm in the Fullscreen mode (and the Fan worked hard) with a 1080P displayer. Also, I found that it worked well(the fan did not work) in the Window mode though the window size was closed to the FullScreen mode.

**Comment by typcn** [comment]
WTF

**Comment by typcn** [comment]
I'll try to set the OpenGL layer full screen , instead of resize the window

**Comment by matthew-z** [comment]
Hi,

Just want to tell you that I think the latest version is awesome: Fullscreen works well and the hidden mouse is very cool.

By the way, I tried to use another mac (MBA,10.10.3) to run the binary version which was downloaded from MEGA, but it still didn't work(error message: The application "bilibili" can't be opened).

**Comment by typcn** [comment]
WTF
Did you set "Allow apps from" to anywhere ?
Maybe Apple's security policy changed and I need buy  Mac Developer Program?

**Comment by typcn** [comment]
Can you try to download it from github or baidu disk?
Files from mega are downloaded from a "data" uri, I think apple can't verify the download url.

**Comment by matthew-z** [comment]
OMG, I just tried the binary program downloaded from github and it does work. I did not try the baiduDisk since it is very slow for me.

**Comment by typcn** [comment]
I'll remove mega link from download list tomorrow

**Comment by typcn** [comment]
Thanks for contributions.
