### ISSUE TITLE
插件 API 没有弹幕接口

### ISSUE THREAD

**Issue by xplorld** [typcn/bilibili-mac-client#273]
想写个网易云音乐听歌插件，放评论当弹幕。发现只有视频 URL 接口。略简陋啊。

**Comment by typcn** [comment]
插件 api 准备改了，现在可以直接继承 VideoProvider 类和 SubProvider 类，发 pr 合并进主程序

**Comment by typcn** [comment]
See https://github.com/typcn/bilibili-mac-client/blob/master/Plug-Ins.md

现在可以使用 SubtitleProvider 来实现弹幕了
