### ISSUE TITLE
bilibili新版本没有默认视频图标

### ISSUE THREAD

**Issue by ariour** [typcn/bilibili-mac-client#274]
默认关联bilibili播放器后，mac中视频文件图标依然是其他播放器的或者是无图标，不知是不是只有我一个人的问题。

**Comment by typcn** [comment]
是的，我也发现了，那个图标必须是 icns 格式，我以为 png 就行（因为xcode里面显示正常），被坑了

**Comment by ariour** [comment]
噗。那看下次更新能不能修复下好了。另外因为人在霓虹，有时候缓冲一半卡住（显示0m）不知是本身网络原因还是什么。。或者不知道能不能加个缓冲的百分比？谢开发的大大

**Comment by typcn** [comment]
0M 就是 buffer 空了，新版可以记忆播放进度，关掉再点下播放

**Comment by typcn** [comment]
Fixed in https://github.com/typcn/bilibili-mac-client/commit/2b3d757a780b4a3e613b425bd3842b48fc70bc71
