### ISSUE TITLE
macOS 10.12 Sierra DP1

### ISSUE THREAD

**Issue by fortissimoX** [typcn/bilibili-mac-client#277]
崩了，打不开

**Comment by typcn** [comment]
Stack Trace 呢？

苹果每次系统更新从来没有不 break OpenGL 的。。。习惯了

**Comment by fortissimoX** [comment]
没crash，只是单纯的打不开

**Comment by typcn** [comment]
打开的时候没有什么错误提示吗？ “详细信息” 之类的

**Comment by fortissimoX** [comment]
什么都没有

**Comment by typcn** [comment]
双击之后什么反映都没有？。。。。提示框能截图下么？

一般是 “详细信息” “技术信息” “报告” 之类的按钮

**Comment by fortissimoX** [comment]
没有任何错误提示，不显示任何窗口

**Comment by typcn** [comment]
擦。。。。。我觉得是系统 BUG？ Console.app 里面有什么日志输出？在终端运行 /Applications/Bilibili.app/Contents/MacOS/Bilibili 呢？

我现在不太方便升级，有时间我装个虚拟机。。

**Comment by fortissimoX** [comment]
`╭─zakuro at bogon in /Users/zakuro
╰─λ /Applications/Bilibili.app/Contents/MacOS/Bilibili                                                      0 < 20:34:49
2016-06-14 20:34:58.240 Bilibili[2347:150973] *** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray
`

**Comment by typcn** [comment]
这个。。。好奇怪。。系统升级为什么会影响
没 Stack Trace 也没法确定是哪里的，请问你有装 Xcode 吗？是否方便调试一下？

**Comment by fortissimoX** [comment]
有，我试试

**Comment by fortissimoX** [comment]
真是奇怪，HEAD是可以编译运行的
<img width="974" alt="screen shot 2016-06-14 at 9 42 14 pm" src="https://cloud.githubusercontent.com/assets/12559223/16044901/dd6f01ce-3278-11e6-81c6-60ff07e96122.png">

**Comment by typcn** [comment]
这个。。。。。

**Comment by typcn** [comment]
估计是 Apple 的玄学 BUG，之前 10.11 的时候也是，测试版不行，到了正式版自动好了。。

**Comment by fortissimoX** [comment]
上次 release 和 HEAD 之间有什么比较重要的变动吗

**Comment by typcn** [comment]
https://github.com/typcn/GCDWebServer/commit/249d1e27609b4c949261d29963dc54f4dffcaea9

就改了这一丁点

**Comment by fortissimoX** [comment]
然而退回去一样也能运行。。

**Comment by typcn** [comment]
那估计就是系统的 BUG 了。。。。 没做 backward compatibility

**Comment by fortissimoX** [comment]
但是为啥我自己编译的没问题呢

**Comment by fortissimoX** [comment]
是因为编译系统的问题？

**Comment by typcn** [comment]
因为你是在新的系统上，用新的 SDK 编译的。。。

**Comment by fortissimoX** [comment]
那就先这么用着吧
iOS10的B站直播也不好使了。。
