### ISSUE TITLE
何时才能适配macOS Sierra？

### ISSUE THREAD

**Issue by JclMiku** [typcn/bilibili-mac-client#278]
何时才能适配macOS Sierra？

**Comment by typcn** [comment]
不是我适配 macOS Sierra，是代码本身就兼容 Sierra ，不需要任何修改。
但是苹果没有做任何的后向兼容，导致旧系统编译出来的程序，不能正常运行。

至于这个时间：
* 苹果把后向兼容修复
* 正式版推出

看哪个先到。。。


你可以下载源代码，自行编译运行

**Comment by typcn** [comment]
编译可以参考 https://github.com/typcn/bilibili-mac-client/blob/master/HOW_TO_BUILD.md

APPKEY 可以不填，用空字符串就可以了，编译类型是 Release 的情况就可以直接解析（Build For Profile 就可以）

**Comment by jaywongs** [comment]
编译之后提示找不到FMDB/FMDB.h

**Comment by typcn** [comment]
请参考上面的编译教程进行编译，否则可能会没有下载子项目，依赖库等。

**Comment by JeremieAstray** [comment]
就是说要手动编译才能用上么？

**Comment by typcn** [comment]
新的commit已经兼容，手动编译release即可

**Comment by typcn** [comment]
2.45 已兼容

**Comment by jaywongs** [comment]
感动哭了  今早才检查了一遍更新。真是万分感谢！

**Comment by jaywongs** [comment]
无法连接到 API 服务，请确保您正在使用 Bilibili for mac 最新版本
10.12  已更新到最新版2.45

**Comment by typcn** [comment]
请查看常见问题 http://vp-hub.eqoe.cn/faq.html

**Comment by jaywongs** [comment]
23330和23336端口都没有占用但是关闭客户端后 23336的aria2c仍然在启动中
重新开启软件显示插件信息解析失败，内容返回错误。点击视频还是显示正在解析地址

**Comment by typcn** [comment]
这可能是由于运营商劫持，无法更新插件信息导致的，请确保系统代理设置没有问题，且可以正常连接 http://vp-hub.eqoe.cn/api/manifest/com.typcn.vp.bilibili.json

**Comment by jaywongs** [comment]
{
    "type":"plugin",
    "name":"bilibili",
    "version":"13",
    "developer":{
        "id":"typcn",
        "site":"http://blog.eqoe.cn"
    },
    "domain":"*.none.nic",
    "apiver":"0.1",
    "minver":214,
    "maxver":999999,
    "sig":true,
    "download":"http://vp-hub.eqoe.cn/download/com.typcn.vp.bilibili/bb13.vpplugin"
}
这样算正常连接吗？

**Comment by typcn** [comment]
正常，如果一直读取失败，建议检查系统代理设置，尝试开启或关闭代理。

**Comment by jaywongs** [comment]
我以为是surge代理的问题 ，关闭了， 也不行，系统代理里全部都没打开，还是不行。运营商劫持的话我换个移动试试?

**Comment by jaywongs** [comment]
清空过缓存了，也试过移动的热点了，还是一样无法获取插件，应该不是运营商劫持。

**Comment by typcn** [comment]
em.. 看来说不定是苹果又乱改 API 了。。。。。。。。

你可以先下载 http://vp-hub.eqoe.cn/download/com.typcn.vp.bilibili/bb13.vpplugin
解压并覆盖到 ~/Library/Application Support/com.typcn.bilibili/

**Comment by jaywongs** [comment]
bb13.vpplugin 怎么解压啊？

**Comment by typcn** [comment]
改后缀 ZIP ，解压即可

**Comment by jaywongs** [comment]
覆盖之后好了，非常感谢您的耐心帮助。

**Comment by typcn** [comment]
测试通道已经修复，明天发正式版更新

**Comment by jaywongs** [comment]
Hello there,

I just signed the petition "Tim Cook: Apple publicly commit to work with
Nvidia on drivers for Mac OS 10.14" and wanted to see if you could help by
adding your name.

Our goal is to reach 10,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/P2jxXbtZ25

Thanks!
wang
