### ISSUE TITLE
开到全屏在线播放发热有点严重

### ISSUE THREAD

**Issue by ariour** [typcn/bilibili-mac-client#279]
风扇也是一直转。印象中在更新到这一版本之前好像是没有这个情况。不知道是为啥- -

**Comment by typcn** [comment]
播放器代码已经好多版本没有修改过一行了
请提供日志和采样以便分析

（ Activity Monitor - Bilibili - Sample )

**Comment by ariour** [comment]
[“Bilibili”的取样.txt](https://github.com/typcn/bilibili-mac-client/files/319673/Bilibili.txt)
不知道有没有反映出问题- -

**Comment by typcn** [comment]
看这个样子应该是大量的弹幕生成造成的。。。。（目前用的是 ass 字幕作为弹幕的渲染，以后可能我会撸一套带预渲染缓存的）

这个问题只在全屏时发生么？

**Comment by ariour** [comment]
测了一下确实是在全屏时发生。

**Comment by typcn** [comment]
100% 可以重现么？还是说有时重现？关闭弹幕之后呢？

**Comment by ariour** [comment]
重现是？这两天又看了下。不是完全出现这样状况，但出现几率也蛮高的- -关闭弹幕后慢慢cpu占用率就下来了。

**Comment by typcn** [comment]
这。。。。好奇怪。你先暂停视频，再全屏，在播放呢？

**Comment by ariour** [comment]
这样的话风扇倒是没转了。cpu占有率大概在近40的程度。

**Comment by typcn** [comment]
加了自动暂停，可以缓解一下。。https://github.com/typcn/bilibili-mac-client/commit/ce2e82cab16668c43c4a11dffb607070f1a35072
