### ISSUE TITLE
用bilibili.app下载的视频，在typcn midea player 播放提示“所有视频源连接失败”

### ISSUE THREAD

**Issue by ikamal** [typcn/bilibili-mac-client#280]
具体是这个视频 http://www.bilibili.com/video/av4749935/
下载后不能播放。

**Comment by typcn** [comment]
这种情况一般是由于下载的文件不完整或损坏造成的
格式肯定是支持的

**Comment by typcn** [comment]
你可以重新下载一下试试

**Comment by ikamal** [comment]
啊，这么快回复了！

我是特意下载两次之后才来这里反馈的。还退出app重新打开还是提示同样的错误。

On 2016年6月16日 周四 at 00:30 typcn

<
mailto:typcn <notifications@github.com>
> wrote:

你可以重新下载一下试试

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/typcn/bilibili-mac-client/issues/280#issuecomment-226243117
, or
https://github.com/notifications/unsubscribe/AApDx4pfGxlT-LA3_KINNWVkgAsJkmStks5qMCibgaJpZM4I2i2z
.

https://github.com/typcn/bilibili-mac-client/issues/280#issuecomment-226243117

**Comment by typcn** [comment]
打开 Console.app 看下日志？

**Comment by ikamal** [comment]
16/6/16 00:43:37.208	Bilibili[42808]	Handle open files: (
    "/Users/Yukun/Movies/Bilibili/\U3010\U4eba\U7c7b\U89c2\U5bdf\U3011160519 \U5982\U679c\U59bb\U5b50\U53d8\U88c5\U540e\U5728\U5927\U8857\U4e0a\U642d\U8baa\U4e08\U592b\Uff0c\U4e08\U592b\U4f1a...?\U3010\U4eba\U529b\U5b57\U5e55\U7ec4\U3011/7706086-1.flv",
    "/Users/Yukun/Movies/Bilibili/\U3010\U4eba\U7c7b\U89c2\U5bdf\U3011160519 \U5982\U679c\U59bb\U5b50\U53d8\U88c5\U540e\U5728\U5927\U8857\U4e0a\U642d\U8baa\U4e08\U592b\Uff0c\U4e08\U592b\U4f1a...?\U3010\U4eba\U529b\U5b57\U5e55\U7ec4\U3011/7706086-2.flv",
    "/Users/Yukun/Movies/Bilibili/\U3010\U4eba\U7c7b\U89c2\U5bdf\U3011160519 \U5982\U679c\U59bb\U5b50\U53d8\U88c5\U540e\U5728\U5927\U8857\U4e0a\U642d\U8baa\U4e08\U592b\Uff0c\U4e08\U592b\U4f1a...?\U3010\U4eba\U529b\U5b57\U5e55\U7ec4\U3011/7706086-3.flv",
    "/Users/Yukun/Movies/Bilibili/\U3010\U4eba\U7c7b\U89c2\U5bdf\U3011160519 \U5982\U679c\U59bb\U5b50\U53d8\U88c5\U540e\U5728\U5927\U8857\U4e0a\U642d\U8baa\U4e08\U592b\Uff0c\U4e08\U592b\U4f1a...?\U3010\U4eba\U529b\U5b57\U5e55\U7ec4\U3011/7706086-4.flv",
    "/Users/Yukun/Movies/Bilibili/\U3010\U4eba\U7c7b\U89c2\U5bdf\U3011160519 \U5982\U679c\U59bb\U5b50\U53d8\U88c5\U540e\U5728\U5927\U8857\U4e0a\U642d\U8baa\U4e08\U592b\Uff0c\U4e08\U592b\U4f1a...?\U3010\U4eba\U529b\U5b57\U5e55\U7ec4\U3011/7706086-5.flv",
    "/Users/Yukun/Movies/Bilibili/\U3010\U4eba\U7c7b\U89c2\U5bdf\U3011160519 \U5982\U679c\U59bb\U5b50\U53d8\U88c5\U540e\U5728\U5927\U8857\U4e0a\U642d\U8baa\U4e08\U592b\Uff0c\U4e08\U592b\U4f1a...?\U3010\U4eba\U529b\U5b57\U5e55\U7ec4\U3011/7706086-6.flv",
    "/Users/Yukun/Movies/Bilibili/\U3010\U4eba\U7c7b\U89c2\U5bdf\U3011160519 \U5982\U679c\U59bb\U5b50\U53d8\U88c5\U540e\U5728\U5927\U8857\U4e0a\U642d\U8baa\U4e08\U592b\Uff0c\U4e08\U592b\U4f1a...?\U3010\U4eba\U529b\U5b57\U5e55\U7ec4\U3011/7706086-7.flv",
    "/Users/Yukun/Movies/Bilibili/\U3010\U4eba\U7c7b\U89c2\U5bdf\U3011160519 \U5982\U679c\U59bb\U5b50\U53d8\U88c5\U540e\U5728\U5927\U8857\U4e0a\U642d\U8baa\U4e08\U592b\Uff0c\U4e08\U592b\U4f1a...?\U3010\U4eba\U529b\U5b57\U5e55\U7ec4\U3011/7706086-8.flv",
    "/Users/Yukun/Movies/Bilibili/\U3010\U4eba\U7c7b\U89c2\U5bdf\U3011160519 \U5982\U679c\U59bb\U5b50\U53d8\U88c5\U540e\U5728\U5927\U8857\U4e0a\U642d\U8baa\U4e08\U592b\Uff0c\U4e08\U592b\U4f1a...?\U3010\U4eba\U529b\U5b57\U5e55\U7ec4\U3011/7706086-9.flv",
    "/Users/Yukun/Movies/Bilibili/\U3010\U4eba\U7c7b\U89c2\U5bdf\U3011160519 \U5982\U679c\U59bb\U5b50\U53d8\U88c5\U540e\U5728\U5927\U8857\U4e0a\U642d\U8baa\U4e08\U592b\Uff0c\U4e08\U592b\U4f1a...?\U3010\U4eba\U529b\U5b57\U5e55\U7ec4\U3011/7706086-10.flv",
    "/Users/Yukun/Movies/Bilibili/\U3010\U4eba\U7c7b\U89c2\U5bdf\U3011160519 \U5982\U679c\U59bb\U5b50\U53d8\U88c5\U540e\U5728\U5927\U8857\U4e0a\U642d\U8baa\U4e08\U592b\Uff0c\U4e08\U592b\U4f1a...?\U3010\U4eba\U529b\U5b57\U5e55\U7ec4\U3011/7706086-11.flv",
    "/Users/Yukun/Movies/Bilibili/\U3010\U4eba\U7c7b\U89c2\U5bdf\U3011160519 \U5982\U679c\U59bb\U5b50\U53d8\U88c5\U540e\U5728\U5927\U8857\U4e0a\U642d\U8baa\U4e08\U592b\Uff0c\U4e08\U592b\U4f1a...?\U3010\U4eba\U529b\U5b57\U5e55\U7ec4\U3011/7706086-12.flv",
    "/Users/Yukun/Movies/Bilibili/\U3010\U4eba\U7c7b\U89c2\U5bdf\U3011160519 \U5982\U679c\U59bb\U5b50\U53d8\U88c5\U540e\U5728\U5927\U8857\U4e0a\U642d\U8baa\U4e08\U592b\Uff0c\U4e08\U592b\U4f1a...?\U3010\U4eba\U529b\U5b57\U5e55\U7ec4\U3011/7706086-13.flv",
    "/Users/Yukun/Movies/Bilibili/\U3010\U4eba\U7c7b\U89c2\U5bdf\U3011160519 \U5982\U679c\U59bb\U5b50\U53d8\U88c5\U540e\U5728\U5927\U8857\U4e0a\U642d\U8baa\U4e08\U592b\Uff0c\U4e08\U592b\U4f1a...?\U3010\U4eba\U529b\U5b57\U5e55\U7ec4\U3011/7706086-14.flv",
    "/Users/Yukun/Movies/Bilibili/\U3010\U4eba\U7c7b\U89c2\U5bdf\U3011160519 \U5982\U679c\U59bb\U5b50\U53d8\U88c5\U540e\U5728\U5927\U8857\U4e0a\U642d\U8baa\U4e08\U592b\Uff0c\U4e08\U592b\U4f1a...?\U3010\U4eba\U529b\U5b57\U5e55\U7ec4\U3011/7706086-15.flv",
    "/Users/Yukun/Movies/Bilibili/\U3010\U4eba\U7c7b\U89c2\U5bdf\U3011160519 \U5982\U679c\U59bb\U5b50\U53d8\U88c5\U540e\U5728\U5927\U8857\U4e0a\U642d\U8baa\U4e08\U592b\Uff0c\U4e08\U592b\U4f1a...?\U3010\U4eba\U529b\U5b57\U5e55\U7ec4\U3011/7706086-16.flv",
    "/Users/Yukun/Movies/Bilibili/\U3010\U4eba\U7c7b\U89c2\U5bdf\U3011160519 \U5982\U679c\U59bb\U5b50\U53d8\U88c5\U540e\U5728\U5927\U8857\U4e0a\U642d\U8baa\U4e08\U592b\Uff0c\U4e08\U592b\U4f1a...?\U3010\U4eba\U529b\U5b57\U5e55\U7ec4\U3011/7706086.xml"
)
16/6/16 00:43:37.208	Bilibili[42808]	AcceptAnalytics=2 WithoutGUI=1
16/6/16 00:43:37.253	Bilibili[42808]	[Crashlytics] Version 3.4.1 (92)
16/6/16 00:43:37.302	Bilibili[42808]	[PlayerView] Starting load video
16/6/16 00:43:37.302	Bilibili[42808]	[PlayerView] Reading video info
16/6/16 00:43:37.302	Bilibili[42808]	[VideoReader] Video Address: /Users/Yukun/Movies/Bilibili/【人类观察】160519 如果妻子变装后在大街上搭讪丈夫，丈夫会...?【人力字幕组】/7706086-1.flv
16/6/16 00:43:37.306	Bilibili[42808]	Video Request Error:Error Domain=NSURLErrorDomain Code=-1002 "不被支持的 URL" UserInfo={NSLocalizedDescription=不被支持的 URL, NSUnderlyingError=0x7f8d3ac891b0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "不被支持的 URL" UserInfo={NSLocalizedDescription=不被支持的 URL}}}
16/6/16 00:43:37.306	Bilibili[42808]	[SimpleParser][FLV] Size pattern not found
16/6/16 00:43:37.308	Bilibili[42808]	[PlayerView] X: 11.000000 Y: 57.000000 Width: 1440.000000 Height: 820.000000
16/6/16 00:43:37.311	Bilibili[42808]	[PlayerView] Read video info completed
16/6/16 00:43:37.313	Bilibili[42808]	[PlayerManager] Create player 3787278219
16/6/16 00:43:39.368	Bilibili[42808]	[Crashlytics:Crash] Warning: NSApplicationCrashOnExceptions is not set. This will result in poor top-level uncaught exception reporting.

**Comment by ikamal** [comment]
啊，发现问题了，是目录中的 `...?` 字符串解析错误了！

**Comment by typcn** [comment]
尝试只勾选视频文件？同文件夹下弹幕会自动加载
