### ISSUE TITLE
bilibili依赖mpv运行环境,是怎样把mpv打包到安装程序，然后能直接独立运行播放的呢？

### ISSUE THREAD

**Issue by huos3203** [typcn/bilibili-mac-client#282]
1. osx 10.11.5
2. mpv ：通过git clone mpv-build.git ->ffmpeg: make ,make install -> mpv: waf编译运行安装
3. 通过libmpv.dylib集成到个人项目中，运行正常。  

问题：打包之后，生成app文件，在新环境的osx机器上无法运行？
该如何打包app,能够独立运行播放呢？

**Comment by typcn** [comment]
直接编译出来的库会是绝对路径，需要先通过 install_name_tool 修改 rpath 
```install_name_tool -id "@executable_path/lib/libmpv.dylib" libmpv.dylib```
然后执行 mpv 的 tools/dylib-unhell ，目标是 libmpv.dylib 这个文件，这样会多出一个 lib 文件夹，里面会出现变为相对路径的文件，复制并覆盖我原来的文件即可

**Comment by huos3203** [comment]
执行提示如下问题：python dylib-unhell.py 
```
Traceback (most recent call last):
  File "dylib-unhell.py", line 94, in <module>
    main()
  File "dylib-unhell.py", line 86, in main
    binary = os.path.abspath(sys.argv[1])
IndexError: list index out of range
```

**Comment by typcn** [comment]
加参数。。。

**Comment by typcn** [comment]
参数是dylib的路径

**Comment by huos3203** [comment]
嗯，dylib-unhell生成了lib和对应的库文件
替换了项目中的libmpv.dylib，xcode run运行正常。
从archive之后的包结构：
![2016-06-27 11 42 23](https://cloud.githubusercontent.com/assets/4022953/16368027/5e67cc2e-3c5c-11e6-9b0b-3199e1ca349c.png)
当双击运行该app时，无法运行。

**Comment by typcn** [comment]
你注意 bilimac 的 Build Phases ，这样改了之后需要把所有的 dylib 复制到 Contents/MacOS/lib

**Comment by huos3203** [comment]
dylib-unhell生成lib目录，生成的库文件只有一个libmpv.dylib呢，bulimic结构中的Contents/MacOS/lib中相关ffmepg的库文件是从那来的呢？

**Comment by typcn** [comment]
ffmpeg 如果是静态编译/链接的，那是不会生成的

**Comment by huos3203** [comment]
我直接把第二步：即
2. mpv ：通过git clone mpv-build.git ->ffmpeg: make ,make install -> mpv: waf编译运行安装

过程中生成的ffmpeg库文件复制到 Contents/MacOS/lib可行吗？

**Comment by typcn** [comment]
你可以通过 otool -L 文件名 查看它们的 rpath
然后可以通过 install_name_tool 来修改
建议阅读一下 mach-o 可执行文件的相关文档

**Comment by huos3203** [comment]
嗯嗯，谢谢 @typcn 耐心指教
找到了痛点：[Mach-O 可执行文件](http://objccn.io/issue-6-3/)

**Comment by huos3203** [comment]
参照这篇文章：[xcode,cocoa开发：如何使用第三方的dylib](http://blog.devep.net/virushuo/2009/07/01/xcodecocoadylib.html)
使用: otool -L mpv-examples.app/Contents/MacOS/mpv-examples  
 install_name_tool -change 修改了依赖库路径
如下：
```
@executable_path/lib/libz.1.2.5.tbd (compatibility version 1.0.0, current version 1.2.5)
	@executable_path/lib/libmpv.1.dylib (compatibility version 1.0.0, current version 1.21.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1258.0.0)
	.....
```
没有看到ffmpeg相关库依赖，大概因为是我ffmpeg **静态编译的**。
参看了bilimac.app结构都是dylib库：
![default](https://cloud.githubusercontent.com/assets/4022953/16448314/63512d5c-3e23-11e6-95b3-c705b49d2b53.png)
请问大神：以上ffmpeg动态库是怎么生成的？
如果ffmpeg动态编译之后，是否在执行python dylib-unhell.py path/libmpv.dylib命令，就会在lib目录生成了所有依赖？

**Comment by typcn** [comment]
1. 参数 “--enable-shared ” 可以开启 ffmpeg 的动态版本
2. 是的，会自动生成 ffmpeg 的依赖

**Comment by huos3203** [comment]
嗯，执行了以下命令：
```ruby
./waf configure --enable-static-build --enable-libmpv-shared  --disable-libass
./waf build
./TOOLS/dylib-unhell.py build/libmpv.dylib 
```
lib目录还是空空如也！
我是否有其他地方没有注意到的呢？

**Comment by typcn** [comment]
编译 ffmpeg 的时候加 --enable-shared

**Comment by huos3203** [comment]
编译ffmpeg是必须在mpv-build.git的目录中吗：
![default](https://cloud.githubusercontent.com/assets/4022953/16476062/2fdfcd3c-3eb6-11e6-8ee6-d07e3ce4e3e1.png)
我执行行了：
```ruby
cd mpv-build/ffmpeg
./configure  --enable-shared
make 
make install
```
再执行
```ruby
./waf configure --enable-static-build --enable-libmpv-shared  --disable-libass
./waf build
./TOOLS/dylib-unhell.py build/libmpv.dylib 
```
lib目录依然空空如也！

**Comment by huos3203** [comment]
重新执行了以上命令OK!
![default](https://cloud.githubusercontent.com/assets/4022953/16481803/a63938dc-3edf-11e6-9c67-ad0e12b14af9.png)
不过在目录中没有找到依赖中的libz.1.dylib，现在项目中直接引用系统中的libz.1.tbd包，在xcode下运行正常，但无法在新环境下独立运行。

**Comment by typcn** [comment]
tbd 是一个类似描述文件的，纯文本的，你打开里面就能看到路径。

你可以看在新环境中的报错信息，是缺少哪个库，就复制过来用 install name tool 修改

**Comment by huos3203** [comment]
![default](https://cloud.githubusercontent.com/assets/4022953/16483298/6804c714-3ee6-11e6-9efa-08b4f3478100.png)
是直接把 install-name:所指的文件直接拷贝到`mpv-examples.app/Contents/MacOS/lib/`目录吗？
在执行：
```ruby
install_name_tool -change /usr/lib/libz.1.dylib @executable_path/lib/libz.1.dylib "mpv-examples.app/Contents/MacOS/mpv-examples"
```
再运行：
```ruby
otool -L mpv-examples.app/Contents/MacOS/mpv-examples
#打印：
	@executable_path/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	@executable_path/lib/libmpv.1.dylib (compatibility version 1.0.0, current version 1.21.0)
	@executable_path/lib/libavformat.57.dylib (compatibility version 57.0.0, current version 57.39.100)
	@executable_path/lib/libavutil.55.dylib (compatibility version 55.0.0, current version 55.25.100)
	@executable_path/lib/libswresample.2.dylib (compatibility version 2.0.0, current version 2.1.100)
	@executable_path/lib/libavfilter.6.dylib (compatibility version 6.0.0, current version 6.46.102)
	@executable_path/lib/libavdevice.57.dylib (compatibility version 57.0.0, current version 57.0.10
```
操作过程应该没有问题的呢？就是双击无法运行

**Comment by typcn** [comment]
你要看双击运行之后 dyld 的报错，缺少哪个库

**Comment by typcn** [comment]
还有就是不仅要修改可执行文件的 install name，还要修改 lib 文件夹里面别的 dylib 的 install name

**Comment by huos3203** [comment]
嗯，项目中仅包含了 libmpv.dylib 命令生成在lib目录的相关dylib库，直接复制到项目中打包，执行otool -L显示相关库路径都是以@executable_path/lib/开头的，只有libz.1.dylib是例外的
对libz.1.dylib手动操作，关联后，双击崩溃有以下日志：
![d](https://cloud.githubusercontent.com/assets/4022953/16483991/82208b94-3ee9-11e6-8ef1-c34bb82e63d2.png)

**Comment by typcn** [comment]
.....你把静态和动态混合了

**Comment by huos3203** [comment]
没有混合，只有引用了动态库

**Comment by typcn** [comment]
你把报错信息读两遍....

**Comment by huos3203** [comment]
没接触过这个错误...操作流程应该没有问题吧？

**Comment by huos3203** [comment]
我再走下流程...

**Comment by huos3203** [comment]
发现设置在search Paths -> Library Search Paths的值包含了以前的静态库路径和当前动态库路径。
修改去除了以前的静态库路径。

**Comment by huos3203** [comment]
重新操作相关步骤：
重新git mov-build.git
```ruby
cd mpv-build/
./rebuild -j4
cd ffmpeg/
./configure  --enable-shared
make 
make install
```
再执行：
```ruby
变更去除static参数：./waf configure --enable-static-build --enable-libmpv-shared  --disable-libass
./waf configure --enable-libmpv-shared  --disable-libass
./waf build
./TOOLS/dylib-unhell.py build/libmpv.dylib 
```
以上操作，顺利完成。
集成到项目中，使用otool -L 和install_name_tool完成了一系列操作。

2. 这两个的命令功能一样吧：
```ruby
install_name_tool -change
install_name_tool -id 
```
检查了build setting相关配置，也没再发现相关静态库的设置了。
问题还是存在：
![d](https://cloud.githubusercontent.com/assets/4022953/16483991/82208b94-3ee9-11e6-8ef1-c34bb82e63d2.png)

**Comment by huos3203** [comment]
问题已解决，集成步骤没有问题，发现是项目中openFile:方法中的bug。
太感谢 @typcn 不吝赐教
