### ISSUE TITLE
关于下载视频的播放问题

### ISSUE THREAD

**Issue by ariour** [typcn/bilibili-mac-client#288]
有2个问题：（下载下来是很多个分段视频文件比如有10个）
1、如果只点击其中一个播放，弹幕的时间是从头开始的，而不是从播放文件的那个时间点出相应的弹幕内容。
2、如果点选文件夹拖进播放器，只是显示第一个分段内容，播放完后会进行到下一段，而不是整体的时间。另外，这个方法的话会不加载弹幕。

ps是不是我每次播放下载文件的方法不对= =

**Comment by typcn** [comment]
按住Shift选择全部要播的文件，包括弹幕

**Comment by ariour** [comment]
那就出现了第一个问题。弹幕内容是从头开始的 - -

**Comment by typcn** [comment]
选择全部要播的文件，会<font color="red">**自动将所有分段合并为同一时间轴**</font>
