### ISSUE TITLE
无法连接到 API 服务，请确保您正在使用 Bilibili for mac 最新版本

### ISSUE THREAD

**Issue by Reigning** [typcn/bilibili-mac-client#289]
我已经使用了 Bilibili for mac 最新版本，但是新建标签页的时候提示无法连接。
在谷歌 Chorme 浏览器中打开 vp-hub.eqoe.cn 没有问题，但是在 客户端中 CSS 和 JS 加载异常。 
经过调试发现  Bilibili for mac 打不开像 http://localhost:23330/static/material.min.js 这类的文件，可是谷歌浏览器可以打开，可能是  Bilibili for mac 内置的浏览器发生了崩溃，没有使用默认代理设置。 
望解决，谢谢！

**Comment by typcn** [comment]
bilimac 内置的浏览器就等于 Safari ，一切的行为都和 Safari 是相同的，请确保你在系统的代理设置中将 localhost 排除掉了

**Comment by Reigning** [comment]
我的解决方案：格式化全盘并重新安装 OS X 系统。虽然这样比较暴力，但是对于未知的端口错误，这样很有效。

**Comment by Reigning** [comment]
我找到原因了，因为我的ｈｏｓｔｓ文件遭到丢失，导致了打不开ｌｏｃａｌｈｏｓｔ域名下的文件，最终恢复ｈｏｓｔｓ，解决！
