### ISSUE TITLE
关于aria2的相关问题

### ISSUE THREAD

**Issue by dxs9642** [typcn/bilibili-mac-client#29]
你好，我刚开始接触osx的开发，偶然看到你的代码很感兴趣。
因为我需要一个相关的下载框架使用，感觉aria2错，但是对aria2不了解，能不能详细告诉我一下你的libaria2.0.dylib是怎么做出来的吗。还有其他的相关的osx的下载框架推荐吗，谢谢

**Comment by typcn** [comment]
下载 aria2 的源代码，configure help 把动态静态都启用 ，make
记得用installnametool改 rpath

**Comment by dxs9642** [comment]
大神再问个问题，我编译aria2的时候出现macro 'AM_PATH_LIBGCRYPT' not found in library，然后我brew install libxml2，然后强制brew link libxml2 --force才能生成configure，但是在./configure仍然出现 syntax error near unexpected token `1.2.4,'  ./configure: line 20197: `    AM_PATH_LIBGCRYPT(1.2.4, have_libgcrypt=yes)'问题，我该怎么解决啊

**Comment by typcn** [comment]
找不到 LIBGCRYPT 你为什么会去联想到 libxml2 ？

**Comment by typcn** [comment]
https://github.com/tatsuhiro-t/aria2/blob/master/README.rst#dependency

**Comment by typcn** [comment]
另外，如果用不着什么 XMLRPC JSONRPC 可以直接 without-xxx

**Comment by dxs9642** [comment]
情况是这样的，即使我使用./configure --enable-static --enable-shared --without-libxml2也是过不去，任然是这个错误：syntax error near unexpected token 1.2.4,' ./configure: line 20197: AM_PATH_LIBGCRYPT(1.2.4, have_libgcrypt=yes)'，主要是在autoreconf -i出现的问题：
configure.ac:471: error: possibly undefined macro: AM_PATH_LIBGCRYPT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1

**Comment by dxs9642** [comment]
然后我强制brew link libxml2 --force即通过了

**Comment by typcn** [comment]
BREW INSTALL LIBGCRYPT

**Comment by dxs9642** [comment]
(:o 」∠)_大神碉堡了
大神再问最后一个问题，make成功了，然后怎么再生成dylib文件啊

**Comment by typcn** [comment]
find . -name "*.dylib"

**Comment by dxs9642** [comment]
找了，木有（>_<）

**Comment by typcn** [comment]
MAKE

**Comment by dxs9642** [comment]
MAKE完毕，然后没有的，configure只开启了两个参数--enable-static --enable-shared，可以吗

**Comment by typcn** [comment]
find . -name "*.dylib"
肯定有的，是在一个隐藏的文件夹

**Comment by dxs9642** [comment]
➜  aria2-master  find . -name "*.dylib" 
➜  aria2-master

**Comment by typcn** [comment]
./configure --help

Press Command+F and find "lib"

**Comment by dxs9642** [comment]
是不是要再加上--enable-libaria2

**Comment by typcn** [comment]
yes

**Comment by dxs9642** [comment]
success！！！你完美的解决了我的问题。
大神太厉害了😉
