### ISSUE TITLE
有的视频在加载缓冲后，直接回到原来普通播放界面界面，只有播放器的页面关闭

### ISSUE THREAD

**Issue by wwh9371** [typcn/bilibili-mac-client#291]
有的视频在加载缓冲一会后，只有播放器的页面关闭，直接回到原来普通网页播放界面界面。这个情况有的视频有，其他的可以正常播放。不能正常播放的视频在网页版也是可以正常看的。

**Comment by wwh9371** [comment]
就是在正在下载视频和弹幕，正在创建播放器之后关闭的

**Comment by typcn** [comment]
请通过 Console.app 查看日志
