### ISSUE TITLE
部分视频提示“所有视屏源连接失败，可能视频已失效”

### ISSUE THREAD

**Issue by cdroad** [typcn/bilibili-mac-client#297]
如题，我在观看这个的时候发现了这样的错误，http://www.bilibili.com/video/av4454690/，但是chorm里的flash是能正常解析并播放的。

**Comment by typcn** [comment]
请发送问题出现时的日志（Console.app）

**Comment by typcn** [comment]
这个视频的容器压制的有问题，且似乎没有被二压，你可以在设置中开启 MP4 模式观看
