### ISSUE TITLE
请问右下角有广告是客户端添加的吗

### ISSUE THREAD

**Issue by ThroneAlbert** [typcn/bilibili-mac-client#299]
如题，今日打开客户端时，首页右下角有广告，但广告是一片空白，有人有同样情况吗？
![](http://ww1.sinaimg.cn/large/006tNbRwjw1f620vk6aa4j31kw0zktws.jpg)

**Comment by typcn** [comment]
运营商劫持，空白是因为我内置的广告拦截器拦截了，但是拦截不彻底
