### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by CoderJackie** [typcn/bilibili-mac-client#300]
按照编译步骤，https://github.com/typcn/bilibili-mac-client/blob/master/HOW_TO_BUILD.md，编译错误：

Undefined symbols for architecture x86_64:
  "_mpv_command", referenced from:
      -[PlayerView playVideo:] in PlayerView.o
  "_mpv_command_async", referenced from:
      -[PlayerControlView nextEP:] in PlayerControlView.o
      -[PlayerControlView prevEP:] in PlayerControlView.o
      -[PlayerControlView subSwitch:] in PlayerControlView.o
      -[PlayerControlView keepAspectSwitch:] in PlayerControlView.o
      -[PlayerWindow scrollWheel:] in PlayerWindow.o
      ___29-[PlayerWindow showMediaInfo]_block_invoke in PlayerWindow.o
      -[PlayerWindow keyDown:] in PlayerWindow.o
      ...
  "_mpv_create", referenced from:
      -[PlayerView playVideo:] in PlayerView.o
  "_mpv_error_string", referenced from:
      check_error(int) in PlayerView.o
  "_mpv_get_property_async", referenced from:
      -[PlayerControlView readInitState] in PlayerControlView.o
      -[PlayerControlView updateTime] in PlayerControlView.o
  "_mpv_get_property_string", referenced from:
      -[PostComment Send:] in PostComment.o
      ___29-[PlayerWindow showMediaInfo]_block_invoke in PlayerWindow.o
  "_mpv_initialize", referenced from:
      -[PlayerView playVideo:] in PlayerView.o
  "_mpv_observe_property", referenced from:
      -[PlayerControlView readInitState] in PlayerControlView.o
  "_mpv_request_log_messages", referenced from:
      -[PlayerView playVideo:] in PlayerView.o
  "_mpv_set_option", referenced from:
      -[PlayerView playVideo:] in PlayerView.o
  "_mpv_set_option_string", referenced from:
      -[PlayerView setMPVOption::] in PlayerView.o
      -[PlayerView playVideo:] in PlayerView.o
      -[PlayerView loadMPVSettings] in PlayerView.o
  "_mpv_set_property_async", referenced from:
      -[PlayerControlView setVolume:] in PlayerControlView.o
      -[PlayerControlView seekTo:] in PlayerControlView.o
      -[PlayerControlView playPause:] in PlayerControlView.o
      -[PlayerControlView mute:] in PlayerControlView.o
      -[PlayerControlView subSwitch:] in PlayerControlView.o
      -[PlayerControlView keepAspectSwitch:] in PlayerControlView.o
      -[PlayerWindow toggleFullScreen:] in PlayerWindow.o
      ...
  "_mpv_set_wakeup_callback", referenced from:
      -[PlayerView playVideo:] in PlayerView.o
      -[PlayerWindow mpv_cleanup] in PlayerWindow.o
  "_mpv_terminate_destroy", referenced from:
      ___27-[PlayerWindow mpv_cleanup]_block_invoke in PlayerWindow.o
  "_mpv_wait_event", referenced from:
      ___24-[PlayerView readEvents]_block_invoke in PlayerView.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by typcn** [comment]
你没有安装 git-lfs 就 clone 了，可以从软件的 Content/MacOS/lib/ 提取然后覆盖带源代码目录 bilibili/libs

**Comment by CoderJackie** [comment]
ok了，我又按照教程来了一遍，可能是之前没用这个下载
`cd bilibili/libs/
rm -rf *.dylib
wget http://7xkd32.dl1.z0.glb.clouddn.com/bilibili/libs/2.zip
unzip 2.zip`

但是第一次`brew install git-lfs`成功了
