### ISSUE TITLE
部分直播间弹幕无法显示

### ISSUE THREAD

**Issue by xjbeta** [typcn/bilibili-mac-client#301]
比如  423510

**Comment by typcn** [comment]
已经切换到新的弹幕接口，更新到测试版本通道即可提前使用

**Comment by xjbeta** [comment]
话说  切换测试版本通道的命令是什么

**Comment by typcn** [comment]
加入：defaults write com.typcn.Bilibili SUFeedURL
https://archive.typcn.download/bilimac/latest/appcast.xml
退出：defaults delete com.typcn.Bilibili SUFeedURL
