### ISSUE TITLE
伪造ip 功能疑似失效

### ISSUE THREAD

**Issue by matthew-z** [typcn/bilibili-mac-client#303]
最新版本2.4.3, 开启了 ip 伪装

之前都挺正常的, 今天突然失效了  提示 

根据版权方要求，您所在的地区无法观看本番，敬请谅解

**Comment by typcn** [comment]
B 站修改了策略，你可以尝试点击 av 号到原页面观看

我看看他还有什么别的头，不行的话就搞个反代

**Comment by matthew-z** [comment]
@typcn 原来如此  点击 AV 号就可以看

**Comment by typcn** [comment]
新版本加了一个自动跳转回原页面的 workaround

**Comment by Joshua1989** [comment]
貌似现在有版权的新番点进av号也看不了了，显示“所有视频源连接失败，可能视频已失效”，比如这个
http://www.bilibili.com/video/av5667410/

**Comment by typcn** [comment]
这是第三方播放器不是b站自己买的吧

**Comment by matthew-z** [comment]
同楼上, 所有版权番提示"所有视频源连接失败，可能视频已失效"

**Comment by Joshua1989** [comment]
我试了下bilibilijj可以下载，不知道bilibili for mac是如何获取视频和弹幕文件的url的
如果不是通过bilibilijj的话感觉把它作为一个exception的解决方案应该可行

**Comment by typcn** [comment]
我日，playurl 也给日了？真TM。。。

**Comment by typcn** [comment]
{"code":-5021,"message":"video is not allow to play in your area"}


下手真狠。。。 其实我有他们 CDN 对源站传送真实 IP 的头名称，但是我感觉这个放出来应该会很快死

现在大概只能反代或者用第三方了？

**Comment by typcn** [comment]
找到了。。。TM 只要加上 accel=1 就好了

**Comment by typcn** [comment]
刚刚还有效的，现在已经 GG 了，算了，我直接把 CDN 传送真实 IP 的头给加进去了

重启软件后，会自动从服务器上下载新的解析模块，伪造 IP 会立即生效

**Comment by matthew-z** [comment]
生效了~  谢谢

**Comment by threefcata** [comment]
我说，反正用了chrome么，是不是可以再带个unblock youku插件，用那个翻墙回去就行了吧

**Comment by oscar-c** [comment]
最近又不行了，打开版权视频会无限循环刷新

**Comment by typcn** [comment]
看到了。。b 强制跳转回来了，我改改注入逻辑吧

**Comment by typcn** [comment]
已修复，启用测试通道即可更新，正式通道明天更新

**Comment by oscar-c** [comment]
不知道为什么 [这个番](http://bangumi.bilibili.com/anime/v/96620) 还是无限跳转

**Comment by typcn** [comment]
我用的是 http://www.bilibili.com/widget/getPageList 这个 API，但是不知道为何这个 API 对这个番返回了 404...
