### ISSUE TITLE
2015 air 全屏播放发热严重，自动卡顿停止播放。

### ISSUE THREAD

**Issue by mengbingrock** [typcn/bilibili-mac-client#304]
查看cpu发现只有20%~30%的使用率，和直接看网页相当。
可是为什么网页发热不明显，使用这个程序非常烫呢？

**Comment by typcn** [comment]
可能是 mpv 的一些 bug 全屏那个动画的频繁 resize 导致的全盘问题，这个我没法重现...也很难找.....

你可以暂时不全屏，我尝试做一些 workaround

**Comment by typcn** [comment]
详情查看 mpv 的 #3364

这是一个苹果的 BUG，6 年没有修。。。。
