### ISSUE TITLE
网站视频打开只能显示一小段

### ISSUE THREAD

**Issue by liyouvane** [typcn/bilibili-mac-client#305]
比如一个一个半小时的节目，用客户端打开之后视频只能走前面5分钟就结束了，反复刷新也没法看到之后的内容。偶尔又会变好，但是在腾讯视频这样的网站上似乎经常出现这样的问题。

**Comment by typcn** [comment]
什么？请描述清楚，看哪个网站的视频，哪个视频，错误什么时候出现，出现时软件的日志

**Comment by liyouvane** [comment]
啊不好意思 我忘记之前的链接了＝＝等我再遇到了和你说🙈
