### ISSUE TITLE
You-Get插件解析错误

### ISSUE THREAD

**Issue by cos-ss** [typcn/bilibili-mac-client#306]
mac OS X 10.11.5
macbook air 2015
斗鱼和Dilidili错误，应该好多都不行
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/12772673/17461791/cbdbdd3e-5cca-11e6-8199-2b0b6d24db1d.png)
![pastedgraphic-2](https://cloud.githubusercontent.com/assets/12772673/17461793/d01e37d4-5cca-11e6-913a-3194ea8de374.png)

还需要其他信息吗？

**Comment by typcn** [comment]
可以通过手动安装 you-get 来解决斗鱼
pip3 install you-get
然后在插件设置中设置 you-get 路径

**Comment by cos-ss** [comment]
用brew安装也是一样的是吧？
可以稍微说一下这个错误的原因吗？

**Comment by typcn** [comment]
这个一般是算法失效了，需要更新
