### ISSUE TITLE
[Bug] Infinite loop restarts at wrong position with previous playing records

### ISSUE THREAD

**Issue by LukeXuan** [typcn/bilibili-mac-client#307]
When a video is opened for the second time, it will start where it was closed last time. In such situation, if I enable the infinite loop, it will restart at the position where it starts this time, ignoring the duration before its start.

**Comment by typcn** [comment]
![image](https://cloud.githubusercontent.com/assets/8022103/17462386/a91b828c-5cdd-11e6-8f21-b117c2f91c09.png)

I have tested position save works fine on infinite loop enabled.


Have you triggered the control bar ? playback position is saved when control bar dismiss

**Comment by LukeXuan** [comment]
I've just tested and find that it will definitely happen when player is minimized. Maybe this is the reason.
