### ISSUE TITLE
b 站挂掉的情况下在读取弹幕时直接退出

### ISSUE THREAD

**Issue by JokerQyou** [typcn/bilibili-mac-client#31]
刚才 b 站挂掉了，网页上跟用户相关的页面都打不开，我试图用客户端播放视频，在「读取弹幕」这里等待了几分钟后，客户端直接退出了。没有崩溃也没有任何提示，直接不见了。

**Comment by typcn** [comment]
因为某个未知错误 exit 0 了吧

**Comment by typcn** [comment]
稍等我先发布个崩溃修复
