### ISSUE TITLE
战旗视频不能解析

### ISSUE THREAD

**Issue by KiritoStudio** [typcn/bilibili-mac-client#314]
战旗视频不能解析，typecn给看下呗~

**Comment by typcn** [comment]
请通过 brew 或 pip 安装最新版的 youget，然后在 youget 插件设置里面填写路径

**Comment by KiritoStudio** [comment]
@typcn  你好，我通过brew把you-get更新到最新，然后在You-get设置里把which you-get里拿到的路径填上去，不过依旧不行。
![image](https://cloud.githubusercontent.com/assets/553215/17641949/fcabe62a-6166-11e6-9613-f4d8c88c2fb4.png)

![image](https://cloud.githubusercontent.com/assets/553215/17641959/4c0a74de-6167-11e6-941e-8aff429a568c.png)

我已经把flash下载并更新到最新了，相同的页面的话safari跟chrome都能打开
![image](https://cloud.githubusercontent.com/assets/553215/17641969/7b608908-6167-11e6-85e5-0569c4690819.png)

**Comment by typcn** [comment]
。。。。。。。。。。。。。。。。

YouGet 解析是播放器的浏览器窗口右上角那个播放按钮，不会替换页面里面的 JS

**Comment by KiritoStudio** [comment]
![image](https://cloud.githubusercontent.com/assets/553215/17644262/3607c43c-61b4-11e6-9f7d-dc8c24caf4cb.png)
你说地址栏右边我就看懂了。。网页上找了半天都没找到。。不过好像还是不能解析啊。。

**Comment by typcn** [comment]
为何是 RTMP 地址呢。。。youget 默认难道不是拿 flv

**Comment by typcn** [comment]
你尝试换回内置的试试？ {BundlePath}/Contents/MacOS/you-get

**Comment by KiritoStudio** [comment]
还是不行，你那边看看能重现么？

**Comment by typcn** [comment]
想到一个 workaround 办法，不过感觉不太好。。

下次更新我兼容一下 RTMP 地址吧

**Comment by KiritoStudio** [comment]
恩，非常感谢
