### ISSUE TITLE
打开本地文件出错

### ISSUE THREAD

**Issue by ywwzwb** [typcn/bilibili-mac-client#316]
打开本地文件, 崩溃
部分内容如下
Process:               Bilibili [8022]
Path:                  /Applications/Bilibili.app/Contents/MacOS/Bilibili
Identifier:            com.typcn.Bilibili
Version:               2.44 (3119)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Bilibili [8022]
User ID:               501

Date/Time:             2016-08-16 13:06:35.261 +0800
OS Version:            Mac OS X 10.11.6 (15G31)
Report Version:        11

Time Awake Since Boot: 1700 seconds

System Integrity Protection: enabled

Crashed Thread:        8  Dispatch queue: video_address_load_queue

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSPathStore2 characterAtIndex:]: index (42) beyond bounds (42)'
abort() called
terminating with uncaught exception of type NSException

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff94d7a4f2 __exceptionPreprocess + 178
1   libobjc.A.dylib                     0x00007fff831e9f7e objc_exception_throw + 48
2   CoreFoundation                      0x00007fff94de14bd +[NSException raise:format:] + 205
3   Foundation                          0x00007fff93bafcd3 -[NSPathStore2 characterAtIndex:] + 108
4   Bilibili                            0x000000010723e0b7 -[NSString(LcsDiff) lcsDiff:] + 336
5   Bilibili                            0x0000000107206a0a -[SP_Local findBestMatch:inFiles:withExtension:] + 775
6   Bilibili                            0x0000000107206585 -[SP_Local getSubtitle:] + 823
7   Bilibili                            0x0000000107205b11 -[SubtitleHelper getSubtitle:] + 257
8   Bilibili                            0x000000010720f749 __36-[PlayerLoader loadVideo:withAttrs:]_block_invoke + 116
9   libdispatch.dylib                   0x00007fff85ff993d _dispatch_call_block_and_release + 12
10  libdispatch.dylib                   0x00007fff85fee40b _dispatch_client_callout + 8
11  libdispatch.dylib                   0x00007fff85ff303b _dispatch_queue_drain + 754
12  libdispatch.dylib                   0x00007fff85ff9707 _dispatch_queue_invoke + 549
13  libdispatch.dylib                   0x00007fff85fee40b _dispatch_client_callout + 8
14  libdispatch.dylib                   0x00007fff85ff229b _dispatch_root_queue_drain + 1890
15  libdispatch.dylib                   0x00007fff85ff1b00 _dispatch_worker_thread3 + 91
16  libsystem_pthread.dylib             0x00007fff979324de _pthread_wqthread + 1129
17  libsystem_pthread.dylib             0x00007fff97930341 start_wqthread + 13

**Comment by ywwzwb** [comment]
打开的文件是一个 mp4 , 同文件夹下, 有对应的字幕文件, 测试如果直接在 finder 中用 bilibili 打开活着在bilibili菜单中使用"打开本地视频" 功能, 但是选择字幕, 均会崩溃, 如果在"打开本地视频"中同时选择字幕就不会失败

**Comment by typcn** [comment]
收到，似乎是字符串长度的bug

**Comment by typcn** [comment]
能否提供一下你尝试打开的文件名和字幕文件名？
