### ISSUE TITLE
只能解析第一个视频的地址

### ISSUE THREAD

**Issue by zssasa** [typcn/bilibili-mac-client#321]
观看的视频是[超智游戏](http://bangumi.bilibili.com/anime/v/21835)
但是用客户端观看所有视频解析的地址都是第一集的。
在safari上观看没问题。客户端看其它多p视频也没问题。

**Comment by typcn** [comment]
b 站好像把换 p 改成免刷新的了，可以先点击 av 号到原页面观看

**Comment by zssasa** [comment]
解决了！
谢啦
