### ISSUE TITLE
能不能加个支持21:9屏幕的拉伸模式？

### ISSUE THREAD

**Issue by cottonty** [typcn/bilibili-mac-client#322]
其实很多视频比如电影什么的都是21:9，不过视频本身是自带上下黑边，所以在我21:9屏幕上看过去是四面黑框 😂
要是能有像大多数本地播放器的那种上下去黑边的播放模式就好了

**Comment by typcn** [comment]
尝试按 W 和 E 键？

**Comment by cottonty** [comment]
碉堡了！！！赞！！
