### ISSUE TITLE
IP伪造貌似失效

### ISSUE THREAD

**Issue by Travical** [typcn/bilibili-mac-client#323]
版权番都看不了了

**Comment by typcn** [comment]
又失效了？你确定不是网络问题？...
解析模块里面可是有 3 种备用源的

**Comment by Travical** [comment]
用unlockyouku可以看应该不是网络问题吧

**Comment by Travical** [comment]
刷新的话番的列表可以出来一瞬间

**Comment by typcn** [comment]
unlock youku 做的比我的代码少得多，而且他是已经失效的方法

**Comment by typcn** [comment]
如果是网页提示地区错误，点里面的 AV 号可以到播放页面

**Comment by Travical** [comment]
貌似是的  只有选集的那个见面现实地区问题  用av号进去可以正常播放

**Comment by typcn** [comment]
我加了个 workaround ，应该好了
