### ISSUE TITLE
百度云网盘再次失效，You-get 部分支持网站失效。

### ISSUE THREAD

**Issue by oliverhuhan** [typcn/bilibili-mac-client#324]
百度云再次无法播放，点击播放虽然有提示获取文件信息成功但是不会跳转播放，两台 MacBook 和不同的 WiFi 网络下试过都是一样的结果；然后 You-get 支持页面上有 A 站但是 A 站上用 You-get 也已经失效；目前百度云上的 aria2 下载也已经失效，也是提示可以获取文件信息但是下载管理中显示错误。

**Comment by typcn** [comment]
已更新，请到插件中心更新插件
