### ISSUE TITLE
插件信息解析失败，返回内容错误

### ISSUE THREAD

**Issue by JustYummy** [typcn/bilibili-mac-client#327]
更新上了10.12，出现毛病了打开以后出现：插件信息解析失败，返回内容错误。安装插件时候也是显示这个。全部清空后重装以后还是这样子，然后打开~/Library/Application Support/com.typcn.bilibili/里面并无Plugins这个文件夹。BiliBli能正常使用，插件用不了。

**Comment by typcn** [comment]
这是苹果的 BUG ，等系统更新

**Comment by typcn** [comment]
刚测试了一下，beta1 无此问题，是 beta3 新引入的 BUG。。

**Comment by typcn** [comment]
加了个 workaround ，明天发更新
