### ISSUE TITLE
神奇的卡顿

### ISSUE THREAD

**Issue by sky-mashiro** [typcn/bilibili-mac-client#329]
同一个视频，如果通过客户端下载视频文件的话速度非常快，基本1-2MB/S，但是在线看就几秒一卡顿，这是为什么呢。。

**Comment by typcn** [comment]
下载视频功能是 10 线程，观看是单线程，网络不好肯定gg

**Comment by sky-mashiro** [comment]
@typcn 原来是这样。。。好蛋疼。。。
