### ISSUE TITLE
点击右下角的切换音轨的按钮后无法再切换回来

### ISSUE THREAD

**Issue by maemual** [typcn/bilibili-mac-client#33]
点击切换音轨的按钮会，再次点击，就无法重新切换回来。表现为无声音。

但是点击一下进度条，跳一下进度之后，声音会重新出现。

**Comment by typcn** [comment]
这是播放器的 BUG ，比较难处理，倒是可以通过切换音轨前进 0.1 秒来避免

**Comment by ainopara** [comment]
不用点进度条，等一会就能出现了。也许和缓存有关。

**Comment by typcn** [comment]
现在切换音轨不会导致声音问题了
