### ISSUE TITLE
视频无法播放

### ISSUE THREAD

**Issue by laike9m** [typcn/bilibili-mac-client#331]
坐标加州
视频：http://bangumi.bilibili.com/anime/v/91289
播放方式为 Chrome + bilibili-mac-client +  bilibili-mac 插件，版本皆为最新
![image](https://cloud.githubusercontent.com/assets/2592205/18537483/b7b45080-7aba-11e6-9c65-bd0daeefbb0d.png)

**Comment by typcn** [comment]
点击 设置 > IP 伪装，选择一个 IP

**Comment by laike9m** [comment]
OK，没问题了
