### ISSUE TITLE
mpv 配置文件无效

### ISSUE THREAD

**Issue by inflation** [typcn/bilibili-mac-client#333]
配置如下：

```
vo=opengl:scale=ewa_lanczossharp:interpolation:icc-profile-auto
osd-status-msg="${time-pos/full} / ${length/full} (${percent-pos}%)"
geometry=70%
video-sync=display-resample
sub-auto=fuzzy
sub-codepage=enca:zh:utf8
```

同样的配置在`~/.config/mpv/mpv.conf`和命令行`mpv`下都可以使用，但在客户端下就没有用。

**Comment by typcn** [comment]
除了 o s d 都会有效，因为 osd 会内部禁用

**Comment by inflation** [comment]
然而即使删除了那一行也没用，每次打开都会窗口最大化，很蛋疼

**Comment by typcn** [comment]
如果窗口关闭时宽度高度大于 100px ，则会自动记忆

如果是自动全屏，请查看设置选项

**Comment by inflation** [comment]
也没用，有什么办法看下log么？

**Comment by typcn** [comment]
我明天晚上回家看看..

**Comment by typcn** [comment]
https://github.com/typcn/bilibili-mac-client/blob/master/bilibili/Player/PlayerView.mm#L120-L133

这里是设置窗口大小的相关代码，如果上次保存的宽和高大于 300px ，则会自动应用
