### ISSUE TITLE
MPV快捷键无效

### ISSUE THREAD

**Issue by revintec** [typcn/bilibili-mac-client#334]
OSX 10.10.5, Bilibili 2.46 Build3200(最新版)

看了下源代码,是启用了mpv的默认快捷键的,但是mpv官网上的默认快捷键(比如视频速度控制的'[',']')都不好使.我自己装了mpv,命令行版的就好使.
尝试过在/Users/xxx/Library/Application Support/com.typcn.bilibili/conf/input.conf里加,并重启了客户端,不好使.com.typcn.bilibili/conf/mpv.conf的配置可以生效,尝试过在mpv.conf里加input-conf=/Users/xxx/...,并重启了客户端,还是不好使.
怀疑是不是键位扫描码不对,因为发现音量控制键居然是'\'和'TAB',而且只有+音量没有-音量.但是我未修改过系统按键映射.

想确认下其他人是否有这个问题,是否是已知问题并且有修复方案.感谢

**Comment by typcn** [comment]
键位是我这边 pass 给 mpv 的，而且 mpv 接受的键位是字符串类型，所以某些按键会不准确。。。

可以尝试绑定一些字面为字母，或者符号的按键？

**Comment by revintec** [comment]
@typcn 试了下,还是不行...你能复现这个BUG么?

**Comment by typcn** [comment]
我这里都是生效的啊。。

**Comment by revintec** [comment]
...额...难道我的系统有问题...我先自己研究下...

**Comment by lunaeidolon** [comment]
报告一下窗口置顶 Shift+T 无效

**Comment by typcn** [comment]
置顶窗口按 F ，因为窗口不是 mpv 接管的
