### ISSUE TITLE
点击“查看完整排行榜无反应”

### ISSUE THREAD

**Issue by zhangciwu** [typcn/bilibili-mac-client#336]
http://www.bilibili.com/ranking_beta
全区热门下，点击“查看完整排行榜”无反应
（好像因为只是hash改变了？）
![qq20160928-0](https://cloud.githubusercontent.com/assets/3340597/18900681/9a46780e-8576-11e6-9868-8b8f7972b897.png)

**Comment by typcn** [comment]
我这里在浏览器里面点也没反映。。。

**Comment by typcn** [comment]
哦是调用了 function rec_rp(){}

**Comment by zhangciwu** [comment]
浏览器可以跳转的

**Comment by typcn** [comment]
清空下缓存，应该可以了
