### ISSUE TITLE
bangumi.bilibili.com 无法绕过海外区域限制

### ISSUE THREAD

**Issue by EddieLiu-Works** [typcn/bilibili-mac-client#337]
Ex. 
http://bangumi.bilibili.com/anime/v/95907
http://bangumi.bilibili.com/movie/11890

播放器无法成功替换

www.bilibili.com 主域名没有问题。

辛苦了～

**Comment by typcn** [comment]
这个问题已经修复，你可以通过加入测试版通道 defaults write com.typcn.Bilibili SUFeedURL https://archive.typcn.download/bilimac/latest/appcast.xml

或者等正式版更新，大概今晚更新

**Comment by EddieLiu-Works** [comment]
Much appreciated.

国庆快乐～
