### ISSUE TITLE
无法显示弹幕，点击右下角的弹幕显示按钮，视频变为无声

### ISSUE THREAD

**Issue by marioZhou** [typcn/bilibili-mac-client#34]

**Comment by typcn** [comment]
直播的话目前是不支持的。
如果是一般视频：
1. 检查网络是否有问题，是否能访问 Bilibili 服务器
2. 这个视频根本没有弹幕
3. 灵异事件

如果播放器上，当前播放秒数都显示不出来，一个字都没有：
1. ![image](https://cloud.githubusercontent.com/assets/8022103/7683407/88b1945a-fdb1-11e4-9e02-2a33e521f429.png)  读一遍这行字
2. 请检查 /User/Shared 文件夹是否存在，以及权限是否正常

**Comment by typcn** [comment]
另外：右下角有两个按钮，一个是切换音轨，一个是切换字幕

弹幕属于字幕类型

**Comment by marioZhou** [comment]
谢谢～
的确是播放器上秒数也显示不出来，可已安装到applicaitons文件夹了。/User/Shared文件夹存在，权限是指什么呢？

**Comment by typcn** [comment]
系统环境呢？ 你确认一下 /Users/Shared/.fc 文件夹是否存在？
如果不存在，就创建一个，把软件包内 Contents/Resources/fontconfig 文件夹里面的所有内容复制过去。

**Comment by marioZhou** [comment]
系统是10.10.3  
文件夹存在，把Contents/Resources/fontconfig复制过去后可以显示弹幕，使用正常。
谢谢

**Comment by typcn** [comment]
fixed with https://github.com/typcn/bilibili-mac-client/commit/4fa97857dfa093a2172ea13f717f75fd771bd158

**Comment by zhugexiaobo** [comment]
OK，可以了。sorry，没有先搜索就开了 issue。

**Comment by zhugexiaobo** [comment]
OK，可以了。sorry，没有先搜索就开了 issue。
