### ISSUE TITLE
百度云播放速度的问题

### ISSUE THREAD

**Issue by ariour** [typcn/bilibili-mac-client#340]
海外用户。更新后百度云又能用了撒花！
但是发现一个问题，用浏览器网页打开百度云在线看时，会自动的加载进度，播放几乎无障碍。
切换到bili客户端后，同样的网络环境下，一开头就会卡住，并且经常显示0mb，暂停缓存一会，播几秒又卡住了- -（海外伪造ip取消、打开都一样）
不知道是什么原因。。。

**Comment by typcn** [comment]
百度的网页播放是独立的，压缩过的源，可能没有限速或者限速较小

而播放器是直接走的下载文件的 API，部分资源的限速可能会比较严重，这是在百度服务器端上做的，我没有什么办法。

你可以点击下载按钮，会用 16 线程下载视频，然后可以直接播放下载中的文件，大部分编码正确的视频文件都可以在下载完成之前直接开始播放。

**Comment by typcn** [comment]
最近忙的飞起，有时间的时候抓一抓网页播放器的 API。。。
