### ISSUE TITLE
优酷插件解析失败

### ISSUE THREAD

**Issue by ZGWS88** [typcn/bilibili-mac-client#346]
MacOS 10.12，BiliBili 2.47(Build 3293)关于优酷插件，点击“立即播放“后显示”解析失败“。

**Comment by ZGWS88** [comment]
貌似是找不到flash。（已安装最新版flash

**Comment by typcn** [comment]
首页已经写了“暂时失效”.字体太小么.....

**Comment by ZGWS88** [comment]
= =抱歉。是我看漏了
