### ISSUE TITLE
Deprecated API Usage - Apple no longer accepts submissions of apps that use QuickTime or QTKit APIs

### ISSUE THREAD

**Issue by huos3203** [typcn/bilibili-mac-client#348]
提示：Deprecated API Usage - Apple no longer accepts submissions of apps that use QuickTime or QTKit APIs
@typcn 你好，我在在提交iTunes应用包时，出现了以上信息，不知能否去除过期的APIs？

**Comment by typcn** [comment]
这是提交什么代码？整个程序里面没有任何与 quicktime 相关的东西

**Comment by huos3203** [comment]
是基于咱们Mac版哔哩哔哩播放器，定制了相关业务的个人应用程序。以上问题是否会受mpv编译导致的问题呢？
@typcn

**Comment by typcn** [comment]
不可能

**Comment by typcn** [comment]
检查一下有没有用 qtkit 之类的东西吧
