### ISSUE TITLE
希望增加倍速播放功能

### ISSUE THREAD

**Issue by uucky** [typcn/bilibili-mac-client#350]
类似YouTube的，0.25/0.5/1/1.25/1.5/2倍速播放。（我个人最常用的是1.5/2倍速）
感谢！

**Comment by kimgogo** [comment]
这个mpv播放器自带的功能，我的是这“[”，“]”两个按键。应该是默认键位。

**Comment by typcn** [comment]
参见 常见问题：http://vp-hub.eqoe.cn/faq.html
