### ISSUE TITLE
版本2.48无法更新

### ISSUE THREAD

**Issue by liyouvane** [typcn/bilibili-mac-client#357]
从2.47试图更新到2.48， 显示update error，无法更新。
<img width="425" alt="screen shot 2016-11-04 at 23 46 17" src="https://cloud.githubusercontent.com/assets/15090572/20027375/ee3e1fea-a2e8-11e6-83ec-687bd4250799.png">

**Comment by typcn** [comment]
请确保您的网络连接正常，尝试更换 DNS ，关闭或使用代理
