### ISSUE TITLE
建议增加音量调节功能

### ISSUE THREAD

**Issue by gdshen** [typcn/bilibili-mac-client#36]
在将系统音量调节到一格时，程序默认音量还是太大，建议增加一下音量调节功能

**Comment by typcn** [comment]
然而 mpv 提供的音量调节 API ，在 OSX 上并没有卵用。。。。。

所以只好内置了调节系统音量的 API ，按上下方向键调节音量

这个比较难解决，更改设备/耳机的音量试试。。。

**Comment by matthew-z** [comment]
调节音量时按住 shift 和 option 可以1/4格为单位进行调节

**Comment by gdshen** [comment]
原来还能这样调节，涨姿势了，谢啦
