### ISSUE TITLE
貌似接触版权限制这块又失效了

### ISSUE THREAD

**Issue by Joshua1989** [typcn/bilibili-mac-client#360]
从昨天开始看版权番的话都会出现“肥肠抱歉，应版权方要求，您所在的地区无法观看本片TAT”，B站也是努力过了啊

追加：貌似所有视频都看不了了？

**Comment by xiao99xiao** [comment]
+1. 坐标日本，开启IP伪造，尝试过所有选项，所有视频点击播放按钮都无响应。

**Comment by typcn** [comment]
请您点击右下角的蓝色按钮，查看“常见问题”
