### ISSUE TITLE
大陆解析b站台湾版权番失效

### ISSUE THREAD

**Issue by YangJianchong** [typcn/bilibili-mac-client#365]
不知道是不是个案_(:_」∠)_
<img width="1388" alt="screen shot 2016-12-01 at 04 10 54" src="https://cloud.githubusercontent.com/assets/14205934/20769282/394e6dee-b77c-11e6-8ca6-41f517e56ebc.png">
<img width="1388" alt="screen shot 2016-12-01 at 04 11 08" src="https://cloud.githubusercontent.com/assets/14205934/20769285/3be87ffe-b77c-11e6-8d21-8ea34fe6ab30.png">

**Comment by typcn** [comment]
请确认伪造 IP 设置正确
