### ISSUE TITLE
无法发出弹幕

### ISSUE THREAD

**Issue by o2chan** [typcn/bilibili-mac-client#367]
看视频时无法发出弹幕，提示错误－8。
另外直播时发出弹幕时会提示发送成功但是实际上没有发出去。

**Comment by typcn** [comment]
API 好像改了，我明天修修。。。

**Comment by o2chan** [comment]
@typcn 从抓包看好像多了一项rnd，数值每次打开视频都会变

**Comment by typcn** [comment]
最近太忙一直没时间更新。。。已经修复，请更新到 2.49
