### ISSUE TITLE
客户端无法记录历史播放数据

### ISSUE THREAD

**Issue by baiyijun** [typcn/bilibili-mac-client#368]
客户端无法记录历史播放数据，b站历史里面不记录客户端观看的历史记录

**Comment by typcn** [comment]
我暂时没有环境测试，请确认以下问题:
1. 请确认设置中没有勾选“不写入历史记录”
2. 请尝试重新注销并登录 B 站，再看看是否正常

**Comment by baiyijun** [comment]
貌似是同一个客户端登陆不同的b站账号导致的问题，清除掉各种缓存后可以了
