### ISSUE TITLE
是否可以添加一个Daemon模式

### ISSUE THREAD

**Issue by sequencer** [typcn/bilibili-mac-client#371]
最近彻底转到Chrome了
不知道有没有办法随着Chrome启动和关闭
或者在配置文件里加一个Daemon和Faceless选项了？
感觉这样在Chrome下的体验会好很多

**Comment by sequencer** [comment]
刚刚想到个方法是在`inject.js`插入
`window.location.assign('bl://open_without_gui');`
不过看到在`8c14914c8d`这个版本中也是这样做的
不知道为什么取消了？
另外感觉可以加入一个`bl://quit`
在所有bilibili的都关闭后退出程序／

**Comment by typcn** [comment]
这个没有取消啊，还是可以用的

**Comment by typcn** [comment]
在扩展的设置里面勾选- 未启动时自动静默打开，即可

**Comment by sequencer** [comment]
哦哦哦 看到了 
Chrome的UI之前对中文是奇怪的乱码
另外`open_without_gui `这个选项打开的时候有没有必要设置到`LSBackgroundOnly `的后台模式了？

**Comment by typcn** [comment]
这个没有测试过... open without gui 是没有任何窗口，但是会显示任务栏
