### ISSUE TITLE
番剧解析失败

### ISSUE THREAD

**Issue by EEEEElio** [typcn/bilibili-mac-client#377]
如题，所有的官方番剧都看不了了

**Comment by typcn** [comment]
您好，我已经在云端进行热修复，请尝试重新启动软件几次，然后试试能否正常观看

请确认可以正常访问以下地址 https://static-ssl.tycdn.net/updates/bilimac.js

如果还是不行，请查看 Console.app 中的 system.log 并上传

**Comment by typcn** [comment]
最近事情非常多，我大概在29号可以闲下来，到时候会发布更新补丁完全修复

**Comment by EEEEElio** [comment]
还是不行～
[system.log.zip](https://github.com/typcn/bilibili-mac-client/files/675170/system.log.zip)

**Comment by typcn** [comment]
刚上飞机...到老家回去更新下...

**Comment by typcn** [comment]
请更新到 2.49 再试下？

**Comment by ariour** [comment]
地址链接以bangumi开头的的确是看不了，升级了似乎也不行

**Comment by typcn** [comment]
如果您在海外，请打开 IP 伪造

遇到问题建议先阅读“常见问题”

**Comment by ariour** [comment]
我一直都是开着ip伪造的，4个ip都不行。这里的bangumi不是番剧的视频，而是电影区上传的视频。
例如：http://bangumi.bilibili.com/movie/11810

**Comment by typcn** [comment]
movie 都是走的那个收费版接口吧..
bangumi 那个 api
这个暂时没做...有时间逆yix

**Comment by typcn** [comment]
太简单了逆出来了..不过限制是破解不了的，最近事情非常多..大概年前后更新下

**Comment by ariour** [comment]
感谢感谢~

**Comment by typcn** [comment]
Should fixed in 2.51

测试通道可直接更新使用，正式通道明天更新
