### ISSUE TITLE
跟新2.49后无法解析

### ISSUE THREAD

**Issue by cogitoxin** [typcn/bilibili-mac-client#380]
Macbook sierra 10.12.2 更新2.49后无法播放任何视频，持续报错：bilibili API JSON Error
卸载重装2.48后依旧报错，之前一直运行正常。
在另一台系统为EI captain的Macbook在同一网络下运行2.49完全正常，软件所有设置都一样。
请问如何解决？

**Comment by typcn** [comment]
请查看日志，尝试更换 DNS 服务器，清除缓存等

**Comment by cogitoxin** [comment]
可以了，谢谢！
