### ISSUE TITLE
dailymotion，百度云，爱奇艺无法播放

### ISSUE THREAD

**Issue by qhzhang87** [typcn/bilibili-mac-client#381]
爱奇艺，百度云是显示解析失败，这两个是一直都没有播放成功过
dailymotion是会弹出小窗，然后小窗显示”playback finished，please close the window“，又自己关闭了，之前几个月还挺好用的，最近就一直播放不了了

**Comment by HomlesZhao** [comment]
请问直接用跳出来的chrome来访问爱奇艺播放？我这里提示需要flash

**Comment by typcn** [comment]
请发一下日志？

**Comment by typcn** [comment]
打开 Console.app ，点击 system.log

**Comment by qhzhang87** [comment]
dailymotion：
1/3/17 3:29:05.016 PM	Bilibili[57374]	[VP_YouGet] YouGet-URL: http://www.dailymotion.com/cdn/manifest/video/x571a81.m3u8?auth=1483658933-2562-c3n4kk2b-2c8d63ec6d8197caf890a17417b0d69a&include=720
1/3/17 3:29:05.029 PM	Bilibili[57374]	[PlayerView] Starting load video
1/3/17 3:29:05.029 PM	Bilibili[57374]	[PlayerView] Reading video info
1/3/17 3:29:05.032 PM	Bilibili[57374]	[PlayerView] X: 531.000000 Y: 105.000000 Width: 601.000000 Height: 362.000000
1/3/17 3:29:05.038 PM	Bilibili[57374]	[PlayerManager] Create player 982004878
1/3/17 3:29:06.198 PM	Bilibili[57374]	[ffmpeg] warn: http: HTTP error 403 Forbidden
1/3/17 3:29:06.198 PM	Bilibili[57374]	[lavf] error: avformat_open_input() failed
1/3/17 3:29:06.251 PM	Bilibili[57374]	[ffmpeg] warn: http: HTTP error 403 Forbidden
1/3/17 3:29:06.252 PM	Bilibili[57374]	[stream] error: Failed to open http://proxy-20.sv6.dailymotion.com/sec(2fb216314a044e88e0f1f8cc6ded13af)/video/790/841/314148097_mp4_h264_aac_hd.m3u8#cell=sv6&hls_maxSeekHole=4&ab_heuristic=1&hls_startFragPrefetch=1&hls_maxLoadingDelay=5&hls_levelLoadingMaxRetry=2&hls_levelLoadingTimeOut=30000&hls_fragLoadingMaxRetry=2.
1/3/17 3:29:06.290 PM	Bilibili[57374]	[ffmpeg] warn: http: HTTP error 403 Forbidden
1/3/17 3:29:06.290 PM	Bilibili[57374]	[stream] error: Failed to open http://proxy-21.sv6.dailymotion.com/sec(2fb216314a044e88e0f1f8cc6ded13af)/video/790/841/314148097_mp4_h264_aac_hd.m3u8#cell=sv6&hls_maxSeekHole=4&ab_heuristic=1&hls_startFragPrefetch=1&hls_maxLoadingDelay=5&hls_levelLoadingMaxRetry=2&hls_levelLoadingTimeOut=30000&hls_fragLoadingMaxRetry=2.
1/3/17 3:29:06.325 PM	Bilibili[57374]	[PlayerWindow] Closing Window
1/3/17 3:29:06.325 PM	Bilibili[57374]	[PlayerWindow] Destroy player
1/3/17 3:29:06.380 PM	Bilibili[57374]	[PlayerManager] Removed player 982004878
1/3/17 3:29:06.381 PM	Bilibili[57374]	[Player] Dealloc player <Player: 0x7fa483df4010>
1/3/17 3:29:06.482 PM	Bilibili[57374]	[PlayerWindow] Dealloc
1/3/17 3:29:06.484 PM	Bilibili[57374]	[PlayerView] Dealloc
1/3/17 3:29:06.614 PM	Bilibili[57374]	[PlayerControl] Dealloc
1/3/17 3:29:15.835 PM	Bilibili[57374]	[WebTabView] Leaving tab 3588 , set status to 0.
1/3/17 3:29:15.838 PM	Bilibili[57374]	[WebTabView] Leaving tab 3588 , set status to 0.
1/3/17 3:29:15.843 PM	Bilibili[57374]	[WebTabView] Leaving tab 3588 , set status to 0.
1/3/17 3:29:16.635 PM	Bilibili[57374]	[WebTabView] Leaving tab 3588 , set status to 0.
1/3/17 3:29:16.639 PM	Bilibili[57374]	[WebTabView] Leaving tab 3588 , set status to 0.
1/3/17 3:29:16.643 PM	Bilibili[57374]	[WebTabView] Leaving tab 3588 , set status to 0.
1/3/17 3:29:22.161 PM	Bilibili[57374]	[WebTabView] Leaving tab 3588 , set status to 0.
1/3/17 3:29:22.165 PM	Bilibili[57374]	[WebTabView] Leaving tab 3588 , set status to 0.
1/3/17 3:29:22.169 PM	Bilibili[57374]	[WebTabView] Leaving tab 3588 , set status to 0.

爱奇艺和百度云的话，点击播放之后都没有log生成，就是显示下图这个提示
![screen shot 2017-01-03 at 3 54 13 pm](https://cloud.githubusercontent.com/assets/10552628/21627468/f8704732-d1cc-11e6-9953-73ba1f691b72.png)

**Comment by typcn** [comment]
可能是失效了，等我有时间更新下 youget 包

**Comment by typcn** [comment]
youget 插件已经更新，请更新后再次尝试解析
