### ISSUE TITLE
海外无法解析正版新番

### ISSUE THREAD

**Issue by captainsure** [typcn/bilibili-mac-client#382]
<img width="1280" alt="2017-01-03 6 27 50" src="https://cloud.githubusercontent.com/assets/19553704/21603672/625eda68-d1e2-11e6-8227-536f9c49f726.png">
如图 坐标日本 b站视频无法进行播放 所有的版权物都是这样无法解析 跪求解决！T T

**Comment by typcn** [comment]
请设置打开伪造IP

**Comment by captainsure** [comment]
3Q!已解决！@ @
