### ISSUE TITLE
为什么打开只有清空并返回！

### ISSUE THREAD

**Issue by ivinsai** [typcn/bilibili-mac-client#384]
为什么打开只有清空并返回！没有像chrome一样打开上次关闭的吗？

**Comment by typcn** [comment]
点链接可以访问

**Comment by ivinsai** [comment]
是这样说，但是加入不小心按了Ctrl+Q 或者不小心Crash了，几个Tab一个个打开也是很痛苦的事情啊～

**Comment by typcn** [comment]
好吧...这个加个JS应该就行，我过年回去在搞...

**Comment by typcn** [comment]
已增加，清空 Webkit 缓存即可使用
