### ISSUE TITLE
请恢复 Webview 的网页缩放功能！！！

### ISSUE THREAD

**Issue by Waigo21** [typcn/bilibili-mac-client#386]
目前 Bilibili Mac 版本的网页禁止了缩放功能，字太小看起来很不方便。

事实上现在好多人都有不同程度的近视眼，都喜欢把字放大来看，我都是习惯将网页 zoom 150%以上。尤其是2k 以上分辨率的显示屏。
所以，恳请恢复内置 webview 的缩放功能。

谢谢！！！

**Comment by typcn** [comment]
Added in 2.51 , Update ETA: 4 Hours

**Comment by Waigo21** [comment]
谢谢开发者的工作！已经看到更新里有双指缩放功能。
但双指缩放还不够啊，很多人连外接显示器不使用触控板的。

请添加 Command + '+'/'-'  快捷键的缩放功能，以及在右上角的菜单添加 Zoom [-]100[+] 这样的菜单按钮项，跟 Chrome 原生的缩放一样。

谢谢！
