### ISSUE TITLE
是否能自动识别弹幕和字幕文件

### ISSUE THREAD

**Issue by otakustay** [typcn/bilibili-mac-client#389]
当弹幕和字幕文件名均与视频文件名相同，且与视频文件在同一目录下时，自动将对应的`.xml`和`.ass`文件作为弹幕和字幕加载

**Comment by typcn** [comment]
该功能早已加入，右键点击视频使用 bilimac 打开即可，您是否遇到了什么问题？日志中有显示么？

**Comment by otakustay** [comment]
非常感谢，我是cmd+o打开文件发现无效……
