### ISSUE TITLE
本地视频无法同时外挂字幕和弹幕

### ISSUE THREAD

**Issue by zhangzhun789** [typcn/bilibili-mac-client#39]
点击右下角的小方框，要么屏幕里只有字幕，要么只有弹幕，字幕和弹幕无法同时出现在屏幕里，望改进。

**Comment by typcn** [comment]
这个没有办法解决，得改播放器的很多代码

duplicate with #38

**Comment by typcn** [comment]
弹幕本身就是以字幕的形式挂上去的，想要改的话比较麻烦，倒也不是不可能

如果是 ASS 字幕就简单一些，Append 到弹幕里面即可，其他字幕得单独写转换程序

**Comment by zhangzhun789** [comment]
好吧，看来我只能不停的点右下角切换着看了😭

**Comment by zhangzhun789** [comment]
大部分都是ass字幕的，如果有可能的话，还希望下个版本改进一下。O(∩_∩)O谢谢

**Comment by typcn** [comment]
![image](https://cloud.githubusercontent.com/assets/8022103/7798100/0c820cee-0328-11e5-9cca-6b76e9846b16.png)

**Comment by typcn** [comment]
尝试合并了两个视频的 ass 和弹幕，成功了

**Comment by typcn** [comment]
稍等打包更新

**Comment by zhangzhun789** [comment]
辛苦了💦

发自我的 iPhone

**Comment by typcn** [comment]
resolved
