### ISSUE TITLE
mac版bilibili的应用一打开番剧很快就会转到空白页或显示错误，几乎看不了番剧。

### ISSUE THREAD

**Issue by 7sv7sv** [typcn/bilibili-mac-client#392]

**Comment by typcn** [comment]
请说明所在区域，使用的运营商
所有出现的错误截图和日志

**Comment by 7sv7sv** [comment]
悉尼，日志和运营商怎么看？

<img width="900" alt="003affe4-48ab-499e-bd66-7be800033fd1" src="https://cloud.githubusercontent.com/assets/26165183/23574609/348736be-00d4-11e7-973d-a8ae141520ae.png">

**Comment by typcn** [comment]
让我看下...您是否可以访问
https://static-ssl.tycdn.net/updates/bilimac.js

**Comment by 7sv7sv** [comment]
不能，全是乱码

**Comment by typcn** [comment]
... 这是代码，可以加在完整就行

**Comment by 7sv7sv** [comment]
那应该可以

**Comment by typcn** [comment]
等我晚上看看是不是b站页面变更...

**Comment by 7sv7sv** [comment]
查出什么问题了吗？

**Comment by typcn** [comment]
您好，已经推送云端更新进行修复，CDN 缓存大约在 10 分钟后更新完毕。
请您稍后重启客户端，并查看是否恢复正常。

**Comment by o2chan** [comment]
@typcn 之前我提了这个issue了，好像是这个版本才出现的，貌似只在bangumi.bilibili.com下的页面才出现，包括全集一览页面和每一话新番的页面，打开页面后过几秒跳转到空白页，虽然按返回就可以回来。。

**Comment by typcn** [comment]
我这里无论是直连还是挂代理都无法重现，能否给一下控制台日志和视频地址？

**Comment by 7sv7sv** [comment]
打开客户端并没有出现更新，问题还和原来一样。

**Comment by typcn** [comment]
已经尝试多次无法重现，请给出有问题的 URL，日志和异常情况

如果我听到“加载不了”，“打不开”就能修掉，那在发布更新之前也就修掉了。

**Comment by typcn** [comment]
@o2chan 抱歉之前很忙，你的 issue 没看到。。
原来是番剧列表页面。。。。 这个 issue 标题和描述让我不停的调试“番剧播放页面”
番剧列表页面的问题刚刚测试了一下，B站修改了版权限制的方式，导致拦截不到ajax请求就会失败，然后 bangumi 的替换脚本以为是播放页面于是做了跳转。

已经推送了新的脚本到云端，请您尝试退出并重新打开软件后再次尝试。

**Comment by o2chan** [comment]
@typcn 现在自动跳转的问题应该已经修复，不过新番的播放器加载不出来了，似乎刷新也无法解决（其他视频遇到播放器加载不出时刷新几次能出来）。可能还是这里的问题所以就不开新issue了

**Comment by typcn** [comment]
稍等

**Comment by typcn** [comment]
已修复
