### ISSUE TITLE
斗鱼解析失败，不能用了吗？还是 Bug？以前可以解析的。

### ISSUE THREAD

**Issue by A1saka** [typcn/bilibili-mac-client#393]
<img width="415" alt="screen shot 2017-03-08 at 7 28 18 pm" src="https://cloud.githubusercontent.com/assets/15502050/23702285/8ce8c368-0435-11e7-989a-e4bb0813bb7e.png">

**Comment by typcn** [comment]
请手动安装 youget ，设置改可执行文件路径
或者等我更新

**Comment by A1saka** [comment]
@typcn 好的，谢谢!!

**Comment by A1saka** [comment]
更新了插件还是不行，斗鱼不能播放。
<img width="332" alt="screen shot 2017-04-09 at 5 38 57 pm" src="https://cloud.githubusercontent.com/assets/15502050/24836327/b7af1ee2-1d4b-11e7-91ee-e4fb41b00680.png">

**Comment by A1saka** [comment]
<img width="384" alt="screen shot 2017-04-09 at 5 38 37 pm" src="https://cloud.githubusercontent.com/assets/15502050/24836337/f41dd9fe-1d4b-11e7-8fe0-070bdd194b19.png">

**Comment by typcn** [comment]
您好，请点击插件设置，然后在 youget 选项中加 -d 然后看看错误信息？

**Comment by JokerQyou** [comment]
这个我也遇到了，昨天在终端用最新版本的 you-get 手动解析测试的结果是跟[这个](https://github.com/soimort/you-get/issues/1720)可能有关系。

**Comment by typcn** [comment]
看样子是斗鱼改了算法，youget 还没跟进

大家可以帮忙移植一下斗鱼插件，最近累的要死....

**Comment by typcn** [comment]
Fixed in 2.52

**Comment by A1saka** [comment]
斗鱼2.52还是不行啊😭

**Comment by typcn** [comment]
Update you-get plugin

**Comment by A1saka** [comment]
发出来我就意识到这个问题了😂
谢谢百忙之中抽空解决！前段时间都不能用 Mac 看斗鱼。
捐赠一点表示感谢，不要嫌弃就好😊
