### ISSUE TITLE
百度云的播放功能又消失了

### ISSUE THREAD

**Issue by lzzzzx** [typcn/bilibili-mac-client#396]
## 基本信息
- 操作系统版本：Mac 10.12.1
- 所在国家：US
- 网络运营商：
- 软件版本：2.51

## 问题描述
百度云插件已更新到最新7。
百度云按照指示勾选文件，但是最上方没有出现播放视频的按钮。请修复！
辛苦了！！

**Comment by typcn** [comment]
您好，请尝试重启一下客户端，然后在百度页面多刷新几次试试？

**Comment by typcn** [comment]
Fixed in 2.52
