### ISSUE TITLE
工程build失败

### ISSUE THREAD

**Issue by lilthree** [typcn/bilibili-mac-client#397]
## 基本信息
- 操作系统版本：macOS 10.12.4
- 所在国家：中国
- 网络运营商：
- 软件版本：

## 问题描述

工程build失败

## 截图
macOS10.12.4下使用Xcode8.3build失败
![2017-04-11 3 52 27](https://cloud.githubusercontent.com/assets/16398987/24898787/9cd7f928-1ed0-11e7-987b-e930e1d569ee.png)

**Comment by typcn** [comment]
您好，请阅读：
https://github.com/typcn/bilibili-mac-client/blob/master/HOW_TO_BUILD.md
确保依赖库已安装完整
