### ISSUE TITLE
弹幕透明度调整

### ISSUE THREAD

**Issue by dimpurr** [typcn/bilibili-mac-client#4]
不支持透明弹幕的话，相当影响观看体验 …… 个人以为这个功能应该优先考虑。
其他的字体调整用空的话也可以考虑下吧。

**Comment by typcn** [comment]
因为弹幕是在播放开始前就作为字幕生成好的，动态改变不大可能，可以考虑在软件中单独做一个设置

**Comment by typcn** [comment]
已经加入，下次发布更新时将可用
