### ISSUE TITLE
问个关于mpv的问题

### ISSUE THREAD

**Issue by dxs9642** [typcn/bilibili-mac-client#40]
大神我又来问问题了，最近在搞那个啥libmpv，然后出现各种问题，大神如果有时间帮我解答下行吗

第一个问题是我用waf编译mpv，然后只出现了libmpv.dylib文件，实在没有找到其他的相关动态库，请问要用什么参数呢，下面是我用的参数
waf configure --enable-libmpv-shared
waf build --enable-libmpv-shared

然后第二个问题是，我把你的工程中的libmpv.dylib换成我编译出来哪个libmpv.dylib然后运行你的工程，虽然能播放，但是一旦暂停快进程序就会失去响应

大神有时间帮我解答这两个问题吗

**Comment by typcn** [comment]
./waf configure --enable-static-build --enable-libmpv-shared
./waf build

这样就可以编译了

编译完成之后 TOOLS 里面有个 dylib 什么的 py 脚本，用那个脚本就会自动帮你复制依赖项，libmpv.dylib 的文件夹中就会多出一个 libs 文件夹，里面就有所有的依赖库。

至于快进失去响应，这个应该是 mpv 的问题，如果是从 master 分支上 checkout 下来的很可能有 bug

**Comment by dxs9642** [comment]
那大神我该用哪个branch呢，cocoa？还是其他的呢

**Comment by typcn** [comment]
多试几个 commit 就行了吧。。

**Comment by dxs9642** [comment]
行，我去试试，大神谢谢了，明天我把能用的贴出来
