### ISSUE TITLE
Feature Request: 逐帧播放

### ISSUE THREAD

**Issue by apm1467** [typcn/bilibili-mac-client#400]
就是每次只往前放一帧的功能，很多时候方便截图，绅士们都懂。

（还是这个功能已经存在了，只是我试快捷键没试出来？）

**Comment by typcn** [comment]
常见问题： http://vp-hub.eqoe.cn/faq.html

"," 和 "." 逐帧播放

**Comment by apm1467** [comment]
我错了，向大佬低头。
