### ISSUE TITLE
功能建议：一键下载弹幕和视频

### ISSUE THREAD

**Issue by kehao95** [typcn/bilibili-mac-client#404]
现在的页面上分别有【下载视频】【下载弹幕】功能，希望有一键同时下载这两个的按键。

**Comment by o2chan** [comment]
选下载视频会同时下载弹幕的

**Comment by kehao95** [comment]
哦，这样啊。不过这个的确有点Confusing，建议改为【下载弹幕】和【下载弹幕+视频】
