### ISSUE TITLE
B站经常刷不出视频播放按钮

### ISSUE THREAD

**Issue by Cappuccino12** [typcn/bilibili-mac-client#405]
## 基本信息
- 操作系统版本：macOs Sierra 10.12.5 beta
- 所在国家：意大利
- 网络运营商：Tiscali
- 软件版本：ver. 2.51

## 问题描述
在打开b站网页的时候左下角出现“拦截了n处iFrame”。当n是1的时候能正常出现视频播放按钮，当n是3或者更大，网页视频播放器就无法显示。

## 截图
<img width="123" alt="schermata 2017-05-03 alle 23 17 03" src="https://cloud.githubusercontent.com/assets/9482667/25682414/61c92976-3058-11e7-8263-f473929ed914.png"> 拦截字样

![image](https://cloud.githubusercontent.com/assets/9482667/25682434/7b1526be-3058-11e7-9307-e5ccd0faa309.png)

**Comment by typcn** [comment]
收到，您可以先安装 Chrome 插件进行观看

**Comment by typcn** [comment]
您好，已经使用云端热修复进行更新，请您在 CDN 缓存更新后（ 通常 1-10 分钟），退出并重新打开客户端即可使用

**Comment by Cappuccino12** [comment]
万分感谢，已经用多个视频网页测试过。没有问题了。效率太高！
