### ISSUE TITLE
在国外有些剧集会版权限制解决失败

### ISSUE THREAD

**Issue by EEEEElio** [typcn/bilibili-mac-client#406]
## 基本信息
- 操作系统版本：10.12.4
- 所在国家：加拿大
- 网络运营商：
- 软件版本：2.51

## 问题描述
在国外有些剧集会版权限制解决失败。。。
## 截图
![2017-05-03 10 42 22](https://cloud.githubusercontent.com/assets/17145926/25689006/ca0058fe-3051-11e7-980a-fd3b0d371e40.jpg)

**Comment by typcn** [comment]
这通常是网络问题导致的，您可以尝试刷新或者更换网络环境

**Comment by apm1467** [comment]
这个有可能是 bug。打开视频页面的时候，有一瞬间视频框是可以点击播放的，那一瞬间过后视频框就会被自动替换成「正在解决版权限制」字样。如果趁那一瞬间点到了视频框，就会打开播放器正常播放。

这个情况我遇到过几次，但出现不稳定，是跟网络环境有关系，不太好调试。我怀疑是 JavaScript 做了多余的替换。

**Comment by Joshua1989** [comment]
我这个情况出现次数满多的，有时候得刷新一二十次，而且确实如楼上所说，刷新后页面先是看起来可以正常播放，然后被替换成「正在解决版权限制」
* 操作系统版本：10.12.4
* 所在国家：美国
* 网络运营商：Times Warner Cable
* 软件版本：2.51

**Comment by typcn** [comment]
![image](https://cloud.githubusercontent.com/assets/8022103/25770988/c1c09146-3276-11e7-9212-a7cb0e1ce0ac.png)

只有这样的返回才会进行替换啊。。。

**Comment by typcn** [comment]
我感觉有可能是请求顺序的问题，在B站版权限制API返回之前就已经完成了替换，返回之后被替换了

我更新了一下云端的 js，请等待大概 10 分钟后重启客户端再试

**Comment by apm1467** [comment]
我试了一下，现在应该是正常了。现在打开页面有一瞬间视频框是「正在解决版权限制」字样，然后就变成了正常可以点击播放的视频框。

我一开始就是遇到这个问题，然后看到[这个文件](https://github.com/typcn/bilibili-mac-client/blob/master/bilibili/WebPages/widget/widget.js#L58)想改一下看看效果，才来研究怎么 build 这个项目。然后发现我怎么改都没用，这个文件压根不会 build 进 app 里去……

**Comment by typcn** [comment]
是的。。。这个文件是在线下载的。。。。位置在

https://static-ssl.tycdn.net/updates/bilimac.js
