### ISSUE TITLE
1.9版本仍然无法同时外挂字幕和弹幕

### ISSUE THREAD

**Issue by zhangzhun789** [typcn/bilibili-mac-client#41]
有些视频右下角是2/2，但须切换字幕和弹幕；还有些视频右下角是1/1，字幕没有被加载，需手动拖入到视频框中，但也无法同时加载字幕和弹幕。
![2015-05-26 13 55 24](https://cloud.githubusercontent.com/assets/12595909/7806106/3d7d5574-03af-11e5-9670-e2eb9db0a104.png)
![2015-05-26 13 59 30](https://cloud.githubusercontent.com/assets/12595909/7806131/82ba7c52-03af-11e5-8daa-f441e8d1e6a7.png)
![2015-05-26 13 59 43](https://cloud.githubusercontent.com/assets/12595909/7806133/830cb21a-03af-11e5-93a2-a8d551037ca8.png)

**Comment by typcn** [comment]
是不是 UTF8 编码的标准 ASS 格式字幕？

**Comment by typcn** [comment]
试了下 GBK 编码的，确实识别不到， UTF 8 的可以正常显示

**Comment by typcn** [comment]
![image](https://cloud.githubusercontent.com/assets/8022103/7808776/3d926d92-03c8-11e5-8944-a4ee1e5d11e3.png)
首先把最后一个逗号后面的数字改成0
然后用 Sublime Text 或者其他文本编辑器，转换成 UTF8 编码

**Comment by zhangzhun789** [comment]
やりました!但是字体变得好小也没有颜色了o(╯□╰)o，不过已经知足了╰(￣▽￣)╮
![2015-05-26 17 16 12](https://cloud.githubusercontent.com/assets/12595909/7809551/d05327de-03cd-11e5-9d12-ff4a54dc71ef.png)

**Comment by typcn** [comment]
![image](https://cloud.githubusercontent.com/assets/8022103/7809696/b9126d04-03ce-11e5-9db7-01e448c6edca.png)
ASS 格式是这样的，可以编辑字幕来改变字体大小

**Comment by zhangzhun789** [comment]
感谢大神指点^_^

**Comment by zhangzhun789** [comment]
刚刚又试验了几次，说说结果：
1.Ecoding是否改为0都可以读出字幕来，但是字体是上面的那种小字体。
2.修改Fontsize数值只能在2/2这个画面（2/2画面没有弹幕只有原字幕）中改变字体大小，对1/2画面（1/2画面既有字幕也有弹幕）中的字幕（小字体）没有影响。
![2015-05-26 18 12 50](https://cloud.githubusercontent.com/assets/12595909/7810247/e1254d3a-03d2-11e5-859a-f0fd27826dc7.png)
![2015-05-26 18 12 58](https://cloud.githubusercontent.com/assets/12595909/7810248/e16e74ce-03d2-11e5-8b12-56cf9013c42d.png)

再次感谢，お疲れ様！

**Comment by typcn** [comment]
经过程序转换后的字幕都是在 /tmp 文件夹下的，打开 /tmp/LOCALVIDEO.ass 看看 style 是否正确复制了？

**Comment by zhangzhun789** [comment]
未修改前的字幕
![default](https://cloud.githubusercontent.com/assets/12595909/7811428/20c275d0-03dd-11e5-8f03-efa9d0d43c2c.png)

Encoding修改为0后，再把Fontsize翻倍，保存为UTF8
![fontsize utf8](https://cloud.githubusercontent.com/assets/12595909/7811446/48d4aaf2-03dd-11e5-8eb6-65e1a83512be.png)

经过Bilibili For Mac打开后，在Tmp下找到的转换字幕 发现Fontsize从22变为44了，但是实际视频中的字体还是小字体
![localvideo cminfo](https://cloud.githubusercontent.com/assets/12595909/7811461/72d997e0-03dd-11e5-8703-8b6e17066c26.png)

**Comment by typcn** [comment]
尝试修改字体名称为 STHeiti ？

**Comment by typcn** [comment]
等等，我发现了一个问题，我的程序只会复制最后一个 Style，你可以尝试删掉 OPTitle 这个 Style ，只保留 Default 的 Style 试一下，我会在下个版本尝试修复这个问题

**Comment by zhangzhun789** [comment]
嗯  O(∩_∩)O谢谢
