### ISSUE TITLE
百度云插件更新日期出错，不应该是还没到来的5.28

### ISSUE THREAD

**Issue by nasyxx** [typcn/bilibili-mac-client#410]
## 问题描述
百度云插件更新日期出错，不应该是还没到来的5.28🤦‍♂️
## 截图
<img width="324" alt="screen shot 2017-05-12 at 2 33 11 am" src="https://cloud.githubusercontent.com/assets/5007613/25965707/61777644-36bb-11e7-98ad-67590dc2b958.png">

**Comment by typcn** [comment]
手滑打错了。。。

**Comment by typcn** [comment]
Fixed
