### ISSUE TITLE
打开几乎所有视频或下载都显示网络连接中断

### ISSUE THREAD

**Issue by lcmuch** [typcn/bilibili-mac-client#411]
## 基本信息
- 操作系统版本：MAC OS 10.12.4
- 所在国家：US
- 网络运营商：
- 软件版本：2.52 Build 3338

## 问题描述
打开几乎所有视频都显示网络连接中断。有小部分即便可以打开，下载也无法成功。
Issue似乎是在24小时内突然出现的。

## 截图
错误代码：-1005

错误详情：网络连接已中断。

调试信息：Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={NSErrorFailingURLKey=http://bangumi.bilibili.com/anime/425?from=search&seid=11232269209537973830, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=The network connection was lost., _WKRecoveryAttempterErrorKey=, NSErrorFailingURLStringKey=http://bangumi.bilibili.com/anime/425?from=search&seid=11232269209537973830, NSUnderlyingError=0x60000005de20 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={_kCFStreamErrorCodeKey=-4, _kCFStreamErrorDomainKey=4}}, _kCFStreamErrorCodeKey=-4}

上不去网？点击左上角文件菜单，打开本地视频进行观看

**Comment by typcn** [comment]
b 站服务器炸了找 b 站客服啊
