### ISSUE TITLE
有没有想法做一下免流的协议分析？

### ISSUE THREAD

**Issue by sequencer** [typcn/bilibili-mac-client#414]
## 基本信息
- 操作系统版本：MacBook Air 2013 i7 10.12.5 Beta (16F71b)
- 所在国家：China
- 网络运营商：Telecom
- 软件版本：Latest

## 问题描述
关于小电视卡，我准备利用中间人做一个协议分析，这样的话如果有小电视卡的手机开热点的话，是可以使用免流功能的。我觉得这个需求还是挺大的。不知道有没有兴趣做，如果有的话我就搞我的卡做协议分析试试看。

**Comment by typcn** [comment]
早就分析过，结果忘记放哪了，简单回忆一下，可能有错：

具体就是客户端里面（应该是sdk）会生成一个签名函数，带一堆参数请求（似乎是写死）的 IP 地址获取一个内网的播放地址，播放器载入这个播放地址即可播放
关键的函数应该只有一个，不知道那个字符串是客户端拼接的还是激活的时候服务器给的，理论上可以使用 http stream 的 VPN
实现任意网站的免流，不确定是否有域名校验。

**Comment by sequencer** [comment]
感受了...
如果是有域名校验的话还是不要弄出来吧...
以免用烂...
