### ISSUE TITLE
播放本地视频时如何添加多个弹幕文件

### ISSUE THREAD

**Issue by JinQzzz** [typcn/bilibili-mac-client#416]
## 基本信息
- 操作系统版本：10.11.6
- 所在国家：China
- 软件版本：2.52

## 问题描述

播放本地视频时如何添加多个弹幕文件？在选择弹幕时只有单选。

**Comment by typcn** [comment]
您好，如果是分段视频，您可以多选视频文件，将视频文件合并，弹幕暂时不可以多选，您可以直接复制弹幕文件进行合并

**Comment by JinQzzz** [comment]
谢谢，我当时直接把弹幕都合并了，issue忘记关闭了。
