### ISSUE TITLE
播放恋爱时代第一集崩溃

### ISSUE THREAD

**Issue by guojiex** [typcn/bilibili-mac-client#42]
http://www.bilibili.com/video/av2184230/
用客户端播放恋爱时代第一集怎么样都会崩溃

**Comment by typcn** [comment]
![image](https://cloud.githubusercontent.com/assets/8022103/7811484/a69810fc-03dd-11e5-9640-ec305eda2385.png)

偶然？或者是 B 站在你所在区域的 CDN 有问题？

B 站的架构很不稳定，经常会有读取不了视频的问题，CDN 放在机房也没多少带宽。

你可以尝试开启 IP 伪造，选择或输入一个外省的 IP 试一下。

错误信息的前 30 行贴出来看一下，可以考虑增加视频 CDN 区域选择

**Comment by guojiex** [comment]
很奇怪我的客户端就第一集打开会崩溃（每次都会。。），第二集就不会
尝试了伪造一个山东的ip和一般设置里面的几个都不行


Process:               Bilibili [3946]
Path:                  /Applications/Bilibili.app/Contents/MacOS/Bilibili
Identifier:            com.typcn.Bilibili
Version:               1.9 (19)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Bilibili [3946]
User ID:               501

Date/Time:             2015-05-26 19:35:23.554 +0800
OS Version:            Mac OS X 10.10.3 (14D136)
Report Version:        11
Anonymous UUID:        3591498B-E6F4-E5F5-F5C7-31CE8A3433BE


Time Awake Since Boot: 40000 seconds

Crashed Thread:        16  Dispatch queue: mpv

Exception Type:        EXC_ARITHMETIC (SIGFPE)
Exception Codes:       EXC_I386_DIV (divide by zero)

Thread 0:: Dispatch queue: com.apple.root.user-interactive-qos
0   libsystem_kernel.dylib        	0x00007fff8da7e51a semaphore_wait_trap + 10
1   libsystem_platform.dylib      	0x00007fff98c2bc5b _os_semaphore_wait + 16
2   libdispatch.dylib             	0x00007fff94da217a dispatch_apply_f + 828
3   com.apple.vImage              	0x00007fff954a461c vPermuteChannels_ARGB8888_SSSE3 + 428
4   com.apple.CoreGraphics        	0x00007fff8cbe7076 CGSConvertABGR8888toRGBA8888 + 157
5   com.apple.CoreGraphics        	0x00007fff8cbe57c2 argb32_image + 5990
6   libRIP.A.dylib                	0x00007fff90343352 ripd_Mark + 294
7   libRIP.A.dylib                	0x00007fff90341c8c RIPLayerBltImage + 1146
8   libRIP.A.dylib                	0x00007fff903415e1 ripc_RenderImage + 265
9   libRIP.A.dylib                	0x00007fff90347e81 ripc_DrawWindowContents + 1851
10  com.apple.CoreGraphics        	0x00007fff8cc0a2e8 CGContextCopyWindowContentsToRect + 101
11  com.apple.HIToolbox           	0x00007fff96ab38bf CopyWindowImageRectToContext + 231
12  com.apple.HIToolbox           	0x00007fff96ab37b3 CopyWindowImageRect + 92
13  com.apple.HIToolbox           	0x00007fff96aabca3 HIMenuBarView::DrawSelf(short, __HIShape const*, CGContext*) + 609
14  com.apple.HIToolbox           	0x00007fff96aab914 HIMenuBarView::DrawWithoutCustomization(short, __HIShape const*, CGContext*) + 82
15  com.apple.HIToolbox           	0x00007fff96aab873 HIMenuBarView::DrawingDelegateHandler(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*) + 249
16  com.apple.HIToolbox           	0x00007fff96a8fb6c DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 1260
17  com.apple.HIToolbox           	0x00007fff96a8efae SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 386
18  com.apple.HIToolbox           	0x00007fff96a8ee22 SendEventToEventTargetWithOptions + 43
19  com.apple.HIToolbox           	0x00007fff96aab3b9 HIView::SendDraw(short, OpaqueGrafPtr*, __HIShape const*, CGContext*) + 337
20  com.apple.HIToolbox           	0x00007fff96aaad42 HIView::RecursiveDrawComposited(__HIShape const*, __HIShape const*, unsigned int, HIView*, CGContext*, unsigned char, double) + 710
21  com.apple.HIToolbox           	0x00007fff96aaafbe HIView::RecursiveDrawComposited(__HIShape const*, __HIShape const*, unsigned int, HIView*, CGContext*, unsigned char, double) + 1346
22  com.apple.HIToolbox           	0x00007fff96aa9cdb HIView::DrawComposited(short, OpaqueGrafPtr*, __HIShape const*, unsigned int, HIView*, CGContext*) + 965
23  com.apple.HIToolbox           	0x00007fff96aa9904 HIView::Render(unsigned int, CGContext*) + 54
24  com.apple.HIToolbox           	0x00007fff96ab7a7c FlushWindowObject(WindowData*, void**, unsigned char) + 763
25  com.apple.HIToolbox           	0x00007fff96ac1114 FlushAllBuffers(__CFRunLoopObserver*, unsigned long, void*) + 228
26  com.apple.CoreFoundation      	0x00007fff94665127 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
27  com.apple.CoreFoundation      	0x00007fff94665080 __CFRunLoopDoObservers + 368
28  com.apple.CoreFoundation      	0x00007fff946572ba __CFRunLoopRun + 1178
29  com.apple.CoreFoundation      	0x00007fff94656bd8 CFRunLoopRunSpecific + 296
30  com.apple.HIToolbox           	0x00007fff96ab956f RunCurrentEventLoopInMode + 235
31  com.apple.HIToolbox           	0x00007fff96ab92ea ReceiveNextEventCommon + 431
32  com.apple.HIToolbox           	0x00007fff96ab912b _BlockUntilNextEventMatchingListInModeWithFilter + 71
33  com.apple.AppKit              	0x00007fff903ed9bb _DPSNextEvent + 978
34  com.apple.AppKit              	0x00007fff903ecf68 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
35  com.apple.AppKit              	0x00007fff903e2bf3 -[NSApplication run] + 594
36  com.apple.AppKit              	0x00007fff9035f354 NSApplicationMain + 1832
37  libdyld.dylib                 	0x00007fff963c35c9 start + 1

Thread 1:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib        	0x00007fff8da84232 kevent64 + 10
1   libdispatch.dylib             	0x00007fff94d99a6a _dispatch_mgr_thread + 52

Thread 2:: Dispatch queue: com.apple.root.user-interactive-qos
0   libsystem_kernel.dylib        	0x00007fff8da7e4f6 semaphore_signal_trap + 10
1   libsystem_platform.dylib      	0x00007fff98c2bc76 _os_semaphore_signal + 9
2   libdispatch.dylib             	0x00007fff94da22cc _dispatch_apply_invoke + 144
3   libdispatch.dylib             	0x00007fff94d96c13 _dispatch_client_callout + 8
4   libdispatch.dylib             	0x00007fff94d9988f _dispatch_root_queue_drain + 935
5   libdispatch.dylib             	0x00007fff94da7fe4 _dispatch_worker_thread3 + 91
6   libsystem_pthread.dylib       	0x00007fff96207637 _pthread_wqthread + 729
7   libsystem_pthread.dylib       	0x00007fff9620540d start_wqthread + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff8da8394a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff9620540d start_wqthread + 13

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff8da8394a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff9620540d start_wqthread + 13

**Comment by typcn** [comment]
应该是视频获取的问题，我会加个选择播放地址的选项
