### ISSUE TITLE
无规律出现空白页，视频加载失败

### ISSUE THREAD

**Issue by StarDuster** [typcn/bilibili-mac-client#421]
已在 TG 告知，截图留底

![photo_2017-06-25_08-43-17.jpg](https://ooo.0o0.ooo/2017/06/25/594f07ad7dade.jpg)

**Comment by typcn** [comment]
您好，服务器已经恢复，如果依然有问题，请确认可以正常访问以下链接

https://static-ssl.tycdn.net/updates/bilimac.js

您也可以在设置 -- 工具中清空缓存
