### ISSUE TITLE
部分页面自动跳转为空白页

### ISSUE THREAD

**Issue by coderstory** [typcn/bilibili-mac-client#422]
## 基本信息
- 操作系统版本： osx 10.11
- 所在国家： 中国
- 网络运营商： 移动
- 软件版本： 2.52 3388

## 问题描述
部分页面打开后，等待几秒后自动跳转[空白页面](about:blank)
测试方法：打开bilibili主页，在首页顶部的推广中选择[开封奇第6话](http://bangumi.bilibili.com/anime/6014)，会在新标签页中打开
                这个时候，等待几秒 url会变成about:blank 页面空间

**Comment by typcn** [comment]
您好，服务器已经恢复，如果依然有问题，请确认可以正常访问以下链接

https://static-ssl.tycdn.net/updates/bilimac.js

您也可以在设置 -- 工具中清空缓存
