### ISSUE TITLE
切换p失效

### ISSUE THREAD

**Issue by AlinJiang** [typcn/bilibili-mac-client#424]
## 基本信息
- 操作系统版本：10.12.5
- 所在国家：
- 网络运营商：
- 软件版本：

## 问题描述
切换p失效，在播放多p的视频的时候，无法自动切换到下一p
同时手动点击其他分p不会自动刷新和加载，必须要手动刷新
## 截图
![image](https://user-images.githubusercontent.com/17582007/28100449-c24444c4-6687-11e7-9fc0-48861240fe4a.png)
选项打开了自动换p，播放完之后直接退出而不是自动加载下一p
手动点了第2p之后
![image](https://user-images.githubusercontent.com/17582007/28100460-d38c164e-6687-11e7-8e34-31d924d69892.png)
不会自动加载第2p  需要手动刷新
手动刷新之后
![image](https://user-images.githubusercontent.com/17582007/28100513-16e18780-6688-11e7-8851-7d8977034905.png)

**Comment by typcn** [comment]
b 站更新了页面...周末更新

**Comment by AlinJiang** [comment]
估计也是这个问题，谢谢回复啦

**Comment by typcn** [comment]
您好，该问题已经云端推送修复，请您尝试退出并重新打开软件（最多 2 次）即可正常使用。

**Comment by AlinJiang** [comment]
能切换了但是好像自动连播还是不能用

**Comment by typcn** [comment]
自动连播热更新比较麻烦..等我下次发布更新软件
