### ISSUE TITLE
Airplay tv端返回 ffffd8f0 文件不支持错误

### ISSUE THREAD

**Issue by j84lee** [typcn/bilibili-mac-client#425]
## 基本信息
- 操作系统版本：MacOS 10.12.5
- 所在国家：
- 网络运营商：
- 软件版本：2.52

## 问题描述
AirPlay推送到Shield TV中安装的AirPlay/DLNA Receiver (PRO). shieldTV报错,显示"Built-in firmware player in your device does't support this format, Error Code: ffffd8f0-0"

**Comment by typcn** [comment]
您好，由于 B 站不再对高清视频提供 MP4 格式，请您尝试在设置中更换画质
