### ISSUE TITLE
Preference界面显示问题

### ISSUE THREAD

**Issue by Mihaly-Ma** [typcn/bilibili-mac-client#427]
## 基本信息
- 操作系统版本：macOS 10.13 Beta (17A306f)
- 所在国家：中国
- 网络运营商：电信
- 软件版本：Version 2.52(Build 3388)

## 问题描述
Preference界面显示不全。不知道是不是新系统的锅。
## 截图
<img width="612" alt="screen shot 2017-07-26 at 11 13 00" src="https://user-images.githubusercontent.com/15869242/28602974-dd72e3ae-7186-11e7-9a60-b718dab1078f.png">

**Comment by typcn** [comment]
Fixed in https://github.com/typcn/bilibili-mac-client/commit/2b60bf9773ff26b4ec6ecb217dae50388d47416d

10.13 里，一旦将窗口的 Resize 按钮隐藏掉，则整个窗口都无法 resize 了，不仅用户无法 resize，通过代码修改 size 都没卵用，只能让它显示了。
