### ISSUE TITLE
最近不少番剧无法下载了

### ISSUE THREAD

**Issue by Joshua1989** [typcn/bilibili-mac-client#429]
## 基本信息
- 操作系统版本：MacOS 10.12.6
- 所在国家：美国
- 网络运营商：TWC
- 软件版本：2.52

## 问题描述
从上周三开始有些番剧下载就parse不出来了，terminal输出如下图，直接观看没有什么问题
奇怪的是完全找不出规律，比如最新的终物语前两集不能下但是第三集可以

## 截图

![image](https://user-images.githubusercontent.com/1357342/29252433-37d03e70-8035-11e7-975c-2ba5fb8b66cf.png)

**Comment by typcn** [comment]
很是奇怪，你复制 app.bilibili.com 那行到浏览器里面访问看看结果？

**Comment by Joshua1989** [comment]
复制 app.bilibili.com 那行到浏览器里面访问返回的是
`{"code":-5009,"message":"video is hidden"}`

**Comment by matthew-z** [comment]
同上，最近新出的几集都不能下载了

**Comment by typcn** [comment]
为什么会这样呢...... 下载和播放都是调用的同一个模块里的同一个函数啊.....

**Comment by typcn** [comment]
大家能否提供下更多的日志样本？...

**Comment by matthew-z** [comment]
这样可以吗 @typcn 



default	17:59:37.265602 +0900	Bilibili	[Downloader] init
default	17:59:37.268242 +0900	Bilibili	[Downloader] video name 骑士&魔法 : 第8话 Secret&Quest 番剧 bilibili 哔哩哔哩弹幕视频网
default	17:59:37.268347 +0900	Bilibili	[Downloader] New Task CID: 22257880
default	17:59:37.275273 +0900	Bilibili	TIC TCP Conn Start [76:0x618000192890]
default	17:59:37.275273 +0900	Bilibili	TIC TCP Conn Start [77:0x610000396310]
default	17:59:37.282354 +0900	Bilibili	TIC TCP Conn Event [76:0x618000192890]: 1 Err(0)
default	17:59:37.282378 +0900	Bilibili	TIC TCP Conn Connected [76:0x618000192890]: Err(0)
default	17:59:37.282488 +0900	Bilibili	TIC Enabling TLS [76:0x618000192890]
default	17:59:37.283372 +0900	Bilibili	TIC TCP Conn Event [77:0x610000396310]: 1 Err(0)
default	17:59:37.283397 +0900	Bilibili	TIC TCP Conn Connected [77:0x610000396310]: Err(0)
default	17:59:37.287857 +0900	Bilibili	TIC TLS Event [76:0x618000192890]: 2, Pending(0)
default	17:59:37.288020 +0900	Bilibili	TIC TLS Event [76:0x618000192890]: 20, Pending(0)
default	17:59:37.288585 +0900	Bilibili	TIC TCP Conn Event [76:0x618000192890]: 8 Err(0)
default	17:59:37.288617 +0900	Bilibili	TIC TLS Handshake Complete [76:0x618000192890]
default	17:59:37.290010 +0900	Bilibili	TIC TCP Conn Start [78:0x600000194770]
default	17:59:37.296796 +0900	Bilibili	TIC TCP Conn Event [78:0x600000194770]: 1 Err(0)
default	17:59:37.296831 +0900	Bilibili	TIC TCP Conn Connected [78:0x600000194770]: Err(0)
default	17:59:37.296955 +0900	Bilibili	TIC Enabling TLS [78:0x600000194770]
default	17:59:37.303021 +0900	Bilibili	TIC TLS Event [78:0x600000194770]: 2, Pending(0)
default	17:59:37.303144 +0900	Bilibili	TIC TLS Event [78:0x600000194770]: 20, Pending(0)
default	17:59:37.303615 +0900	Bilibili	TIC TCP Conn Event [78:0x600000194770]: 8 Err(0)
default	17:59:37.303645 +0900	Bilibili	TIC TLS Handshake Complete [78:0x600000194770]
default	17:59:37.494941 +0900	Bilibili	[Downloader] Comment downloaded
default	17:59:37.495021 +0900	Bilibili	[VP_Bilibili] Getting video url
default	17:59:37.495073 +0900	Bilibili	[VP_Bilibili] AV: 0, CID: 22257880, PID: 1
default	17:59:37.495246 +0900	Bilibili	[VP_Bilibili] API Request URL: http://www.bilibili.com/m/html5?aid=0&page=1
default	17:59:37.495310 +0900	Bilibili	[VP_Bilibili] Using dynamic parser
default	17:59:37.495459 +0900	Bilibili	[Bilibili Dynamic Parser] Using android v2 parser
default	17:59:37.495514 +0900	Bilibili	[Bilibili Dynamic Parser] Fake IP detected, checking region
default	17:59:37.495878 +0900	Bilibili	TIC TCP Conn Start [79:0x618000193f50]
default	17:59:37.496170 +0900	Bilibili	TIC TCP Conn Start [80:0x618000194500]
default	17:59:37.504507 +0900	Bilibili	TIC TCP Conn Event [79:0x618000193f50]: 1 Err(0)
default	17:59:37.504548 +0900	Bilibili	TIC TCP Conn Connected [79:0x618000193f50]: Err(0)
default	17:59:37.505260 +0900	Bilibili	TIC TCP Conn Event [80:0x618000194500]: 1 Err(0)
default	17:59:37.505291 +0900	Bilibili	TIC TCP Conn Connected [80:0x618000194500]: Err(0)
default	17:59:37.511680 +0900	Bilibili	[Bilibili Dynamic Parser] Sign params: appkey=iVGUTjsxvpLeuDCf&build=503000&buvid=81A162FC-CCFF-4D26-A33A-D7D9834362EE28297infoc&cid=22257880&device=android&otype=json&platform=android&quality=4HIDDEN_APPSECRET
default	17:59:37.511797 +0900	Bilibili	[Bilibili Dynamic Parser] APIURL https://app.bilibili.com/playurl?otype=json&platform=android&device=android&appkey=iVGUTjsxvpLeuDCf&cid=22257880&build=503000&quality=4&buvid=81A162FC-CCFF-4D26-A33A-D7D9834362EE28297infoc&sign=1b1c2ef1b7ad64237efb79016ee40be6
default	17:59:37.512697 +0900	Bilibili	TIC TCP Conn Start [81:0x6100001870f0]
default	17:59:37.519483 +0900	Bilibili	TIC TCP Conn Event [81:0x6100001870f0]: 1 Err(0)
default	17:59:37.519517 +0900	Bilibili	TIC TCP Conn Connected [81:0x6100001870f0]: Err(0)
default	17:59:37.519625 +0900	Bilibili	TIC Enabling TLS [81:0x6100001870f0]
default	17:59:37.525442 +0900	Bilibili	TIC TLS Event [81:0x6100001870f0]: 2, Pending(0)
default	17:59:37.525536 +0900	Bilibili	TIC TLS Event [81:0x6100001870f0]: 20, Pending(0)
default	17:59:37.526019 +0900	Bilibili	TIC TCP Conn Event [81:0x6100001870f0]: 8 Err(0)
default	17:59:37.526040 +0900	Bilibili	TIC TLS Handshake Complete [81:0x6100001870f0]
default	17:59:37.716277 +0900	Bilibili	[Bilibili Dynamic Parser] Android Parser V2 failed
default	17:59:37.716421 +0900	Bilibili	[Bilibili Dynamic Parser] Using android parser
default	17:59:37.716472 +0900	Bilibili	[Bilibili Dynamic Parser] Fake IP detected, checking region
default	17:59:37.722770 +0900	Bilibili	TIC TCP Conn Start [82:0x600000185fe0]
default	17:59:37.729855 +0900	Bilibili	TIC TCP Conn Event [82:0x600000185fe0]: 1 Err(0)
default	17:59:37.729886 +0900	Bilibili	TIC TCP Conn Connected [82:0x600000185fe0]: Err(0)
default	17:59:37.735705 +0900	Bilibili	[Bilibili Dynamic Parser] Server ts: 1503363572 , Hour: 9
default	17:59:37.735796 +0900	Bilibili	[Bilibili Dynamic Parser] tvboxm: 34353264333935386630343863303261
default	17:59:37.735875 +0900	Bilibili	[Bilibili Dynamic Parser] APPKEY: 452d3958f048c02a
default	17:59:37.735950 +0900	Bilibili	[Bilibili Dynamic Parser] Sign params: _aid=0&_appver=427000&_buvid=81A162FC-CCFF-4D26-A33A-D7D9834362EE28297infoc&_device=android&_down=0&_hwid=50e88b77ff7470cd&_p=1&_tid=0&appkey=452d3958f048c02a&cid=22257880&otype=json&platform=android&quality=4HIDDEN_APPSECRET
default	17:59:37.736033 +0900	Bilibili	[Bilibili Dynamic Parser] APIURL http://interface.bilibili.com/playurl?platform=android&_appver=427000&_buvid=81A162FC-CCFF-4D26-A33A-D7D9834362EE28297infoc&_device=android&_hwid=50e88b77ff7470cd&_aid=0&_tid=0&_p=1&_down=0&cid=22257880&quality=4&otype=json&appkey=452d3958f048c02a&sign=3597d4c00d11586ab113ef10043d2b0a
default	17:59:37.834161 +0900	Bilibili	[Bilibili Dynamic Parser] Android Parser failed
default	17:59:37.834251 +0900	Bilibili	[Bilibili Dynamic Parser] Using FLVCD parser
default	17:59:37.834313 +0900	Bilibili	[Bilibili Dynamic Parser] APIURL http://www.flvcd.com/parse.php?kw=http://www.bilibili.com/video/av0/index_1.html&flag=one&format=super
default	17:59:37.834950 +0900	Bilibili	TIC TCP Conn Start [83:0x618000194360]
default	17:59:39.440249 +0900	Bilibili	TIC TCP Conn Event [83:0x618000194360]: 1 Err(0)
default	17:59:39.440286 +0900	Bilibili	TIC TCP Conn Connected [83:0x618000194360]: Err(0)
default	17:59:39.624599 +0900	Bilibili	[Bilibili Dynamic Parser] Using WP parser
default	17:59:39.624731 +0900	Bilibili	[Bilibili Dynamic Parser] APIURL http://interface.bilibili.com/playurl?platform=android&cid=22257880&quality=4&otype=json&appkey=422fd9d7289a1dd9&type=flv&rnd=5301&sign=06ac8a6302a83ffb831d6aedcf674e29
default	17:59:39.747177 +0900	Bilibili	[Bilibili Dynamic Parser] WinPhone Parser Failed
default	17:59:39.747271 +0900	Bilibili	[Bilibili Dynamic Parser] Using BiliHelper parser
default	17:59:39.747340 +0900	Bilibili	[Bilibili Dynamic Parser] APIURL http://interface.bilibili.com/playurl?platform=bilihelper&otype=json&appkey=95acd7f6cc3392f3&cid=22257880&quality=4&type=flv
default	17:59:39.851527 +0900	Bilibili	[Bilibili Dynamic Parser] BiliHelper Parser Failed
default	17:59:39.851632 +0900	Bilibili	[Bilibili Dynamic Parser] All parser failed , return error video
default	17:59:39.851744 +0900	Bilibili	[VP_Bilibili] Dynamic parse success
default	17:59:39.851790 +0900	Bilibili	[VP_Bilibili] Parsing result
default	17:59:39.851827 +0900	Bilibili	[VP_Bilibili] Retring resolve with FLV format
default	17:59:39.851866 +0900	Bilibili	[VP_Bilibili] Getting video url
default	17:59:39.851915 +0900	Bilibili	[VP_Bilibili] AV: 0, CID: 22257880, PID: 1
default	17:59:39.852068 +0900	Bilibili	[VP_Bilibili] API Request URL: http://www.bilibili.com/m/html5?aid=0&page=1
default	17:59:39.852138 +0900	Bilibili	[VP_Bilibili] Using dynamic parser
default	17:59:39.852332 +0900	Bilibili	[Bilibili Dynamic Parser] Using android v2 parser
default	17:59:39.852388 +0900	Bilibili	[Bilibili Dynamic Parser] Fake IP detected, checking region
default	17:59:39.857893 +0900	Bilibili	[Bilibili Dynamic Parser] Sign params: appkey=iVGUTjsxvpLeuDCf&build=503000&buvid=81A162FC-CCFF-4D26-A33A-D7D9834362EE28297infoc&cid=22257880&device=android&otype=json&platform=android&quality=4HIDDEN_APPSECRET
default	17:59:39.858011 +0900	Bilibili	[Bilibili Dynamic Parser] APIURL https://app.bilibili.com/playurl?otype=json&platform=android&device=android&appkey=iVGUTjsxvpLeuDCf&cid=22257880&build=503000&quality=4&buvid=81A162FC-CCFF-4D26-A33A-D7D9834362EE28297infoc&sign=1b1c2ef1b7ad64237efb79016ee40be6
default	17:59:40.001729 +0900	Bilibili	[Bilibili Dynamic Parser] Android Parser V2 failed
default	17:59:40.001871 +0900	Bilibili	[Bilibili Dynamic Parser] Using android parser
default	17:59:40.001930 +0900	Bilibili	[Bilibili Dynamic Parser] Fake IP detected, checking region
default	17:59:40.012771 +0900	Bilibili	[Bilibili Dynamic Parser] Server ts: 1503363577 , Hour: 9
default	17:59:40.012866 +0900	Bilibili	[Bilibili Dynamic Parser] tvboxm: 34353264333935386630343863303261
default	17:59:40.012938 +0900	Bilibili	[Bilibili Dynamic Parser] APPKEY: 452d3958f048c02a
default	17:59:40.013000 +0900	Bilibili	[Bilibili Dynamic Parser] Sign params: _aid=0&_appver=427000&_buvid=81A162FC-CCFF-4D26-A33A-D7D9834362EE28297infoc&_device=android&_down=0&_hwid=50e88b77ff7470cd&_p=1&_tid=0&appkey=452d3958f048c02a&cid=22257880&otype=json&platform=android&quality=4HIDDEN_APPSECRET
default	17:59:40.013104 +0900	Bilibili	[Bilibili Dynamic Parser] APIURL http://interface.bilibili.com/playurl?platform=android&_appver=427000&_buvid=81A162FC-CCFF-4D26-A33A-D7D9834362EE28297infoc&_device=android&_hwid=50e88b77ff7470cd&_aid=0&_tid=0&_p=1&_down=0&cid=22257880&quality=4&otype=json&appkey=452d3958f048c02a&sign=3597d4c00d11586ab113ef10043d2b0a
default	17:59:40.130615 +0900	Bilibili	[Bilibili Dynamic Parser] Android Parser failed
default	17:59:40.130698 +0900	Bilibili	[Bilibili Dynamic Parser] Using FLVCD parser
default	17:59:40.130751 +0900	Bilibili	[Bilibili Dynamic Parser] APIURL http://www.flvcd.com/parse.php?kw=http://www.bilibili.com/video/av0/index_1.html&flag=one&format=super
default	17:59:40.741962 +0900	Bilibili	[Bilibili Dynamic Parser] Using WP parser
default	17:59:40.742131 +0900	Bilibili	[Bilibili Dynamic Parser] APIURL http://interface.bilibili.com/playurl?platform=android&cid=22257880&quality=4&otype=json&appkey=422fd9d7289a1dd9&type=flv&rnd=5508&sign=4fb1512075c632ec214acac81201b5a9
default	17:59:41.805231 +0900	Bilibili	[Bilibili Dynamic Parser] WinPhone Parser Failed
default	17:59:41.805336 +0900	Bilibili	[Bilibili Dynamic Parser] Using BiliHelper parser
default	17:59:41.805415 +0900	Bilibili	[Bilibili Dynamic Parser] APIURL http://interface.bilibili.com/playurl?platform=bilihelper&otype=json&appkey=95acd7f6cc3392f3&cid=22257880&quality=4&type=flv
default	17:59:41.920000 +0900	Bilibili	[Bilibili Dynamic Parser] BiliHelper Parser Failed
default	17:59:41.920099 +0900	Bilibili	[Bilibili Dynamic Parser] All parser failed , return error video
default	17:59:41.920190 +0900	Bilibili	[VP_Bilibili] Dynamic parse success
default	17:59:41.920231 +0900	Bilibili	[VP_Bilibili] Parsing result
default	17:59:41.920827 +0900	Bilibili	TIC TCP Conn Start [84:0x618000194290]
default	17:59:41.923155 +0900	Bilibili	TIC TCP Conn Event [84:0x618000194290]: 1 Err(0)
default	17:59:41.923184 +0900	Bilibili	TIC TCP Conn Connected [84:0x618000194290]: Err(0)
default	17:59:41.924072 +0900	Bilibili	Download Task Added
default	17:59:41.924486 +0900	Bilibili	[Downloader] Download task added
default	17:59:42.484023 +0900	Bilibili	TIC TCP Conn Event [77:0x610000396310]: 2 Err(0)
default	17:59:42.484076 +0900	Bilibili	TIC TCP Conn Cancel [77:0x610000396310]
default	17:59:42.484128 +0900	Bilibili	TIC TCP Conn Destroyed [77:0x610000396310]
default	17:59:45.081744 +0900	Bilibili	TIC TCP Conn Event [82:0x600000185fe0]: 2 Err(0)
default	17:59:45.081827 +0900	Bilibili	TIC TCP Conn Cancel [82:0x600000185fe0]
default	17:59:45.081885 +0900	Bilibili	TIC TCP Conn Destroyed [82:0x600000185fe0]
default	17:59:46.925330 +0900	Bilibili	TIC TCP Conn Event [79:0x618000193f50]: 2 Err(0)
default	17:59:46.925402 +0900	Bilibili	TIC TCP Conn Cancel [79:0x618000193f50]
default	17:59:46.925455 +0900	Bilibili	TIC TCP Conn Destroyed [79:0x618000193f50]
default	17:59:50.816150 +0900	Bilibili	TIC TCP Conn Event [83:0x618000194360]: 2 Err(0)
default	17:59:50.816203 +0900	Bilibili	TIC TCP Conn Cancel [83:0x618000194360]
default	17:59:50.816288 +0900	Bilibili	TIC TCP Conn Destroyed [83:0x618000194360]
default	18:00:07.927511 +0900	Bilibili	TIC TCP Conn Cancel [76:0x618000192890]
default	18:00:07.927571 +0900	Bilibili	TIC TCP Conn Cancel [78:0x600000194770]
default	18:00:07.927578 +0900	Bilibili	TIC TCP Conn Destroyed [76:0x618000192890]
default	18:00:07.927622 +0900	Bilibili	TIC TCP Conn Destroyed [78:0x600000194770]
default	18:00:12.867990 +0900	Bilibili	TIC TCP Conn Event [84:0x618000194290]: 2 Err(0)
default	18:00:12.868047 +0900	Bilibili	TIC TCP Conn Cancel [84:0x618000194290]
default	18:00:12.868125 +0900	Bilibili	TIC TCP Conn Destroyed [84:0x618000194290]

**Comment by typcn** [comment]
您好，该问题已经使用云端补丁热修复，请您尝试退出软件，并重新打开。

**Comment by matthew-z** [comment]
谢谢！

**Comment by Joshua1989** [comment]
感谢！能问下这个问题出现的原因么

**Comment by typcn** [comment]
解析模块是靠判断 URL 中是否有 bangumi.bilibili.com 来判断使用 bangumi 的 API 还是使用 APP 的 API 进行解析的，因为下载功能没有传视频 URL 给解析模块，所以下载一律走了 APP 的解析，而播放正常。

B 站最近完全关闭了 APP 的 API 解析番剧的权限（video hidden），所以就导致失效。

**Comment by zhujun24** [comment]
请问一下 `{"code":-5009,"message":"video is hidden"}` 这种情况是怎么破解的呢？

**Comment by typcn** [comment]
视频隐藏，一般被管理员删了

**Comment by zhujun24** [comment]
怎样通过 bangumi.bilibili.com 的 API 解析番剧呢？有像 interface 解析那样的 key 么？或者怎么获取 key ？

**Comment by typcn** [comment]
逆客户端，F12抓JS，或者IDA看我的解析模块

**Comment by zhujun24** [comment]
看前端 JS 里面写了 ["interface.bilibili.com/playurl?","bangumi.bilibili.com/player/web_api/v2/playurl?","bangumi.bilibili.com/player/web_api/playurl?"]
大概有三种解析地址，目前后面两个还没有可用的 key
