### ISSUE TITLE
如果系统装有Flash 播放器自动调用Flash播放器

### ISSUE THREAD

**Issue by liujixincd** [typcn/bilibili-mac-client#43]
系统版本 10.10.3
播放器版本1.9

**Comment by typcn** [comment]
什么意思？没有完全屏蔽掉 Flash ？
这个稍微有点蛋疼，我想办法提前一下代码注入

**Comment by liujixincd** [comment]
就是说每次打开一个视频 一般是先有bilibili的flash播放器载入的画面（表明flash播放器已经载入了） 过一会才会切换到你的播放器（就是硬解的播放器）但刚才我甚至出现了打开一个视频 播放器没切换的情况

**Comment by typcn** [comment]
这是由于网页没加载完全的情况，可以右键，强制显示播放界面，或者暂时卸载掉自带的 flash

我想想办法直接拦截 flash

**Comment by liujixincd** [comment]
感谢回复

还有一个小问题是 字体的渲染有的地方至今还是有锯齿 虽然主页所有直接显示文字已经没有锯齿了 但下拉菜单还是有
如这种情况
![7135a163-3bcf-414d-8a5f-d126e184833c](https://cloud.githubusercontent.com/assets/6250655/7894794/26fa189a-0626-11e5-9583-6111c5c4d4dc.png)
更正一下 不是所有的界面都有这种情况 我的机器上是主页是这样 但有的视频页面点进去下拉菜单就是没问题的 很奇怪

**Comment by typcn** [comment]
这应该是 Safari 的 Bug 再加上 B 站那古老的 css 引发的问题

**Comment by typcn** [comment]
Safari 直接打开有这个问题么？试试 translate3d 归零？

**Comment by liujixincd** [comment]
Safari 直接打开没有问题 所有文字渲染正常 （btw，软件里面如果载入了flash播放器的话 可以发现flash 播放器是低dpi的 有点像firefox里面flash的样子 但我觉得应该是用的safari内核 应该是高dpi的啊）

**Comment by typcn** [comment]
擦，我外置屏幕 + 内置屏幕都没问题啊，下次更新加个 css hack 试试

**Comment by liujixincd** [comment]
麻烦了 不过现在的播放器已经很完美了 感谢！
