### ISSUE TITLE
百度网盘页面无法打开

### ISSUE THREAD

**Issue by ariour** [typcn/bilibili-mac-client#432]
## 基本信息
- 操作系统版本：macOs sierra 10.12.6
- 所在国家：日本
- 网络运营商：未知
- 软件版本：2.52

## 问题描述

点击主页，一直出去空白页面，并一直加载状态。大概两天前都还是正常，求排解问题。

**Comment by typcn** [comment]
您好，暂时没有时间更新，过几天修

**Comment by mttlxx** [comment]
我这边的情况是一打开百度网盘页面就自动刷新。百度云的这个插件有办法删除吗？我只是不小心点到的，尴尬。

**Comment by typcn** [comment]
您好，该问题已修复，请您尝试更新到 2.53 版本
