### ISSUE TITLE
不知道怎么下载 .....

### ISSUE THREAD

**Issue by Clearlove4** [typcn/bilibili-mac-client#435]
## 基本信息
- 操作系统版本：Mac OS 10.12
- 所在国家：中国
- 网络运营商：
- 软件版本：2.52

## 问题描述
 是我太笨了吗hhh，为什么无法下载呢，点击下载视频，解析视频的时候，就直接提示下载失败请点击帮助

**Comment by typcn** [comment]
您好，请您查看“常见问题”，如果没有解决，请提供日志（Console.app）
