### ISSUE TITLE
拖动窗口时进度条自动飞出去，而且窗口乱跳

### ISSUE THREAD

**Issue by RhodesZ** [typcn/bilibili-mac-client#439]
## 基本信息
- 操作系统版本：MacOS High Sierra 10.13
- 所在国家：US
- 网络运营商：wu... don't know
- 软件版本：2.53

## 问题描述
拖动播放器窗口时，窗口乱跳，进度条也会飞出去并且消失...

**Comment by xrain0610** [comment]
我也发现了这个问题, 进度条可以缩放窗口的时候重现
