### ISSUE TITLE
新安装的客户端软件不能正常打开包括插件中心、未关闭页面提示页在内的页面

### ISSUE THREAD

**Issue by scatoday** [typcn/bilibili-mac-client#441]
## 基本信息
- 操作系统版本：OS X El Capitan 10.11.6
- 所在国家：China
- 网络运营商：电信
- 软件版本：2.52 / 2.53

## 问题描述
新安装的客户端软件不能正常打开包括插件中心、未关闭页面提示页在内的站点，隶属于 http://vp-hub.eqoe.cn/ 站下的均提示您的请求带有不合法参数，已被网站管理员设置拦截！不能安装插件的话意味着 bilibili 站内的视频不能正常播放，对已安装过插件的用户影响不大
## 截图

<img width="621" alt="467ff1e5-cb52-445e-a310-ca3d56fe82f9" src="https://user-images.githubusercontent.com/32606008/31544365-121464ce-afe0-11e7-9407-94a426cd040a.png">

**Comment by typcn** [comment]
您好，本站没有安装任何防火墙，请确认您的网络环境正常。

**Comment by scatoday** [comment]
谢谢，已解决。
原因是浙江电信屏蔽了此网站，指向到了错误的网站。
暂时通过修改 Host 指向正确的 ip 地址解决。
