### ISSUE TITLE
无法打开视频观看页面 无法弹出窗口 提示API JSON错误

### ISSUE THREAD

**Issue by Estherstasia** [typcn/bilibili-mac-client#442]
## 基本信息
- 操作系统版本：macOS Sierra 10.12.6
- 所在国家：中国
- 网络运营商：无
- 软件版本：2.53

## 问题描述
无法打开视频观看页面 无法弹出窗口 提示BILIBILI API JSON Error

## 截图

![default](https://user-images.githubusercontent.com/32773995/31555152-8accb280-b072-11e7-9145-a5a84fa6e831.png)

**Comment by typcn** [comment]
请检查您的网络连接正常，可以连接到 https://app.bilibili.com

**Comment by Estherstasia** [comment]
网络可以正常连接 而且直播页面打得开 可以弹出播放窗口 但是观看视频不行

**Comment by Estherstasia** [comment]
换过多个Wi-Fi 都无法打开视频，但是直播页面可以观看

**Comment by typcn** [comment]
您好，经过测试，由于不可抗力的原因，云端解析模块在中国大陆境内的服务器被强制关闭，已经修改解析，请明天再试

**Comment by Estherstasia** [comment]
好的
