### ISSUE TITLE
没有改变播放速度的问题

### ISSUE THREAD

**Issue by number36cc** [typcn/bilibili-mac-client#446]
![44e6fcf4-cea0-4ace-82be-1b88cd1afcda](https://user-images.githubusercontent.com/31819514/32001432-6c38c70a-b95f-11e7-907c-6e435fa7d4d1.jpg)

## 基本信息
- 操作系统版本：High Sierra 10.13
- 所在国家：中国
- 网络运营商：移动
- 软件版本：2.52

## 问题描述
没有播放速度的相关设置么

**Comment by typcn** [comment]
您好，请您阅读：常见问题 http://vp-hub.eqoe.cn/faq.html
