### ISSUE TITLE
想请问一下有关弹幕内容查用户名的功能

### ISSUE THREAD

**Issue by staf97531** [typcn/bilibili-mac-client#447]
是这样子的
虽然有些弹幕查的到
不过常常会出现以下的讯息
![22](https://user-images.githubusercontent.com/33168740/32130435-fc4fd0f0-bbca-11e7-9fe1-c794e99b9e0b.png)
总不会是刚好用户真的被删除了吧
有些还是一两天前发的弹幕
而且用手机和电脑都会出现这个讯息

**Comment by typcn** [comment]
您好，由于数据不完整，新用户查不到，即将扩充数据。

**Comment by typcn** [comment]
已经增加到 3 亿数据
您也可以自行搭建服务器 https://github.com/typcn/biliquery_db
