### ISSUE TITLE
Debug模式下HTML5 API失败。Release模式触发反调试直接跳出

### ISSUE THREAD

**Issue by Naville** [typcn/bilibili-mac-client#448]
## 基本信息
- 操作系统版本：10.12.6
- 所在国家：UK
- 网络运营商：
- 软件版本：git

## 问题描述
    Debug 日志:https://gist.github.com/Naville/b7436c2689e996f1bbcd71666ba92246
## 截图
![ba5ab6b7-6e5b-45cf-a544-fa9345367a20](https://user-images.githubusercontent.com/5205699/32189381-7c477a46-bda2-11e7-98fd-af25b109df67.png)

搞macOS/iOS逆向的同学都已经很熟悉99%的反调试套路了，这除了增加正常开发者的麻烦以外没有任何用处

**Comment by Naville** [comment]
我的想法是希望能增加一个新的播放按钮。自动把窗口大小调整为屏幕的大约1/3,1/3 ，类似Safari的pip模式，而原来的播放维持行为不变。因为有时用户可能想全屏看有时用户可能在做别的事情只需要小窗口。每次都来回调整大小会比较麻烦
感谢

**Comment by typcn** [comment]
没必要，之前天天被b站日，迫不得已加的一行ptrace

**Comment by typcn** [comment]
1. 播放器会自动记住窗口的位置，按 F 就可以置顶了
2. 指的是增加一个禁止多开的选项么？

**Comment by Naville** [comment]
2.是的
