### ISSUE TITLE
播放视频时发热量和Chrome直接播放差不多

### ISSUE THREAD

**Issue by HatCloud** [typcn/bilibili-mac-client#45]
这样的话，感觉背离了这个应用的初衷了。

**Comment by typcn** [comment]
尝试开启 mp4 模式，部分视频是没法硬解的

**Comment by typcn** [comment]
还有这种莫名其妙的 issue , 只是发热，具体情况没有，视频没有，分辨率/码率没有， log 没有，截图没有，我怎么知道哪里写错了还是夏天天气太热呢。。。

**Comment by HatCloud** [comment]
不好意思，我的错。
我的电脑信息：MBPr 2013 Early i7 独显。

##具体情况：
几乎播放所有视频都特别能发热。
现在日常使用电脑温度基本都在**80°C**左右。看视频的时候会在**100°C**左右
下面是我播放今天首页上的[【新曲】真·操戈天下 (洛天依中文 PV附)](http://www.bilibili.com/video/av2414867/?tg)时的截屏。
中间“一般设定”的详细界面。右上角是CPU温度。

![_2015-06-09_ 9_29_51](https://cloud.githubusercontent.com/assets/7430550/8058899/334c9df8-0eef-11e5-8ed9-f210f06023f6.png)

抱歉的是Log我不会看

**Comment by HatCloud** [comment]
唔，我发现在这个界面的时候就开始发烫了，而且上传数据的速度很快，但最终什么也没加载出来。
注意截图右上角的网速和温度。
![2015-06-09 9 42 39](https://cloud.githubusercontent.com/assets/7430550/8059069/8a6bc568-0ef0-11e5-84b0-b321315db48e.png)

**Comment by typcn** [comment]
1. Intel Core CPU 最大温度是 72℃，这是华氏度么？
2. 上传协议速度大约有 90KB/s 左右，软件屏蔽了一切 P2P，没有任何超过 200KB/s 的可能性
