### ISSUE TITLE
插件无法安装，插件页面都无法显示出来

### ISSUE THREAD

**Issue by shenyunhuan** [typcn/bilibili-mac-client#452]
插件页面必须翻墙才能勉强显示，变一竖排，点击安装无反应
![image](https://user-images.githubusercontent.com/16234033/32977319-e4df97e2-cc65-11e7-8ccf-cfc844618991.png)

**Comment by shenyunhuan** [comment]
打开时连接服务器也不行

**Comment by shenyunhuan** [comment]
重启好几次后正常了

**Comment by exxfzc** [comment]
我想知道如何删除已经安装好的you-get插件,感觉这插件没啥用
