### ISSUE TITLE
打开视频后播放窗口右移

### ISSUE THREAD

**Issue by ariour** [typcn/bilibili-mac-client#453]
## 基本信息
- 操作系统版本：mac10.13.1
- 所在国家：日本
- 网络运营商：未知
- 软件版本：2.53

## 
大概一周前开始出现的问题，任何视频打开后都出现如下窗口右移状态，
如果向左拖动窗口，就会出现重影很难往左边拖动的那种效果（不知道能不能get）
就是，稍微往左动一下，窗口就乱跳。。
不知道是什么原因。求排查

##
<img width="1280" alt="2017-11-24 22 45 58" src="https://user-images.githubusercontent.com/19725111/33213102-72039d00-d169-11e7-82b3-a3433b866b70.png">

**Comment by typcn** [comment]
您好，请不要拖动窗口标题栏，拖动视频画面即可

**Comment by ariour** [comment]
原来这样。。。。。谢谢了
