### ISSUE TITLE
新版直播无法播放

### ISSUE THREAD

**Issue by specter119** [typcn/bilibili-mac-client#454]
## 基本信息
- 操作系统版本：macOS 10.13
- 所在国家：中国
- 网络运营商：教育网
- 软件版本：2.53(build 3497)

## 问题描述

新版直播无法播放

## 截图

![2017-11-28 16 55 49](https://user-images.githubusercontent.com/8768524/33310580-0530dca0-d45d-11e7-9a1e-f1e4963fae45.png)

**Comment by typcn** [comment]
您好，由于本人非常繁忙，预计下周前提供更新补丁。

**Comment by specter119** [comment]
@typcn 没有关系，十分感谢。

**Comment by typcn** [comment]
Hi

This issue has been fixed.
Please restart the app twice to finish hot update.

Thanks
