### ISSUE TITLE
番剧无法观看

### ISSUE THREAD

**Issue by strygwyr76** [typcn/bilibili-mac-client#456]
- 操作系统版本：macos high sierra 10.13.2
- 所在国家：中国
- 网络运营商：教育网
- 软件版本：2.53

## 问题描述
打开番剧播放界面为黑屏，无法进入播放器播放，另外视频可正常播放

## 截图
<img width="1280" alt="screen shot 2017-12-20 at 10 07 33 am" src="https://user-images.githubusercontent.com/27882826/34187869-7d5d3e04-e56e-11e7-8dec-55175151b356.png">
<img width="1280" alt="screen shot 2017-12-20 at 10 12 54 am" src="https://user-images.githubusercontent.com/27882826/34187870-7d9f9f60-e56e-11e7-8531-19fd4d444144.png">
<img width="1280" alt="screen shot 2017-12-20 at 10 13 21 am" src="https://user-images.githubusercontent.com/27882826/34187871-7dd2ac7a-e56e-11e7-89fb-8c833b0b0bae.png">

**Comment by i0ntempest** [comment]
我发现地址是www.bilibili.com/bangumi/play/epxxxxx的都无法播放
bangumi.bilibili.com/anime/6440/play#xxxxxx这样的可以播放
我在加拿大一直用着IP伪造，差不多跟你一样的情况
![screen shot 2017-12-20 at 00 34 26 2](https://user-images.githubusercontent.com/16017904/34192691-9cc6ea02-e51d-11e7-9864-662e1923c938.png)

**Comment by typcn** [comment]
您好，当前的脚本严格匹配了 anime/play 作为 url，由于本人较为繁忙，预计周五或周六推送热修复

**Comment by i0ntempest** [comment]
感谢dev！辛苦了

**Comment by typcn** [comment]
您好

已经应用热补丁修复番剧无法播放的问题，请尝试退出客户端两次并重新打开

谢谢。

**Comment by i0ntempest** [comment]
现在好像连bangumi.bilibili.com/anime/6440/play#xxxxxx这样的都没法放了。。

**Comment by typcn** [comment]
匹配错了，匹配了新的老的挂了..

**Comment by i0ntempest** [comment]
我是新旧链接都变成没法放了

**Comment by typcn** [comment]
您好，请您尝试刷新几次页面，由于网络问题，脚本可能没有在B站官方脚本之前加载。

**Comment by i0ntempest** [comment]
/bangumi/play/epxxxx 这种链接还是不行 重启很多次了 （是不是IP伪造那块的问题 要不我开个新ticket？）

**Comment by typcn** [comment]
您好，这类连接的IP伪造我暂时没有办法解决，因为服务器直接返回了 404，过段时间做一个反代
