### ISSUE TITLE
无法播放 bangumi.bilibili.com/movie/ 下的视频

### ISSUE THREAD

**Issue by Zhanzhe7878** [typcn/bilibili-mac-client#457]
## 基本信息
- 操作系统版本：macOS Sierra 10.12.6 (16G1114)
- 所在国家：CN
- 网络运营商：中国电信
- 软件版本：2.53（build 3497）

## 问题描述
无法播放 bangumi.bilibili.com/movie/****** 这个下的电影、番剧等
显示白屏（已经购买了大会员，并且在Chrome上可以观看）
## 截图
![刀剑神域-bilibili](https://user-images.githubusercontent.com/26194829/34298906-ff884336-e75a-11e7-83a6-30436de2514e.png)
http://bangumi.bilibili.com/movie/12364
![你的名字-bilibili](https://user-images.githubusercontent.com/26194829/34298991-8251f2a8-e75b-11e7-8a69-c6b4d9a2b2c6.png)
https://bangumi.bilibili.com/movie/12044
![建军大业-bilibili](https://user-images.githubusercontent.com/26194829/34299036-c076ed36-e75b-11e7-9650-b7df90dca4c3.png)
https://bangumi.bilibili.com/movie/12102
![心理罪-bilibili](https://user-images.githubusercontent.com/26194829/34299101-11ac2df6-e75c-11e7-80cc-b4fc4838cc31.png)
https://bangumi.bilibili.com/movie/12103

**Comment by typcn** [comment]
您好

已经应用热补丁修复番剧无法播放的问题，请尝试退出客户端两次并重新打开

谢谢。
