### ISSUE TITLE
看视频说解析错误

### ISSUE THREAD

**Issue by Wangiiii** [typcn/bilibili-mac-client#459]
如果您已经准备好，请删除以上文字，填写以下内容。

## 基本信息
- 操作系统版本：10.13.2
- 所在国家：中国
- 网络运营商：
- 软件版本：2.53

## 问题描述
每次打开视频都会显示解析错误，昨天晚上是这样，今天早上又试了一下，还是一样解析错误。
## 截图
<img width="1440" alt="2017-12-25 11 54 38" src="https://user-images.githubusercontent.com/34303466/34332350-abea302e-e96a-11e7-911a-26441b7765e1.png">

**Comment by typcn** [comment]
您好，是否此现象仍然存在？

**Comment by Altair-C** [comment]
我也是这个问题

**Comment by typcn** [comment]
您好，请你打开 Console.app ，重新尝试上述操作，然后将日志复制过来。

出现该问题是因为尝试请求 B 站 API 时返回的内容不是 JSON，通常由于您的网络被劫持，或者 B 站在您所在区域和运营商的服务器出现故障。

**Comment by Wangiiii** [comment]
复制哪里的日志？
