### ISSUE TITLE
求加入加速播放功能

### ISSUE THREAD

**Issue by ShawnZhong** [typcn/bilibili-mac-client#46]
mpv有内置的四个快捷键 [ , ] , { , } 可以加速减速的，
希望可以把这个快捷键功能加进去，谢谢！

**Comment by typcn** [comment]
不知道为啥 mpv 捕获不到键盘输入，我在软件层面加个快捷键吧

**Comment by typcn** [comment]
忘记看 issue 了，现在已经自动把快捷键 Pass 到了 mpv 层。
