### ISSUE TITLE
感觉需要更新了， high sierra 10.13.2 已经无法播放任何视频

### ISSUE THREAD

**Issue by ash0080** [typcn/bilibili-mac-client#461]
# 请您阅读

http://vp-hub.eqoe.cn/faq.html

如果您没有找到答案，请向下看

# 提问的智慧
如果您不是经常提交 issue，我们建议您阅读这篇文章，它可以有效节省您和开发者的时间。

http://doc.zengrong.net/smart-questions/cn.html

如果您已经准备好，请删除以上文字，填写以下内容。

## 基本信息
- 操作系统版本： high sierra 10.13.2
- 所在国家：中国
- 网络运营商：电信
- 软件版本：2.5.3

**Comment by typcn** [comment]
您好，非常抱歉，由于本人非常繁忙，需要一些时间更新，预计本周内可更新完成，请您耐心等待推送，谢谢。

**Comment by typcn** [comment]
您好

已经应用热补丁修复番剧无法播放的问题，请尝试退出客户端两次并重新打开

谢谢。
