### ISSUE TITLE
fake ip 已经全部不能使用，海外党新番无法播放。

### ISSUE THREAD

**Issue by xjw849239113** [typcn/bilibili-mac-client#463]
## 基本信息
- 操作系统版本：mac os 10.13.2
- 所在国家：加拿大
- 网络运营商：videotron
- 软件版本：2.53

## 问题描述：
Fake IP 已经全部不能使用，海外党新番无法播放。

## 截图
<img width="1276" alt="screen shot 2017-12-28 at 10 55 14 pm" src="https://user-images.githubusercontent.com/33409730/34429159-48b96d66-ec22-11e7-82aa-0e7dca0e27c6.png">

**Comment by j20120307** [comment]
Possible duplicate #457

**Comment by j20120307** [comment]
I don't have time to check the commit but the fix is not working for me. My current solution is to click on the AV number below the video title and watch.

**Comment by typcn** [comment]
Hi

This is known issue，they changed the method for getting client IP.

I will fix it if I have any time.

**Comment by typcn** [comment]
Hi

This issue has been fixed.
Please restart the app twice to finish hot update.

Thanks

**Comment by xjw849239113** [comment]
Hi there,
It works, thanks a lot!
