### ISSUE TITLE
bangumi/play/ep115089 无法播放

### ISSUE THREAD

**Issue by sanlengjingvv** [typcn/bilibili-mac-client#464]
## 基本信息
- 操作系统版本：MacOS 10.13.2
- 所在国家：中国
- 网络运营商：电信
- 软件版本：2.53 Build3497

## 问题描述
https://www.bilibili.com/bangumi/play/ep115089  无法播放，其他视频都可以播放，只发现这一个不能  
## 截图
![20180107175702](https://user-images.githubusercontent.com/6478615/34648523-a67c0804-f3d5-11e7-9979-6e7c679acf61.png)

**Comment by wrgsRay** [comment]
https://www.bilibili.com/bangumi/play/ep172119
也无法播放，相同错误

**Comment by typcn** [comment]
您好，已修复该问题，请您退出并尝试重新打开，谢谢。
