### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by joan0boy** [typcn/bilibili-mac-client#465]
我买了新的MAC PRO。装上了BILIBILI MAC，结果播放画面一直卡在99%
可是旧MAC完全没这问题。
仔细看了之后，发现画面也不太一样。感觉是少装了什么的感觉？

感谢你的回覆！
![img_0552](https://user-images.githubusercontent.com/35193131/34649750-f9b7be18-f3ef-11e7-8d66-6a5c1e0f8424.JPG)

**Comment by typcn** [comment]
您好，bilimac 缓冲视频并不会显示加载进度，请问 99% 指的是？

**Comment by typcn** [comment]
Hi

This issue has been fixed.
Please restart the app twice to finish hot update.

Thanks
