### ISSUE TITLE
bilibili for mac视频加载卡在99%

### ISSUE THREAD

**Issue by wind-snow-rain** [typcn/bilibili-mac-client#466]
没改变任何设置突然就这样了，网络也没变化。试过重启和重新安装dmg均不成功。
基本信息
IP地址：37.49.74.69
运营商：*
所在地：德国 null
DNS信息：0.0.0.0 *
复制所有信息
网速测试 平均速度：110kb/s 重新检测
常用网站链接情况重新检测
百度 链接成功 776ms
腾讯 链接成功 1670ms
阿里云 链接成功 2522ms
域名诊断 重新检测
//static.hdslb.com  508ms
//www.bilibili.com  638ms
//interface.bilibili.com  857ms
//comment.bilibili.com  1041ms
//static-s.bilibili.com  89ms
//secure.bilibili.com  197ms
//i0.hdslb.com  552ms
![841515452750_ pic_hd](https://user-images.githubusercontent.com/35277209/34746273-aeb76b8e-f593-11e7-8c57-56fb00047455.jpg) /Users/jasonma/Library/Containers/com.tencent.xinWeChat/Data/Library/Application Support/com.tencent.xinWeChat/2.0b4.0.9/0779be5e7ec7d49ef6e5819985868124/Message/MessageTemp/9e20f478899dc29eb19741386f9343c8/Image/841515452750_.pic_hd.jpg

**Comment by typcn** [comment]
您好，b站服务在欧洲没有节点，您可以尝试打开或关闭伪造ip选项，如果您必须保持伪造ip开启，建议您下载视频后观看（下载功能多线程）

**Comment by wind-snow-rain** [comment]
之前一直保持打开均正常使用，突然不好用了，尝试过打开或关闭无法解决

在 2018年1月10日 上午2:28，typcn <notifications@github.com>写道：

**Comment by typcn** [comment]
您好，b站服务在欧洲没有节点，您可以尝试打开或关闭伪造ip选项，如果您必须保持伪造ip开启，建议您下载视频后观看（下载功能多线程）

如果b站官方网页播放器可以流畅播放，请尝试关闭伪造ip。

如果下载功能都没有速度，建议您检查网络问题，尝试更换 dns 服务器，或联系您的网络运营商解决。

**Comment by wind-snow-rain** [comment]
网页播放器可以流畅播放，但是mac版关闭伪造ip也不行

typcn <notifications@github.com>于2018年1月10日 周三03:24写道：

**Comment by typcn** [comment]
关闭伪造 IP 需要按回车并关闭设置页面后生效

如果您设置了代理，代理服务器无法应用在客户端上。
建议使用 Proxifier 等软件进行代理。

如果怎么设置都慢，无能为力，请通过播放器标题栏获得视频服务器节点域名，联系B站客服。

**Comment by wind-snow-rain** [comment]
收到，我没有按回车确认，顺便请问如需更改设置里的其他选项是否也需要按回车确认？而且视频卡在99%是否一定是慢的原因？

typcn <notifications@github.com>于2018年1月10日 周三10:10写道：

**Comment by typcn** [comment]
多数选项（输入框）需要按回车并关闭设置窗口后生效。如果您可以正常使用本播放器播放本地视频，那只有网络慢的原因。您也可以尝试使用下载功能来测试网络速度。

**Comment by wind-snow-rain** [comment]
您好，再次尝试了一下，还是不行。我用safari浏览器打开b站网页是没问题的，视频全都可以顺利加载，但是用bilibili for
mac还是打开不了，每个页面的播放器都是从88%开始一点一点加载到99%然后卡住，伪造ip已经关闭。用本软件打开本地视频也没问题。

typcn <notifications@github.com>于2018年1月10日 周三10:17写道：

**Comment by typcn** [comment]
Hi

This issue has been fixed.
Please restart the app twice to finish hot update.

Thanks

**Comment by wind-snow-rain** [comment]
hello，
it can be used。thank you for the fixing!

2018-01-15 20:55 GMT+01:00 typcn <notifications@github.com>:
