### ISSUE TITLE
視頻一直小電視卡在99%

### ISSUE THREAD

**Issue by Swdm** [typcn/bilibili-mac-client#467]
## 基本信息
- 操作系统版本：macOS Sierra 10.12.6
- 所在国家：英國
- 网络运营商：StudentCom
- 软件版本：2.53

## 问题描述
由上星期開始視頻畫面全白顯示網頁版bilibili的小電視，並一直卡在99%
朋友的mac bilibili客戶端也有這個問題所以我想不是我網絡的問題，偽造ip功能也有關閉
本來的下載彈幕下載視頻按鈕也沒顯示

求修復，謝謝！QQ

## 截图
![bili](https://user-images.githubusercontent.com/35352874/34854202-1c6b826c-f730-11e7-931f-4bedb8e850fa.png)

**Comment by typcn** [comment]
您好，请问您是否可以连接到 https://static-ssl.tycdn.net/updates/bilimac.js

**Comment by Swdm** [comment]
謝謝回覆
不行連接不到

**Comment by typcn** [comment]
您好，请发一下截图

**Comment by Swdm** [comment]
您好
剛才打開網頁變成一堆碼了
![screen shot 2018-01-13 at 8 33 23 pm](https://user-images.githubusercontent.com/35352874/34909839-15e254ee-f8a1-11e7-83eb-e6cbdde2a60b.png)

**Comment by typcn** [comment]
如果可以看到这些内容，那重启客户端后应该就可以正常播放了

**Comment by typcn** [comment]
Hi

This issue has been fixed.
Please restart the app twice to finish hot update.

Thanks
