### ISSUE TITLE
小電視卡在99%

### ISSUE THREAD

**Issue by ryosuke314** [typcn/bilibili-mac-client#468]
## 基本信息
- 操作系统版本：Mac OS high sierra 10.13.12 
- 所在国家：英國
- 网络运营商：Virgin Media
- 软件版本：2.53

## 问题描述
由上星期開始視頻畫面全白顯示網頁版bilibili的小電視，並一直卡在99% （原本應該可以按play，然後有視頻會出來）
本來的下載彈幕下載視頻按鈕也沒顯示
請求修復，謝謝！
btw我可以连接到 https://static-ssl.tycdn.net/updates/bilimac.js
但我重启客户端后也沒是播放不到

## 截图

<img width="1280" alt="screen shot 2018-01-14 at 16 54 58" src="https://user-images.githubusercontent.com/35428576/34918525-b1c63150-f94b-11e7-9a4d-13a24e04c176.png">

**Comment by typcn** [comment]
您好，我无法重现此问题，可能是由于海外网络速度而导致的脚本加载顺序问题，我会尝试查看

**Comment by ryosuke314** [comment]
十分感謝，在您那麼忙的時候還要麻煩您真的非常抱歉。

**Comment by typcn** [comment]
您好，我尝试挂了我最慢的代理，还使用了多种公共VPN，依然无法重现，请问现在您能否重现该问题？

**Comment by typcn** [comment]
Hi

This issue has been fixed.
Please restart the app twice to finish hot update.

Thanks
