### ISSUE TITLE
大会员问题

### ISSUE THREAD

**Issue by laserroger** [typcn/bilibili-mac-client#470]
## 基本信息
- 操作系统版本：Mac
- 所在国家：US
- 网络运营商：NA
- 软件版本：2.53

## 问题描述

https://www.bilibili.com/bangumi/play/ep173287, 在我所看的时候仍属于大会员抢先看的部分，我已充值大会员但是无法看。

**Comment by sdogsq** [comment]
同

**Comment by typcn** [comment]
您好，客户端请求 API 时已经自动带入了当前登录用户的 Cookie，您尝试退出并重新登录是否可以正常使用？

**Comment by laserroger** [comment]
> 您好，客户端请求 API 时已经自动带入了当前登录用户的 Cookie，您尝试退出并重新登录是否可以正常使用？

好像不行，会提示

>非常抱歉，该视频为付费内容
>请升级到新版app观看
>（如无法升级请到http://app.bilibili.com 下载新版本）

弹幕可以加载

**Comment by typcn** [comment]
啊，那可能是有别的请求限制，等我下飞机回去康康

**Comment by matthew-z** [comment]
同样问题+1

**Comment by typcn** [comment]
哪位借我个帐号测试一下？。。。

**Comment by matthew-z** [comment]
我有  怎么发给你?

**Comment by typcn** [comment]
https://t.me/lostmem0ries

**Comment by matthew-z** [comment]
已发

**Comment by typcn** [comment]
刚刚逆向了一下，似乎被日了几次之后觉得防不住，B 站把之前 Android 的动态 lua 解析都删掉了，换成了静态的 java 解析，想到我也没什么时间去弄，客户端还经常更新，于是想了一个新的解析方法：

调用 HTML5 播放器进行解析，解析完了之后把视频地址发到客户端进行播放，这个大概可以一劳永逸了。。。。

**Comment by typcn** [comment]
[Bilibili.zip](https://github.com/typcn/bilibili-mac-client/files/1750033/Bilibili.zip)

各位试试这个版本？（没加数字签名，ctrl+open 忽略 gatekeeper）

**Comment by laserroger** [comment]
perfect! 3Q!

**Comment by typcn** [comment]
尴尬，CI 服务器坏了，我手动 Build 一下更新吧

**Comment by typcn** [comment]
2.54 Released
