### ISSUE TITLE
下载失败并且无法播放

### ISSUE THREAD

**Issue by momoihotaru** [typcn/bilibili-mac-client#471]
## 基本信息
- 操作系统版本：OS X EL CAPITAN 10.11.6
- 所在国家：中国 
- 网络运营商：中国联通
- 软件版本：2.53

## 问题描述
您好，上个月开始突然无法下载bilibili上的视频，一直提示错误，点击播放也提示错误，重新安装了好几次最新版本也还是不行……请问是什么原因呢？十分感谢。

## 截图
![2018-02-04 1 46 39](https://user-images.githubusercontent.com/23303085/35774701-d9783a42-09b1-11e8-86ed-7ab311669b5a.png)
![2018-02-04 1 44 33](https://user-images.githubusercontent.com/23303085/35774702-ddbdd2d8-09b1-11e8-9bc1-16fa8f994ca9.png)

**Comment by typcn** [comment]
您好 请确认您可以连接到 vp-hub.eqoe.cn
