### ISSUE TITLE
弹幕时间加载问题

### ISSUE THREAD

**Issue by Exspectate** [typcn/bilibili-mac-client#473]
## 基本信息
- 操作系统版本：10.13.3
- 所在国家：中国
- 网络运营商：联通
- 软件版本：2.53

## 问题描述
如何修改本地弹幕的时间？
看银魂下载的本地弹幕整体比视频慢了一些，想要自己写一下处理功能从哪入手？谢谢！

## 截图
无

**Comment by typcn** [comment]
您好，请查看常见问题：

“默认快捷键

   - 空格暂停/播放，上下调整音量，左右调整进度， 按 J 切换字幕，S 键截图
   - "," 和 "." 逐帧播放，"[" 和 "]" 变速播放，"L" AB 循环，Shift+L 洗脑循环
   - "Z" 和 "X" 调整字幕延迟， F 键窗口置顶， CMD+F 键全屏
   - 另外，你可以通过 Input.conf 来自定义快捷键”
