### ISSUE TITLE
请问现在获取视频的playurl是如何进行sign的呢

### ISSUE THREAD

**Issue by dongshimou** [typcn/bilibili-mac-client#475]
`https://interface.bilibili.com/v2/playurl`
web端似乎启用了V2的接口.然后发现以前的sign方式一直返回 checksum error

chrome抓取了一个正确的请求.
https://interface.bilibili.com/v2/playurl?cid=32253539&appkey=84956560bc028eb7&otype=json&type=&quality=0&qn=0&sign=0d1b3ad4dd857c060d28a31a05d13835

尝试不排序,按照以往的方式md5,依旧是checksum error.请问mac端是怎样做的呢?
我该怎样sign呢?

**Comment by typcn** [comment]
您好，我也没有最新的api，bilimac是模拟安卓端进行解析的，您可以参考 you-get 的源代码。

**Comment by dongshimou** [comment]
```
    def api_req(self, cid, quality, bangumi, bangumi_movie=False, **kwargs):
        ts = str(int(time.time()))
        if not bangumi:
            params_str = 'cid={}&player=1&quality={}&ts={}'.format(cid, quality, ts)
            chksum = hashlib.md5(bytes(params_str+self.SEC1, 'utf8')).hexdigest()
            api_url = self.api_url + params_str + '&sign=' + chksum
        else:
            mod = 'movie' if bangumi_movie else 'bangumi'
            params_str = 'cid={}&module={}&player=1&quality={}&ts={}'.format(cid, mod, quality, ts)
            chksum = hashlib.md5(bytes(params_str+self.SEC2, 'utf8')).hexdigest()
            api_url = self.bangumi_api_url + params_str + '&sign=' + chksum

        xml_str = get_content(api_url, headers={'referer': self.url, 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36'})
        return xml_str
```
[bilibili](https://github.com/soimort/you-get/blob/master/src/you_get/extractors/bilibili.py)

似乎不是V2的接口,而是以前的flash的接口...

**Comment by dongshimou** [comment]
方便讲解一下 bilimac 是怎么做的么?

我参考 you-get 的方式成功了. 参数主要有
```
cid:"",
player:"1",//flash播放器
quality:"0",//清晰度
ts:"",//unix时间戳
```
以前的方法算sign.然后header加上
```
"Accept-Encoding = identity" 
"Referer =https://www.bilibili.com/video/av号/ "
"User-Agent = chrome默认"
```

这样做貌似是被限速了... 直接抓取浏览器的 html5 的可以基本跑满带宽.而flash这个源却最大只能到500kb左右.不知道是不是我的网络问题.

**Comment by typcn** [comment]
bilimac 目前的做法是通过 Hook 浏览器内的 ajax 函数，拦截 playurl 请求，然后销毁 B 站 HTML5 播放器。

旧版的做法是模拟 android 客户端内的 lua 解析， 也不是 v2 的解析，就是旧版的 playurl platform=android 而已。

**Comment by dongshimou** [comment]
thanks.

**Comment by yangcongtougg** [comment]
@dongshimou 请问找到最新的sign的签名算法了吗

**Comment by dongshimou** [comment]
@yangcongtougg 新版的没有.还是flash的方法.源是被限速的.
