### ISSUE TITLE
mac无法播放

### ISSUE THREAD

**Issue by hbsun2113** [typcn/bilibili-mac-client#476]
## 基本信息
- 操作系统版本：mac
- 所在国家：美国或中国
- 网络运营商：移动
- 软件版本：2.54

## 问题描述
无法播放视频

## 截图
![image](https://user-images.githubusercontent.com/27994442/36945403-93ac28be-1fe8-11e8-966d-e920d65310d7.png)

**Comment by typcn** [comment]
您好，请刷新

**Comment by hbsun2113** [comment]
您好！我刷新了很多遍。

**Comment by hbsun2113** [comment]
您好！我刷新了很多遍。

**Comment by laserroger** [comment]
play/ss的没办法，play/ep的可以。转换方法：
首先你有ss页面
https://www.bilibili.com/bangumi/play/ss1640/
然后根据那个号1640改成
https://bangumi.bilibili.com/anime/1640/
的番剧页面，然后再点击里面的对应内容就可以了

**Comment by laserroger** [comment]
ss无法播放，ep可以播放，具体方法是在别的浏览器里面打开你的网站（https://www.bilibili.com/bangumi/play/ss12513）
打开source，然后搜ep_id，得到197993
然后把ss12513改成ep197993即可
https://www.bilibili.com/bangumi/play/ep197993

**Comment by typcn** [comment]
您好，已经针对该问题推送了热修复，请您退出并重新打开后再试。
