### ISSUE TITLE
很多番无法解析

### ISSUE THREAD

**Issue by EEEEElio** [typcn/bilibili-mac-client#477]
## 基本信息
- 操作系统版本：10.13.3
- 所在国家：加拿大
- 软件版本：2.54

## 问题描述
以 https://www.bilibili.com/bangumi/play/ 开头的番剧无法解析，就算我挂上VPN也还是不能解析。
## 截图
![2018-03-04 10 04 55](https://user-images.githubusercontent.com/17145926/36946979-97d3bee8-1f93-11e8-8580-b39f3da79e3e.jpg)

**Comment by typcn** [comment]
您好，请检查网络连接正常

https://labs.typcn.com/cdncheck/index.aspx

**Comment by laserroger** [comment]
play/ss的没办法，play/ep的可以。转换方法未知

**Comment by typcn** [comment]
您好，已经针对该问题推送了热修复，请您退出并重新打开后再试。
