### ISSUE TITLE
经常在打开新页面时闪退

### ISSUE THREAD

**Issue by anamewing** [typcn/bilibili-mac-client#478]
## 基本信息
- 操作系统版本： macOS 10.13.3
- 所在国家： CN
- 网络运营商： CERNET
- 软件版本： 2.54

## 问题描述
在 2.54 更新之后，经常在浏览 bilibili 网站并点击的页面上任意链接时，整个 app 闪退。
闪退后似乎没有触发 macOS 的应用崩溃提交报告小窗口。
闪退似乎在开启新页面时更常出现。

在 console 中能看到几行相关日志
在使用时陆续出现多次下面的错误：
```
错误	00:53:48.202780 +0800	sandboxd	Sandbox: com.apple.WebKit(11106) deny iokit-get-properties AAPL,IOGraphics_LER_RegTag_0
Violation:       deny iokit-get-properties AAPL,IOGraphics_LER_RegTag_0 
MetaData: {"build":"Mac OS X 10.13.3 (17D102)","action":"deny","target":["AAPL,IOGraphics_LER_RegTag_0"],"hardware":"Mac","platform_binary":"no","profile":"unknown","process":"com.apple.WebKit","op":"iokit-get-properties"}
```
以及 `deny iokit-get-properties AAPL,IOGraphics_LER_Busy_2 ` `deny iokit-get-properties AAPL,IOGraphics_LER_RegTag_1 ` `deny iokit-get-properties AAPL,IOGraphics_LER `
之后会突然
```
默认	00:54:00.246510 +0800	Bilibili	[BUG] Browser seems freeze, isLastTab: 0
默认	00:54:00.382509 +0800	kernel	AGC:: [Bilibili pid 11097 mux-aware] exiting, non-mux-aware app count 1, runtime: 0:09:24.440
```
并应用闪退。

如果需要可提供更完整的日志。

**Comment by typcn** [comment]
您好，请您尝试重启一下电脑？非 Last tab URL 为 null 通常不会出现

**Comment by anamewing** [comment]
重启并没能解决问题；尽管重启之后应用可以使用更长时间，但打开约20个新标签页后依然闪退了。
之后应用一般打开10个标签页以内就会触发闪退。

这个问题我遇到较长时间了，期间电脑也重启过多次。

**Comment by typcn** [comment]
您好，我这里测试1秒打开50个标签也无法重现这个问题，其他用户是否可以重现？

**Comment by typcn** [comment]
Fixed in 2.55
