### ISSUE TITLE
时间跳来跳去的

### ISSUE THREAD

**Issue by laserroger** [typcn/bilibili-mac-client#479]
# 请您阅读

http://vp-hub.eqoe.cn/faq.html

如果您没有找到答案，请向下看

# 提问的智慧
如果您不是经常提交 issue，我们建议您阅读这篇文章，它可以有效节省您和开发者的时间。

http://doc.zengrong.net/smart-questions/cn.html

如果您已经准备好，请删除以上文字，填写以下内容。

## 基本信息
- 操作系统版本：macOS 10.13.3
- 所在国家：US
- 网络运营商：
- 软件版本：2.5.4

## 问题描述
https://www.bilibili.com/bangumi/play/ep85276/
这个视频播放的时候时间跳来跳去的，暂时没有在其他视频中复现这一结果。例如：
6分22秒会跳到6分48秒

**Comment by typcn** [comment]
您好，这是由于 B 站压片的时候存在 GOP GAP，您可以尝试关闭硬解观看。
