### ISSUE TITLE
从最初的版本开始视频就没有出现过弹幕

### ISSUE THREAD

**Issue by zhugexiaobo** [typcn/bilibili-mac-client#48]
右下的两个按钮一个是静音后无法恢复，另一个干脆没有作用。

![image](https://cloud.githubusercontent.com/assets/2577087/8134037/adc999e8-115e-11e5-9d91-0cd2ca919ced.png)

这是控制台的输出，不知道有没有帮助。

**Comment by typcn** [comment]
/User/Shared/.fc 文件夹存在吗？

**Comment by typcn** [comment]
https://github.com/typcn/bilibili-mac-client/issues/34

你看下这个 issue

**Comment by typcn** [comment]
should fixed with https://github.com/typcn/bilibili-mac-client/commit/4fa97857dfa093a2172ea13f717f75fd771bd158

**Comment by zhugexiaobo** [comment]
可以了，谢谢。
