### ISSUE TITLE
不显示播放器框导致无法换P

### ISSUE THREAD

**Issue by wind-snow-rain** [typcn/bilibili-mac-client#480]
## 基本信息
- 操作系统版本：macOS 10.13.3
- 所在国家：德国
- 网络运营商：
- 软件版本：2.54

## 问题描述
应用内的播放器不显示播放器框，导致换P界面无法显示

## 截图
![1520341071216](https://user-images.githubusercontent.com/35277209/37033485-77ececb2-2146-11e8-8f8d-68b26b48952b.jpg)

**Comment by typcn** [comment]
您好，该情况是由于B站网页超过10秒没有载入完成，所以脚本进行了强制替换播放器。

可能是服务器太屑了，，，，您可以在 URL 最后面加 index_2.html 进行换 P。

**Comment by wind-snow-rain** [comment]
了解，谢谢


2018-03-06 14:01 GMT+01:00 typcn <notifications@github.com>:

**Comment by typcn** [comment]
Fixed in 2.55
