### ISSUE TITLE
浏览视频时，视频窗口被挤压，无法看到多p

### ISSUE THREAD

**Issue by gl09025** [typcn/bilibili-mac-client#483]
## 基本信息
- 操作系统版本：10.12.6  MacBook Pro (Retina, 13-inch, Early 2015)
- 所在国家：CN
- 网络运营商：电信
- 软件版本：2.54 （BUILD3546）

## 问题描述

bilibili浏览器内无法加载视频窗口，也看不到多p，无法选p播放。
最主要还是想看到多p的选择，因为有的视频想直接看2p。

## 截图

<img width="1392" alt="screen shot 2018-03-17 at 12 56 10" src="https://user-images.githubusercontent.com/18009385/37551937-8c89bcfc-29e5-11e8-8000-4d0f129da8d9.png">

**Comment by typcn** [comment]
您好，b站网页改版，待更新。

**Comment by gl09025** [comment]
@typcn 感谢辛勤付出

**Comment by typcn** [comment]
Fixed in 2.55
