### ISSUE TITLE
如何下载完整视频

### ISSUE THREAD

**Issue by chelseaqqq** [typcn/bilibili-mac-client#488]
## 基本信息
- 操作系统版本：mac
- 所在国家：美国
- 网络运营商：
- 软件版本：bilibilimac 2.54

## 问题描述
在设置里面没有能成功解决一个视频被分为多个flv的问题，想知道如何让它成功下载一整个视频。
## 截图
![image](https://user-images.githubusercontent.com/38440825/38832796-ae342144-4191-11e8-9dd4-823d32d6c8fb.png)

**Comment by typcn** [comment]
您好，B站服务器就是这样存的

使用 bilimac 播放时，框选多个视频可直接合并为一个播放。

如果需要使用外部播放器播放，请您使用第三方工具（例如ffmpeg）进行合并。
