### ISSUE TITLE
feature suggestions

### ISSUE THREAD

**Issue by shouya** [typcn/bilibili-mac-client#49]
昨天晚上聽說了這個客戶端，試玩了一下，感覺非常棒！

對功能性的話有一點點小建議：

1. 希望能夠快速從網頁版 bilibili.com 跳轉到 app，可以通過 bookmarklet 加上特殊的 url scheme handling （常常會收到好友分享來的 bilibili 鏈接，如果能從鏈接快速進入 app 觀看這一點會很有幫助的）
2. 目前的 app 沒有地址欄，如果希望在 app 內拷貝鏈接分享給好友的話似乎做不到
3. 離線下載列表裡的項目希望能更通過直接雙擊或者類似的方式直接播放，可以省去手動 load 視頻和彈幕的步驟

最後謝謝開發分享～

**Comment by typcn** [comment]
第一个，url scheme 是有的，打开官网下面有个“在客户端播放”，拖到书签栏即可
第二个，右键点击页面就有复制链接了
第三个，我下次优化一下，加上列表持久化和直接播放

**Comment by shouya** [comment]
嗯，很有幫助，謝謝回答！
