### ISSUE TITLE
能否提供固定播放控制模块选项？

### ISSUE THREAD

**Issue by londbell** [typcn/bilibili-mac-client#492]
## 基本信息
- 操作系统版本：10.13.4 (17E202)
- 所在国家：中国
- 网络运营商：联通
- 软件版本：Build 3548

## 问题描述
播放时，拖动窗口栏，播放控制条完全不受控制，伴随着的是窗口与控制条的闪动与位移，我的电脑没有外接屏幕，但播放控制条却经常因此移动到了屏幕之外。

## 截图
<img width="1279" alt="wx20180519-225654 2x" src="https://user-images.githubusercontent.com/7590762/40269978-24759f78-5bb8-11e8-95f2-3c5130f2b527.png">

**Comment by typcn** [comment]
请拖动窗口内容而不是标题。
