### ISSUE TITLE
打开番剧，一直显示 “正在尝试载入脚本”

### ISSUE THREAD

**Issue by dove-young** [typcn/bilibili-mac-client#496]
## 基本信息
- 操作系统版本：Mac OSX High Sierra 
- 所在国家： 中国
- 网络运营商：电信吧
- 软件版本：2.55

## 问题描述

打开番剧，一直显示 “正在尝试载入脚本”

## 截图

我好像传不了截图到GitHub了。 剧的链接在这里  https://www.bilibili.com/bangumi/play/ep199906

**Comment by typcn** [comment]
Cloud script updated.
