### ISSUE TITLE
播放視頻時客戶端崩潰

### ISSUE THREAD

**Issue by shouya** [typcn/bilibili-mac-client#50]
目前測試會崩潰的視頻：

* http://www.bilibili.com/video/av41737 ([log](http://lpaste.net/1765714450419023872))

故障可重現。

**Comment by typcn** [comment]
试了一下没有问题，应该是B站CDN的问题，尝试在设置中开启或关闭 mp4 模式

**Comment by shouya** [comment]
清空緩存後測試沒有問題。
