### ISSUE TITLE
汇报一些累积 bug

### ISSUE THREAD

**Issue by ash0080** [typcn/bilibili-mac-client#501]
# 请您阅读

http://vp-hub.eqoe.cn/faq.html

如果您没有找到答案，请向下看

# 提问的智慧
如果您不是经常提交 issue，我们建议您阅读这篇文章，它可以有效节省您和开发者的时间。

http://doc.zengrong.net/smart-questions/cn.html

如果您已经准备好，请删除以上文字，填写以下内容。

## 基本信息
- 操作系统版本：10.13.6
- 所在国家：
- 网络运营商：电信
- 软件版本：最新

## 问题描述
最近累积的问题有点多起来了,总结一下

A、脚本问题
1、播放窗口初始化位置有时候会出屏幕，拖动窗口的时候会闪动，不跟随鼠标，应该是 mousePositon 的问题；
2、初次打开某个番剧，直接播放的话，不会载入网站记录的当前话，而是从第一话开始播
3、播放器本身有部分番剧显示找不到视频内容

B、播放器问题
1、播放会间歇性卡顿，观察一般在5分钟左右，猜测是在某次缓冲后
2、卡住后一般就不能播放了，也有一定几率会往后跳一大段(5分钟左右) 再继续播放，此时如果拉时间轴，一般会自动退出

**Comment by typcn** [comment]
1. Fixed in 2.56
2 和 3 这个需要读取 B 站服务器上的一些设置

播放器问题可能视频时间太长，一定时间后 B 站 CDN 把连接拒掉了，可以通过在设置里面开大缓冲缓存，让播放器一开始就下载全部视频内容到内存里。

**Comment by ash0080** [comment]
@typcn dmg 文件打包有点问题 打开时显示无法识别

**Comment by typcn** [comment]
是 github 上的还是 typcn.download 上的？

**Comment by typcn** [comment]
typcn.download 上的文件似乎上传了一半。。少了2MB，重新上传了一下，缓存正在更新

**Comment by ash0080** [comment]
@typcn 超棒
