### ISSUE TITLE
macOS Mojave  10.14 播放器控制栏显示bug

### ISSUE THREAD

**Issue by atxiu** [typcn/bilibili-mac-client#502]
## 基本信息
- 操作系统版本：macOS Mojave 10.14
- 所在国家：cn
- 网络运营商：China Unicom
- 软件版本：Version 2.55 (Build 3548)

## 问题描述
macOS Mojave 10.14 播放番剧时播放器控制栏按钮显示白色，但可以使用

## 截图
![](https://ws3.sinaimg.cn/large/006tNc79gy1fvqupimx69j30xg06jq7k.jpg)

**Comment by typcn** [comment]
Seems simply recompile the project works..

**Comment by typcn** [comment]
Fixed in 2.56
