### ISSUE TITLE
视频无法拼接

### ISSUE THREAD

**Issue by willre** [typcn/bilibili-mac-client#510]
## 系统及软件信息
- 操作系统版本： mojave
- 软件版本： 2.5.6 build 3582

## 问题描述
如果视频有多个分片，那么下载后，还是多个分片，没有组合成一个。

**Comment by typcn** [comment]
您可以通过按住 shift 选择多个视频进行拼接播放，或采用 ffmpeg 等工具进行拼接

**Comment by willre** [comment]
如果分片很多，顺序可能会乱啊
或者
如果可以实现程序自动给分片加序号也可以的，有没有好的办法呢，最好分片的名字可以设置为视频的标题，这样下载多个视频的时候不会乱啊。

**Comment by typcn** [comment]
您好，分片文件名最后会有 -1 -2 的
