### ISSUE TITLE
无法连接/连接失败

### ISSUE THREAD

**Issue by Sukie26** [typcn/bilibili-mac-client#513]
## 基本信息
- 操作系统版本：Mac OS 10.14.2
- 所在国家：加拿大
- 网络运营商：Bell
- 软件版本：Bilibili 2.56 

## 问题描述
打开软件显示连接失败，更新显示已是最新，卸载后重新下载依旧如此

## 截图
<img width="1081" alt="screen shot 2019-01-08 at 6 33 28 pm" src="https://user-images.githubusercontent.com/46504564/50862076-3141ad80-1375-11e9-8e65-ee7caaf8cb12.png">
<img width="1081" alt="screen shot 2019-01-08 at 6 33 28 pm" src="https://user-images.githubusercontent.com/46504564/50862096-3d2d6f80-1375-11e9-84b9-bb9b6d1fdb93.png">

**Comment by typcn** [comment]
您好，建议您查看 常见问题
连接失败是本机上的 HTTP API 服务器，建议您查看 hosts 文件中的 localhost 是否被删除
