### ISSUE TITLE
部分b站视频无法播放

### ISSUE THREAD

**Issue by nnysldrwv** [typcn/bilibili-mac-client#514]
## 基本信息
- 操作系统版本：Mac OS Mojave 10.14.2 
- 所在国家：中国
- 网络运营商：联通
- 软件版本：2.56

## 问题描述
部分bilibili视频无法播放，提示“正在尝试载入脚本”和“正在截获播放地址”
## 截图
<img width="630" alt="image" src="https://user-images.githubusercontent.com/31592021/51076914-eeb40400-16d9-11e9-9f98-b8352948e873.png">
<img width="442" alt="image" src="https://user-images.githubusercontent.com/31592021/51076924-fa9fc600-16d9-11e9-8ffb-bccd40b7d63a.png">

**Comment by typcn** [comment]
您好，已经推送动态更新补丁，请您尝试退出并重新启动软件，即可使用。

**Comment by nnysldrwv** [comment]
已解决，多谢


开 2019年1月14日 在 上午12:59:19, typcn (notifications@github.com) 写到:

您好，已经推送动态更新补丁，请您尝试退出并重新启动软件，即可使用。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/typcn/bilibili-mac-client/issues/514#issuecomment-453846309>,
or mute the thread
