### ISSUE TITLE
海外党伪造IP看新番全部失效

### ISSUE THREAD

**Issue by ghost** [typcn/bilibili-mac-client#515]
基本信息

操作系统版本：mac os 10.14.2
所在国家：美国
网络运营商：
软件版本：2.56
问题描述：

Fake IP 已经全部不能使用，包括自己输入的IP，交替闪烁显示“正在尝试载入脚本”和“正在截获播放地址“，最终停在“正在截获播放地址“上。海外党新番无法播放。

**Comment by typcn** [comment]
您好，已经推送动态更新补丁，请您尝试退出并重新启动软件，即可使用。

**Comment by ghost** [comment]
Hi,

New problem here:



Sent from my iPhone

**Comment by typcn** [comment]
?

**Comment by ghost** [comment]
in other country
