### ISSUE TITLE
海外用户无法观看

### ISSUE THREAD

**Issue by BrambleXu** [typcn/bilibili-mac-client#518]
坐标日本，即使开启伪造IP后也无法看番剧。

**Comment by typcn** [comment]
请详细描述你的问题

**Comment by BrambleXu** [comment]
## 基本信息
- 操作系统版本：macOS 10.13.6
- 所在国家：日本
- 网络运营商：softbank
- 软件版本：2.56

## 问题描述

无法查看有版权的番剧。即使设置了IP伪造也没有效果。会被提示“视频不见了”，如下图所示

## 截图
![image](https://user-images.githubusercontent.com/10768193/51439073-714f4b80-1cf8-11e9-9286-82c8c9d60136.png)

**Comment by typcn** [comment]
您好，无法重现该问题，番剧页面并不会有该提示内容，只有普通视频才可能有该提示。

**Comment by BrambleXu** [comment]
重新测试了一下，发现不同番剧页面不同区域的视频连接，有的可以读取，有的无法读取。

![image](https://user-images.githubusercontent.com/10768193/51439224-65fd1f80-1cfa-11e9-9524-f8b778e65f86.png)
在【最近更新】这个box里的连接，点开之后URL能正常被解析。以约定的梦幻岛为例，被解析的URL为：https://www.bilibili.com/bangumi/play/ss26281

![image](https://user-images.githubusercontent.com/10768193/51439260-e58aee80-1cfa-11e9-98b4-a3d39dd39750.png)
但是如果从【连载动画】，【完结动画】，或者右边栏【热门】中点击连接后，URL无法解析，无法观看。此时URL为：https://www.bilibili.com/video/av40328354

**Comment by typcn** [comment]
av 开头的链接似乎有额外的在服务器端的限制..

**Comment by BrambleXu** [comment]
好吧，看样子只能找ss开头的链接了
