### ISSUE TITLE
更新2.56后不能播放。safari可以正常使用bilibili。

### ISSUE THREAD

**Issue by bingcheng1998** [typcn/bilibili-mac-client#522]
## 基本信息
- 操作系统版本：
![](https://ws3.sinaimg.cn/large/006tKfTcly1g061d2phkyj30wk0jota2.jpg)
- 所在国家：
China
- 网络运营商：
SJTU 校园网【教育网】DNS：114.114.114.114
- 软件版本：
![](https://ws1.sinaimg.cn/large/006tKfTcly1g061e2dpsfj30v40c8glz.jpg)
## 问题描述
更新前使用正常，更新后无法播放，下载等操作。
## 截图
![](https://ws1.sinaimg.cn/large/006tKfTcly1g061lmfqw9j31120u00v3.jpg)

**Comment by sgyzetrov** [comment]
command + Q 强退试一下？再打开会自动更新解析脚本

**Comment by bingcheng1998** [comment]
> command + Q 强退试一下？再打开会自动更新解析脚本

尝试了很多次，显示已经更新脚本成功。但是任然不能点击页面上面任何东西，即使鼠标变成了手的形状点击也是无效的。

还有重启后的恢复页面点击也没有反应。

**Comment by sgyzetrov** [comment]
等作者来吧，或者重启电脑试下

**Comment by bingcheng1998** [comment]
发现玄学解决办法！

首先开启`VPN`，然后就能播放量！然后退出`VPN`，任然能播放！
但是重启后又不能了，又要再上`VPN`。希望作者解决这个问题。

感谢。

**Comment by typcn** [comment]
/etc/hosts
127.0.0.1 localhost

请阅读常见问题
