### ISSUE TITLE
海外版权问题, 设置大陆IP无效

### ISSUE THREAD

**Issue by gongjiaji** [typcn/bilibili-mac-client#528]
## 基本信息
- 操作系统版本：MACOS 10.14.4 (18E226)
- 所在国家：英国
- 网络运营商：BT
- 软件版本：2.56

## 问题描述

切换到设置里面的中国大陆地址并不能成功绕开地区检测. 有多次切换地址和重启客户端.

打不开https://www.bilibili.com/video/av52040216/ 格式的番剧, 显示视频不见了. 用Chrome浏览器打开是一样的结果.

但 https://www.bilibili.com/bangumi/play/ep250642/ 格式的视频可以打开, 这是从番剧页面直接点推荐进去的, 下面有截图. 此视频的av号为AV52040216, 但可惜通过这种方式只能打开推荐的那一集, 无法选择其他的集数.

## 截图

![2](https://user-images.githubusercontent.com/18358788/57562423-634a3700-738a-11e9-80d8-11ac06e24a81.png)
![1](https://user-images.githubusercontent.com/18358788/57562424-634a3700-738a-11e9-92e4-2f1c907c4146.png)

**Comment by typcn** [comment]
这个是服务器端的限制，你可以从番剧列表入口进入，也可以用搜索功能
