### ISSUE TITLE
下载视频的时候可以默认顺便下载檀木么？

### ISSUE THREAD

**Issue by ranyouli** [typcn/bilibili-mac-client#54]
因为我用此程序打开本地视频的时候，可以选择檀木。。但是怎么下载？是否可以下载视频的时候加上同时下载檀木的选择功能？

**Comment by typcn** [comment]
下载的时候，已经自动下载弹幕了，就在相同的目录里面，有一个 XML 文件，你可以看下

**Comment by ranyouli** [comment]
啊，是哦！谢谢提醒，是我没注意～
