### ISSUE TITLE
播放器会被系统的节能选项休眠

### ISSUE THREAD

**Issue by suillven** [typcn/bilibili-mac-client#57]
休眠之后有可能会解析不出视频
极小几率出现

**Comment by typcn** [comment]
我想办法在播放时禁用下休眠，mpv 自带的那个有问题，会导致播放卡死，所以去掉了

**Comment by typcn** [comment]
直接用 mpv 没问题，但是 libmpv 貌似有点小问题，所以去掉了，我试试直接用 OC 关休眠。

这个算法是通过什么参数开启的么？

**Comment by suillven** [comment]
opengl
OpenGL video output driver. It supports extended scaling methods, dithering and color management.

By default, it tries to use fast and fail-safe settings. Use the alias  opengl-hq to use this driver with defaults set to high quality rendering.

Requires at least OpenGL 2.1.

Some features are available with OpenGL 3 capable graphics drivers only (or if the necessary extensions are available).

OpenGL ES 2.0 and 3.0 are supported as well.

Hardware decoding over OpenGL-interop is supported to some degree. Note that in this mode, some corner case might not be gracefully handled, and color space conversion and chroma upsampling is generally in the hand of the hardware decoder APIs.

scale=<filter>

bilinear
Bilinear hardware texture filtering (fastest, very low quality). This is the default for compatibility reasons.
spline36
Mid quality and speed. This is the default when using opengl-hq.
lanczos
Lanczos scaling. Provides mid quality and speed. Generally worse than spline36, but it results in a slightly sharper image which is good for some content types. The number of taps can be controlled with scale-radius, but is best left unchanged.

This filter corresponds to the old lanczos3 alias if the default radius is used, while lanczos2 corresponds to a radius of 2.

(This filter is an alias for sinc-windowed sinc)
ewa_lanczos
Elliptic weighted average Lanczos scaling. Also known as Jinc. Relatively slow, but very good quality. The radius can be controlled with scale-radius. Increasing the radius makes the filter sharper but adds more ringing.

(This filter is an alias for jinc-windowed jinc)
ewa_lanczossharp
A slightly sharpened version of ewa_lanczos, preconfigured to use an ideal radius and parameter. If your hardware can run it, this is probably what you should use by default.
mitchell
Mitchell-Netravali. The B and C parameters can be set with  scale-param1 and scale-param2. This filter is very good at downscaling (see dscale).
oversample
A version of nearest neighbour that (naively) oversamples pixels, so that pixels overlapping edges get linearly interpolated instead of rounded. This essentially removes the small imperfections and judder artifacts caused by nearest-neighbour interpolation, in exchange for adding some blur. This filter is good at temporal interpolation, and also known as "smoothmotion" (see tscale).
custom
A user-defined custom shader (see scale-shader).
There are some more filters, but most are not as useful. For a complete list, pass help as value, e.g.:

mpv --vo=opengl:scale=help

ewa_lanczos是jinc 显卡太差的话可能会卡

**Comment by typcn** [comment]
不是这个问题。。。是跨线程的问题。。

我一台 TITAN 一台 295X 怎么可能是这个问题。。
