### ISSUE TITLE
缓冲很多片子会出现速度骤降的问题

### ISSUE THREAD

**Issue by theone1989** [typcn/bilibili-mac-client#58]
海外党,有个常见现象就是刚点进去开始看,缓冲速度正常,很快,然后这一大段看完卡了一下再缓冲的话基本就没速度了,必须退出播放再点进去然后手动点到之前看到地方缓冲才会恢复速度..

**Comment by typcn** [comment]
请问解析到的是什么源？

**Comment by theone1989** [comment]
http://www.bilibili.com/video/av2505008/
http://www.bilibili.com/video/av1188206/
比如今天看的这俩就会这样..

**Comment by typcn** [comment]
这应该不是我的问题吧，乐视云本身是有限速的，刚开始快是因为 QoS 的问题吧？

你试试网页版效果一样么

**Comment by theone1989** [comment]
网页版就是全程缓冲条跟着进度条走的样子,但是能坚持看完,客户端的话差不多会以蛮快速度缓冲个几十M,然后这点缓冲的看完了就开始卡了..
原来这些都是乐视的源..估计就是源的问题

谢谢这么快回复额!!

2015-07-02 8:34 GMT-04:00 typcn <notifications@github.com>:

**Comment by typcn** [comment]
乐视有十几个国家海外 CDN 的，但是恶心的限速
