### ISSUE TITLE
希望在系统选项里增加默认隐藏弹幕功能＝v＝

### ISSUE THREAD

**Issue by summerchip** [typcn/bilibili-mac-client#59]
还有两个问题～
一个是在下载多个任务时如果意外关闭，重新开启后还没下载完的任务就会消失
还有就是，每次全屏或者退出全屏，视频的画面和声音都会暂停一下
不知是有意做成这样的还是……？

**Comment by typcn** [comment]
下载任务没做持久化，更新已经发了，下个版本加上吧。
画面暂停一下是为了防止 resize 时的 bug ，部分情况下 cpu 会飙很高

**Comment by typcn** [comment]
很抱歉长时间搁置，可以在配置文件中添加 sub-visibility = no 来默认隐藏
