### ISSUE TITLE
自动换 P

### ISSUE THREAD

**Issue by typcn** [typcn/bilibili-mac-client#6]

**Comment by BigPa** [comment]
已支持5元，望尽快支持该功能 :flushed:

**Comment by typcn** [comment]
啊。。这个 issue 已经被遗忘了，下次加上吧

**Comment by typcn** [comment]
Resolved with
a2f46f86d1fee11bb633634b8b7198b5ea4d37f1
e6eb02dbc976b81815583e5f736ce52b6aed2371
b9b39e1ee9d4ff8a02783de66883b9dd6f6e3124
dad82096831e1a9954d72c4e1d401e1e1d495abc
f981771cae328c69a4baa5f5094f1795c21b8966
