### ISSUE TITLE
/users/shared/.fc  无法建立文件 也就没有弹幕

### ISSUE THREAD

**Issue by yangyanbin1982** [typcn/bilibili-mac-client#60]
系统提示：
不能使用.作为文件名，已被系统预留。fc文件名改不了，至今没有弹幕，help!!!

**Comment by yangyanbin1982** [comment]
<img width="943" alt="2015-07-07 11 44 18" src="https://cloud.githubusercontent.com/assets/13222261/8550268/28e3adb0-2502-11e5-9fb0-1e9414e4e312.png">

**Comment by typcn** [comment]
先创建名叫 fc 的，然后用命令改名
cd /Users/Shared
mv fc .fc

**Comment by yangyanbin1982** [comment]
mv: rename fc to .fc/fc: Directory not empty
在终端里遇到这句话，fc文件夹无法改名。

**Comment by typcn** [comment]
先 rm -rf /Users/Shared/.fc

**Comment by yangyanbin1982** [comment]
yangyanbindeMacBook-Pro:shared duke$ rm -rf/users/shared/.fc
rm: illegal option -- /
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file

**Comment by typcn** [comment]
你能复制我的内容粘贴么...

**Comment by yangyanbin1982** [comment]
终于进入播放前的缓存过程了。弹幕有了。
thanks！！
