### ISSUE TITLE
希望能完善一下简单的细节

### ISSUE THREAD

**Issue by NSBeidou** [typcn/bilibili-mac-client#63]
1、把设置选项放入偏好设置中，符合Mac使用习惯
2、菜单项支持英文国际化

**Comment by typcn** [comment]
第一个是指  system preference ？

国际化没有什么用处吧，毕竟使用的都是中国人

**Comment by NSBeidou** [comment]
我是英文版的系统，所有App菜单都是英文的，只有这个打开是半英半中的，很别扭

**Comment by typcn** [comment]
啊。。其实我也是英文的，但是做这个没有什么意义，我最近也有点事，如果可以的话，可以帮忙改一下发 PR，谢谢

**Comment by NSBeidou** [comment]
好的

**Comment by typcn** [comment]
fixed in 2.03
