### ISSUE TITLE
APP放在Applications文件夹中依然没有弹幕

### ISSUE THREAD

**Issue by houjunxiong** [typcn/bilibili-mac-client#64]
APP放在Applications文件夹中依然没有弹幕，能不能帮助解决，谢谢！

**Comment by typcn** [comment]
请点击软件的右下角，
![image](https://cloud.githubusercontent.com/assets/8022103/8722585/bbd2b420-2bf8-11e5-8e84-e8d0a0d88adc.png)，然后读一遍内容

**Comment by houjunxiong** [comment]
好的，已经解决了！谢谢！
