### ISSUE TITLE
推荐个mac风格的app图标

### ISSUE THREAD

**Issue by theone1989** [typcn/bilibili-mac-client#65]
现在这个放dock上并不是很协调，所以就自己做了个
![d6eaa587-84e0-4ec1-9348-78c1985a5f3c](https://cloud.githubusercontent.com/assets/4074434/8735022/c0afe606-2bdb-11e5-9254-3376ed80469f.png)
这个是效果
![osx_icon_bilibil](https://cloud.githubusercontent.com/assets/4074434/8735030/c92934ea-2bdb-11e5-83ab-349bdb15d424.png)

**Comment by typcn** [comment]
thanks , 下次更新换上

**Comment by lightsing** [comment]
图标授权请求 @theone1989 
用于一个bilibili的私有插件，非盈利目的，不发布

**Comment by zhongfei-qian** [comment]
@lightsing 好呀..拿去呗
