### ISSUE TITLE
下载管理无法清空全部任务导致无法下载新视频

### ISSUE THREAD

**Issue by Joshua1989** [typcn/bilibili-mac-client#68]
2.00版本之前每次只能下载一个视频，如果第一个下到一半到时候选择下载第二个，那么在第一个视频下载完成后第二个视频到下载也不会开始，但是只要每次下载一个视频然后重启程序自动清空下载列表就好了

新版本重启程序会保留之前的下载记录，手动选择清空全部任务会使程序崩溃，导致升级新版本之后只能下载一个视频。虽然缓存目前不是mac客户端最迫切的需求，还是希望有空完善一下下载管理的功能

**Comment by typcn** [comment]
我这测试了很多次没有问题啊，如果要清空任务，不要点“继续下载”，直接点击清空，就OK了

**Comment by Joshua1989** [comment]
![image](https://cloud.githubusercontent.com/assets/1357342/8762210/37b13a74-2d40-11e5-8cca-6e289380f109.png)
我这里极少情况下是可以成功清除任务的，大部分时间会出现这样的错误

**Comment by typcn** [comment]
好的等我有时间改下，最近有点事

**Comment by typcn** [comment]
should fixed with 8aa88136ebdda2ad2010971decf56e432d1b358b

**Comment by Joshua1989** [comment]
删除任务没问题了，不过仍然是每次只能下载一个视频，卡在正在启动下载引擎动不了

**Comment by typcn** [comment]
是啊。。部分库不线程安全，向同一个实例添加任务得重构下载类，开两个实例有很大几率崩溃，比较蛋疼
