### ISSUE TITLE
希望加上airplay的支持，现在的Mac播放器都不支持这个很不爽

### ISSUE THREAD

**Issue by ipconfiger** [typcn/bilibili-mac-client#69]
RT

**Comment by typcn** [comment]
不支持是因为苹果根本没有开放 API ，想要滋瓷的话必须分析协议模拟一个客户端

**Comment by typcn** [comment]
已经在 2.08 版本中添加初步实现 （ https://github.com/typcn/bilibili-mac-client/tree/master/AirPlay ）
