### ISSUE TITLE
“播放，下载”选择界面出现Blocked Plug-in的文字

### ISSUE THREAD

**Issue by naijim** [typcn/bilibili-mac-client#75]
以前基本没有什么问题：先出现Blocked Plug-in的文字，然后消失，出现播放和下载两个按钮，点播放就好了。最近开始不行了，也许是Bug?

**Comment by typcn** [comment]
右键点击一下刷新试试？

**Comment by naijim** [comment]
不好意思，我这里右键没有反应。。。试着在Blocked Plug-in上右键和在网页上右键，都没有反应。。。

**Comment by typcn** [comment]
额，好吧，下次我在侧栏加个按钮

**Comment by naijim** [comment]
找到了Reload的方法，不过重新载入还是显示Blocked Plug-in
