### ISSUE TITLE
不支持标签过滤

### ISSUE THREAD

**Issue by ProtossProbe** [typcn/bilibili-mac-client#77]
<img width="900" alt="2015-07-31 17 57 11" src="https://cloud.githubusercontent.com/assets/6406279/9018525/992025b4-37ad-11e5-890e-2d78b3d8d6cd.png">
一点到某个分区的具体标签，就无法显示。

**Comment by typcn** [comment]
这是b站的js在webview下的bug，你可以点两下

**Comment by ProtossProbe** [comment]
感谢，问题解决了

**Comment by typcn** [comment]
temp fixed 8544bbef1935b8d24b29af2cdcc36500ff7f72a2
