### ISSUE TITLE
偏好设置的两个问题

### ISSUE THREAD

**Issue by jellyshen** [typcn/bilibili-mac-client#82]
1. 建议把快捷键开启偏好设置从command + ` 改为 command + , 以和系统默认方式契合，符合OSX习惯
2. 英文版系统中偏好设置英化的不完全，包括关于弹幕计算方式的说明以及顶级选项"通用“和”弹幕屏蔽“两个选项完全没有英化，希望在下一个版本中更加国际化

**Comment by typcn** [comment]
![image](https://cloud.githubusercontent.com/assets/8022103/9253254/7ede84cc-420f-11e5-86bf-8dbdce5ac23a.png)
这是啥。。。

**Comment by typcn** [comment]
翻译暂时还没完善，大家可以帮忙一起翻译。。

**Comment by anamewing** [comment]
@typcn 当前打开设置的快捷键为command+键盘左上角的重音符，希望其能改为command+逗号（以符合大多数应用的快捷键习惯）。

**Comment by typcn** [comment]
嘛，这个快捷键不是我加的，我兼容一下，加两个快捷键吧

**Comment by anamewing** [comment]
我看到似乎有人提交过修正 https://github.com/typcn/bilibili-mac-client/commit/61d30d37eed800fff6ad8cb9ea23f93b60477736 了，是还没进release？

**Comment by typcn** [comment]
哦忘记了。。还没 release ，我发布了一个调查，决定下一个功能后再出新版本。

主要是这个崩溃的问题挺蛋疼的，还不好解决。

40% 是 WebView 加上 B 站 buggy 的脚本出的问题
50% 是 播放器的问题。。。

**Comment by Tz101** [comment]
#81 已更改快捷键
顶级选项"通用“和”弹幕屏蔽“两个选项，因为使用的是 label 属性所以没有英化，已改为 title 属性。
#86 已经修复了国际化对应关系。翻译不完善，还需要大家帮忙。
