### ISSUE TITLE
调查两个问题

### ISSUE THREAD

**Issue by typcn** [typcn/bilibili-mac-client#83]
如果要解决 web 界面崩溃或卡顿的问题，哪种选择好一些？
1. 把浏览器内核换成 chromium （变大30MB）
2. 重写一个界面，替换掉 B 站原来的（我美工捉鸡有人帮忙吗）

如果解决播放器界面的崩溃问题：
1. 换一个稳定一些，久经考验的播放器内核，然后重新实现一下弹幕引擎（有点麻烦）
2. 仔细查看 libmpv 的代码，改掉这些 bug （然而并没有这么多时间）
3. 每次播放独立启动一个进程，播放完之后直接 kill 掉，比较容易，不能很彻底的解决，但是也解决掉大部分了

**Comment by gdshen** [comment]
### 关于解决web界面崩溃
1. 变大30MB是安装包增大30MB，还是安装之后所占空间变大30MB？
2. 如果换浏览器内核的话，打算一直跟着chrome上游更新内核版本么？
3. 重写界面本身太麻烦，而且大家对于界面喜好太难调，不如用官方原来的界面

### 关于解决播放器界面的崩溃
建议先用第3种方法顶上，毕竟多开一个进程并没有增大多少资源消耗，长期方面还是建议把1搞定

**Comment by typcn** [comment]
安装包增大 20MB 左右，安装后可能大于 30MB 
每隔一段时间我会手动同步官网版本，当然也可以写一个脚本自动

新建进程的话，貌似 .app 没法执行 fork，直接把播放器独立打包，注册 Url Scheme 好了。

**Comment by gdshen** [comment]
就是现在替换内核后安装包总大小大约35MB了，还是在比较能接受的范围。不过可能会增加一倍多你服务器的流量。

.app 没法fork是由于sandbox的原因么？fork出的子进程即使父进程没有权限关闭，用户可以手动关闭播放窗口，这个过程应该旧关闭了原先播放的进程了吧？

**Comment by typcn** [comment]
不是能不能关闭的，应该是 dock 栏那个图标逻辑的问题，禁止了 fork

直接新建线程也可以吧，播放完了直接 exit 就好

**Comment by gdshen** [comment]
那就先新建线程试试好了。


ps. 为什么不尝试修改UA，嵌浏览器内核之后b站直接html5播放？这样省了很多步骤，也会少很多崩溃？
(完全不懂这个client的数据获取和解码过程，求轻喷)

**Comment by typcn** [comment]
新建线程没有用的。。现在本身就是在新线程播放的，任意一个线程出现错误，还是会导致整个程序崩溃。

HTML5 播放，治标不治本啊，

1. HTML5 版资源不全，很多视频 MP4 是 AV 画质，还有的老视频根本没 mp4 格式。
2. 我测试资源占用，Flash 大约占 200% （两个核心），HTML5 占用 70% 左右，而软件（原生播放器）满弹幕也占不到 30% 的 CPU。

视频播放本身的资源占用是非常低的，大部分问题出在弹幕上

Flash 关键帧动画就不说了，FPS 很低，闪瞎狗眼不说，还很占 CPU 导致发热。
HTML5 就算使用 Canvas ，也是 JS 控制的，在弹幕量大的时候仍然会造成卡顿（何况 B 站手机版的弹幕实现还是 HTML4）。
软件现在使用的是 mpv 内置的 libass ，libass 是纯 C 实现的，直接绘制到 OpenGL 画布上，可以做到很低的占用。

目前没有找到更好的解决方案，虽然别的实现可能效果更好，但也是得不偿失的。

**Comment by gdshen** [comment]
> 任意一个线程出现错误，还是会导致整个程序崩溃。

多线程本身确实太多trick。

我最近在学习opengl，听你这么说，打算看看libass :)

**Comment by typcn** [comment]
根据软件首页上的调查问卷结果

根据 80% 的反馈，会增加多 Tab 浏览和历史记录功能，稍微改进 B 站的界面，变得美观一点，暂时没时间重写
根据 60% 的反馈，崩溃和播放器问题，可能会增加一个播放核心， mpv + vlc 两个内核切换，或者把进程独立出来
还有就是，下载引擎的崩溃问题，可能会把 aria2 独立进程，使用 RPC 控制下载，或者直接导出下载地址让用户自行下载

由于比较忙，以上功能可能需要 10 天左右的时间，<del>其实几个小时就能做好的说</del>。

**Comment by lifangzheng** [comment]
唉看来真是电脑老了 11年中的13寸air 看视频都五六十的CPU了 不过已经比直接在网页看好多啦！ 

在网页看safari卡卡卡（减少发热的缘故？）chrome热热热（温度超100）

感谢开发者啦~

**Comment by JokerQyou** [comment]
换成 chromium 的话会不会对电量消耗有影响？因为之前似乎听说 Chrome 会调整 CPU 唤醒周期之类的，不知道是 chromium 就这样呢还是 Google 魔改的锅

**Comment by typcn** [comment]
@JokerQyou Chrome 在播放声音，视频，Canvas 之类的时候才会调整，只看网页一般没事，但是，B 站这前端写的。。。估计会有影响、、

**Comment by JokerQyou** [comment]
哦，是我记错了。那个 Chrome 的 bug 只出现在 Windows 版本中。

**Comment by typcn** [comment]
浏览器方面现在已经实现，依然是 Safari 的 WebView， 但是我加了一个类似 Chrome 的多 Tab 浏览，一下午写了两千多行，累死了，明天发布新版本

**Comment by typcn** [comment]
![image](https://cloud.githubusercontent.com/assets/8022103/9683045/e1011800-533e-11e5-974f-cb406284da67.png)
这 jquery 用的。。。。卡顿主要来源于图片的 lazyload ，尝试换掉 B 站原本的一次滚动 400 个 jquery 事件的 lazyload ，找个别的
