### ISSUE TITLE
每次更新版本之后都需要重新登录，建议能够在更新后保存登录状态

### ISSUE THREAD

**Issue by gdshen** [typcn/bilibili-mac-client#87]
只能算一个feature request吧，每次更新之后都需要重新登录，感觉不是很方便。

我自己没有做过OS X的app编程不太了解，不清楚在更新替换bilibili.app时能不能在其它文件夹下保存登录相关信息用于后续重新登录。但是使用其它的app，很多都是支持更新之后保持登录状态的，比如wiz笔记。

**Comment by typcn** [comment]
我这里每次更新都保持了登录状态，Cookie 与 Safari 是完全同步的啊，是每次更新 100% 触发还是偶尔触发？

**Comment by gdshen** [comment]
是因为我一直没有在safari上登录b站的缘故么？在一直没有在safari上登录b站的情况下，100%触发更新后变为未登录状态

**Comment by typcn** [comment]
我这里只是无规律的遇到登录失效，下次把 session 存到用户文件夹算了。

**Comment by typcn** [comment]
很抱歉没有时间顾及旧 issue

经过长时间测试，这个问题与软件/更新并没有什么关系。。。只是 B 站服务器自己掉
