### ISSUE TITLE
希望能添加调整视频比例的功能

### ISSUE THREAD

**Issue by BigPa** [typcn/bilibili-mac-client#88]
B站部分视频的缺省比例不合适（拉伸或收缩），若能调节视频比例岂不美哉？

**Comment by typcn** [comment]
动态调整比较麻烦，可以暂时通过设置中的“视频撑满窗口”来实现，开启之后，视频会始终填充你的窗口大小。

主要是目前在考虑要不要换播放器，改播放器代码很费劲。
