### ISSUE TITLE
记忆窗口大小

### ISSUE THREAD

**Issue by Ikaroshu** [typcn/bilibili-mac-client#89]
可能的话能否考虑实现一下记忆窗口的大小的功能呢？
现在的版本每次关闭窗口后打开的话都是默认最大化的，这在imac上看起来特别的别扭。而再次点击缩放按钮又会使窗口变得异常的小。所以每次都得重新手动调整大小。
因此如果能够窗口能够记住每次关闭时的大小的话就好了。

**Comment by typcn** [comment]
中午加上

**Comment by Ikaroshu** [comment]
好快的回复！太感谢了🙏
