### ISSUE TITLE
从网页中调用本地播放器

### ISSUE THREAD

**Issue by JokerQyou** [typcn/bilibili-mac-client#9]
因为客户端没法开多标签页（没办法我就是这么蛋疼的人……），一般还是在浏览器里翻东西或者看评论，先找到视频后手动打开客户端输入 AV 号，略麻烦。
理想的情况可能是这样：浏览器安装扩展或者书签 / 脚本，在 b 站视频页面增加一个显眼的按钮之类的，点击之后直接调用本地播放器播放。

**Comment by typcn** [comment]
这个简单，注册个协议就可以了

**Comment by RexPi** [comment]
这个我来做吧

**Comment by typcn** [comment]
fixed with #10 
下个版本更新时将可以使用，当然也可以自己编译

**Comment by JokerQyou** [comment]
终端 `open bl://` 加地址可以播放，但 Safari 书签打开本地播放器之后是空白。

**Comment by RexPi** [comment]
确定问题了，稍后发布修复。

**Comment by typcn** [comment]
可以先使用 javascript:window.location='bl://'+window.location.hostname+window.location.pathname

**Comment by RexPi** [comment]
fixed.
