### ISSUE TITLE
希望增加调节画质的功能

### ISSUE THREAD

**Issue by iwaiting** [typcn/bilibili-mac-client#91]
有些BD版，用PC端看，还是标清的画质.....

**Comment by typcn** [comment]
刚下飞机...
默认是最高画质，如果要修改请在左上角的设置中修改，如果勾选了mp4模式尝试取消，还不行的话打开网页验证下是不是b站的问题

当然还有一种可能就是，b 站对我这个 key 限制了，你可以抓包对比下，这个情况手边没有 mac 电脑暂时无法核实，可能需要等几天。

**Comment by typcn** [comment]
我测试了一下，画质调整没有任何问题啊。。。 
随便找了个视频测试可以获取到 1080P

**Comment by iwaiting** [comment]
我之前在看高达00的BDrip，发现客户端的分辨路和网页差的有点多.....

2015-08-26 14:39 GMT+08:00 typcn <notifications@github.com>:

**Comment by typcn** [comment]
发出av号? 只要不是腾讯优酷这样专用播放器，都是可以最高画质的

**Comment by iwaiting** [comment]
不用了，我刚才又去看了一下，大部分集数都没问题，只有几个个别的，估计是B站源的问题.....谢谢...

2015-09-01 10:51 GMT+08:00 typcn <notifications@github.com>:

> 发出av号? 只要不是腾讯优酷这样专用播放器，都是可以最高画质的
