### ISSUE TITLE
“打开本地视频”界面英文按钮文字显示不全

### ISSUE THREAD

**Issue by NamedGod** [typcn/bilibili-mac-client#92]
<img width="481" alt="screen shot 2015-09-01 at 5 31 04 pm" src="https://cloud.githubusercontent.com/assets/6631870/9600728/4bb8a874-50cf-11e5-89c6-61ffb09238ac.png">

如图……

**Comment by typcn** [comment]
master 版本已经修复，还没进 Release

最近比较忙所以没更新，我会在修复一些问题（主要是崩溃）之后放出新的 Release

**Comment by NamedGod** [comment]
感谢高速的回复 m(_ _)m
