### ISSUE TITLE
窗口不能撑满屏幕

### ISSUE THREAD

**Issue by smahou** [typcn/bilibili-mac-client#93]
10.11自动隐藏菜单栏,全屏播放一次视频后浏览器界面不能撑满窗口
<img width="1280" alt="screen shot 2015-09-04 at 14 26 49" src="https://cloud.githubusercontent.com/assets/10609822/9677864/789adba2-5311-11e5-8211-3039df1e963f.png">
几个建议:
1.播放时自动全屏,不需要手动调整
2.播放时默认不开启弹幕, 需要时手动调整

**Comment by typcn** [comment]
我想应该是 Apple 没有把新的屏幕可视区域大小传过来，目前最新的代码已经可以保存窗口大小，一会我写完之后发布一个更新再试试看
