### ISSUE TITLE
最新版 2.04 点击播放/下载按钮无效

### ISSUE THREAD

**Issue by maemual** [typcn/bilibili-mac-client#95]
系统版本 10.10.5

点了没有任何反应

**Comment by typcn** [comment]
按 Cmd+Q 退出然后重新打开一下即可

忘记释放一个配置了，已经修复，明天发更新

https://github.com/typcn/bilibili-mac-client/commit/74c37e9cc6f60ec0dfd48d116a1490c8f84196aa

**Comment by typcn** [comment]
重现步骤应该是关掉所有窗口-点击dock烂图标，重开后恢复，如果是这样请告诉我下 thanks，我就不重新开机了，明天发新版

**Comment by maemual** [comment]
唔，现在说是这样的，是不是有点晚了。。。

**Comment by typcn** [comment]
没事，今天发fix版

**Comment by Exvoke** [comment]
没错，确实这样就ok了...

**Comment by typcn** [comment]
稍等我重写下播放器界面和下载管理

**Comment by toooonyy** [comment]
在 `10.10.5` 和 `2.0.6` 再次遇到此问题，播放和下载按钮无效，尝试删除并重新下载后依然无法解决

**Comment by typcn** [comment]
请查看 FAQ，确保端口没有被占用

**Comment by toooonyy** [comment]
恩，确认过的（用的 lsof），刚刚忘了说。

**Comment by typcn** [comment]
访问 localhost:23330 能不能看到返回？

**Comment by toooonyy** [comment]
Bilibili for mac http service
safari 访问返回这个

**Comment by typcn** [comment]
那可能是你把 hosts 里面的默认内容删了，加一条 127.0.01 localhost 就可以

**Comment by toooonyy** [comment]
thx，原来之前动 hosts 的时候的锅
