### ISSUE TITLE
新版不能播放

### ISSUE THREAD

**Issue by smahou** [typcn/bilibili-mac-client#98]
新版已经不能播放, CPU 很高

**Comment by typcn** [comment]
日志？堆栈？啥都没有？


我这依然不到 10% 的 CPU 啊，你尝试完全卸载，然后重新下载安装试试
![image](https://cloud.githubusercontent.com/assets/8022103/9705175/fc036346-54ed-11e5-982b-924054f8b7f0.png)

**Comment by typcn** [comment]
对了，不要在播放的同时开其他的播放类程序，包括浏览器里的视频。

OSX 的设定是同时只能有一个程序占用硬解引擎，否则自动 Fallback 软解

**Comment by JokerQyou** [comment]
呃……与其在播放器里内嵌一个浏览器，为何不在浏览器里内嵌一个播放器？如果每个页面都可以有独立的播放界面（嵌入到页面中，像 Flash 一样），那么多个页面之间切换播放的体验就会好很多。现在如果临时想看个别的视频，就必须把当前的视频关掉。

**Comment by typcn** [comment]
mpv 的 lib 不支持初始化多个实例..

**Comment by smahou** [comment]
打开增强硬解会出现不能播放的情况, 关掉才正常

**Comment by typcn** [comment]
硬解已经重构了，这次更新之后应该就可以了

**Comment by smahou** [comment]
thank you!
