### ISSUE TITLE
播放器和历史纪录的几个小建议

### ISSUE THREAD

**Issue by Ikaroshu** [typcn/bilibili-mac-client#99]
更新了新版本感觉比以前爽太多了！不过有几个小问题，大大有时间的话可以改进一下：

1. 现阶段的版本似乎无法让b站记住自己的观看纪录，如图
<img width="355" alt="2015-09-06 11 58 23" src="https://cloud.githubusercontent.com/assets/13895960/9705578/a7e3bcca-548e-11e5-85fc-48f35674a834.png">
历史记录都是我在浏览器中看过的才有。

2. 播放器会占用键盘上的播放快进和后退键，只要打开过一次播放器后如果不退出客户端播放键等都无法被itunes使用。

3. 播放器滚动鼠标快进的方向是windows式的（也就是反向的滚动）与mac的习惯不同，并且在magic mouse上很容易误触，如果能增加禁止鼠标滚动的选项就好了。

祝好！

**Comment by typcn** [comment]
b站的历史只有flash才会写入，搞不明白哪个请求写入了历史，明天反编译看下

**Comment by Ikaroshu** [comment]
chrome下bilibili助手自动替换成html5播放器仍然可以记录历史记录，不知道这个信息是否有帮助。。

**Comment by typcn** [comment]
写入播放历史已加入
